// Generated by Qleany v1.8.0 from common_entity_table.tera

// ═══════════════════════════════════════════════════════════════════════
// Leaf entity (no forward relationships) — macro implementation
// ═══════════════════════════════════════════════════════════════════════

use super::holiday_repository::HolidayTable;
use super::holiday_repository::HolidayTableRO;
use crate::entities::Holiday;
use crate::error::RepositoryError;
use crate::types::EntityId;

crate::impl_leaf_entity_table!(
    entity: Holiday,
    entity_name: "holiday",
    store_field: holidays,
    table_trait: HolidayTable,
    table_ro_trait: HolidayTableRO,
    table_struct: HolidayHashMapTable,
    table_ro_struct: HolidayHashMapTableRO,
    backward_junctions: [

        (jn_holiday_from_pace_holidays),
    ],
);
