// Generated by Qleany v1.8.0 from feature_use_case_uow.tera
//
// Hand-converted to a READ-ONLY unit of work (see save_as_uc.rs header): a
// "Save As" must not hold a whole-store write savepoint on a background thread —
// on failure that rollback would revert the entire store and erase edits the UI
// committed meanwhile. The new path/shape is now recorded into WorkInfo by the
// UI thread on completion (via update_work_info), not here. Mirrors
// save_work_uow.rs. Modify-and-protect scaffold: don't blanket-regenerate.

use crate::use_cases::save_as_uc::{SaveAsUnitOfWorkFactoryTrait, SaveAsUnitOfWorkTrait};
use anyhow::{Ok, Result};
use common::database::QueryUnitOfWork;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{
    Binder, BinderItem, BinderTag, Content, DictWord, Holiday, Milestone, Pace, ProgressSnapshot, TrashInfo, Work,
    WorkInfo,
};
use common::event::WorkManagementEvent::SaveAs;
use common::event::{Event, EventHub, Origin};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::sync::Arc;
use std::sync::Mutex;

pub struct SaveAsUnitOfWork {
    context: DbContext,
    transaction: Mutex<Option<Transaction>>,
    event_hub: Arc<EventHub>,
}

impl SaveAsUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        SaveAsUnitOfWork {
            context: db_context.clone(),
            transaction: Mutex::new(None),
            event_hub: event_hub.clone(),
        }
    }
}

impl QueryUnitOfWork for SaveAsUnitOfWork {
    fn begin_transaction(&self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        // Frozen (snapshot-isolated) read — see save_work_uow.
        *transaction = Some(Transaction::begin_frozen_read_transaction(&self.context)?);
        Ok(())
    }

    fn end_transaction(&self) -> Result<()> {
        let mut transaction = self.transaction.lock().unwrap();
        transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .end_read_transaction()?;
        Ok(())
    }
}
// Read-only unit of work for a long operation (thread_safe). Exactly the same
// macro set must be set on the use-case trait in ../use_cases/save_as_uc.rs.
#[macros::uow_action(entity = "WorkInfo", action = "GetAllRO", thread_safe = true)]
#[macros::uow_action(entity = "Work", action = "GetAllRO", thread_safe = true)]
#[macros::uow_action(entity = "Work", action = "GetRelationshipRO", thread_safe = true)]
#[macros::uow_action(entity = "TrashInfo", action = "GetAllRO", thread_safe = true)]
#[macros::uow_action(entity = "Binder", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Binder", action = "GetRelationshipRO", thread_safe = true)]
#[macros::uow_action(entity = "BinderItem", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(
    entity = "BinderItem",
    action = "GetRelationshipRO",
    thread_safe = true
)]
#[macros::uow_action(entity = "BinderTag", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Content", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "DictWord", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Pace", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Pace", action = "GetRelationshipRO", thread_safe = true)]
#[macros::uow_action(entity = "Holiday", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "Milestone", action = "GetMultiRO", thread_safe = true)]
#[macros::uow_action(entity = "WorkInfo", action = "GetRelationshipRO", thread_safe = true)]
#[macros::uow_action(entity = "ProgressSnapshot", action = "GetMultiRO", thread_safe = true)]
impl SaveAsUnitOfWorkTrait for SaveAsUnitOfWork {
    fn publish_save_as_event(&self, ids: Vec<EntityId>, data: Option<String>) {
        self.event_hub.send_event(Event {
            origin: Origin::WorkManagement(SaveAs),
            ids,
            data,
        });
    }
}

pub struct SaveAsUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl SaveAsUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        SaveAsUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl SaveAsUnitOfWorkFactoryTrait for SaveAsUnitOfWorkFactory {
    fn create(&self) -> Box<dyn SaveAsUnitOfWorkTrait> {
        Box::new(SaveAsUnitOfWork::new(&self.context, &self.event_hub))
    }
}
