// Generated by Qleany v1.4.2 from foreign_feature_controller_h.tera
#pragma once
#include "trash_management_controller.h"
#include <QCoro/QCoroQml>
#include <QCoro/QCoroQmlTask>
#include <QQmlEngine>

struct ForeignTrashManagementController : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(TrashManagementController)
    Q_PROPERTY(int undoRedoStackId READ undoRedoStackId WRITE setUndoRedoStackId NOTIFY undoRedoStackIdChanged)

  public:
    explicit ForeignTrashManagementController(QObject *parent = nullptr)
        : QObject(parent), m_controller(new Skribisto::TrashManagement::TrashManagementController(this))
    {
    }

    Q_INVOKABLE static Skribisto::TrashManagement::TrashBinderItemsDto getTrashBinderItemsDto()
    {
        return Skribisto::TrashManagement::TrashManagementController::getTrashBinderItemsDto();
    }
    Q_INVOKABLE QCoro::QmlTask trashBinderItems(
        const Skribisto::TrashManagement::TrashBinderItemsDto &trashBinderItemsDto)
    {
        return m_controller->trashBinderItems(trashBinderItemsDto);
    }

    Q_INVOKABLE static Skribisto::TrashManagement::TrashBinderDto getTrashBinderDto()
    {
        return Skribisto::TrashManagement::TrashManagementController::getTrashBinderDto();
    }
    Q_INVOKABLE QCoro::QmlTask trashBinder(const Skribisto::TrashManagement::TrashBinderDto &trashBinderDto)
    {
        return m_controller->trashBinder(trashBinderDto);
    }

    Q_INVOKABLE static Skribisto::TrashManagement::RestoreItemsDto getRestoreItemsDto()
    {
        return Skribisto::TrashManagement::TrashManagementController::getRestoreItemsDto();
    }
    Q_INVOKABLE QCoro::QmlTask restoreItems(const Skribisto::TrashManagement::RestoreItemsDto &restoreItemsDto)
    {
        return m_controller->restoreItems(restoreItemsDto);
    }

    Q_INVOKABLE QCoro::QmlTask emptyTrash()
    {
        return m_controller->emptyTrash();
    }

  Q_SIGNALS:
    void undoRedoStackIdChanged();

  private:
    void setUndoRedoStackId(int undoRedoStackId)
    {
        if (undoRedoStackId == m_controller->undoRedoStackId())
        {
            return;
        }
        m_controller->setUndoRedoStackId(undoRedoStackId);
        Q_EMIT undoRedoStackIdChanged();
    }
    int undoRedoStackId() const
    {
        return m_controller->undoRedoStackId();
    }
    Skribisto::TrashManagement::TrashManagementController *m_controller;
};
