// Generated by Qleany v1.6.1 from foreign_entity_controller_h.tera
#pragma once
#include "binder/binder_controller.h"
#include <QCoro/QCoroQml>
#include <QCoro/QCoroQmlTask>
#include <QQmlEngine>

struct ForeignBinderController : public QObject
{
    Q_OBJECT
    QML_NAMED_ELEMENT(BinderController)
    Q_PROPERTY(int undoRedoStackId READ undoRedoStackId WRITE setUndoRedoStackId NOTIFY undoRedoStackIdChanged)

  public:
    explicit ForeignBinderController(QObject *parent = nullptr)
        : QObject(parent), m_controller(new Skribisto::DirectAccess::Binder::BinderController(this))

    {
    }
    Q_INVOKABLE QCoro::QmlTask get(const QList<int> &ids) const
    {
        return m_controller->get(ids);
    }

    Q_INVOKABLE static Skribisto::DirectAccess::Binder::CreateBinderDto getCreateDto()
    {
        return Skribisto::DirectAccess::Binder::BinderController::getCreateDto();
    }

    Q_INVOKABLE QCoro::QmlTask createOrphans(const QList<Skribisto::DirectAccess::Binder::CreateBinderDto> &dtos) const
    {
        return m_controller->createOrphans(dtos);
    }

    Q_INVOKABLE QCoro::QmlTask create(const QList<Skribisto::DirectAccess::Binder::CreateBinderDto> &dtos, int ownerId,
                                      int index) const
    {
        return m_controller->create(dtos, ownerId, index);
    }

    Q_INVOKABLE static Skribisto::DirectAccess::Binder::UpdateBinderDto getUpdateDto()
    {
        return Skribisto::DirectAccess::Binder::BinderController::getUpdateDto();
    }

    Q_INVOKABLE static Skribisto::DirectAccess::Binder::UpdateBinderDto toUpdateDto(
        const Skribisto::DirectAccess::Binder::BinderDto &dto)
    {
        return Skribisto::DirectAccess::Binder::UpdateBinderDto(dto);
    }

    Q_INVOKABLE QCoro::QmlTask update(const QList<Skribisto::DirectAccess::Binder::UpdateBinderDto> &dtos) const
    {
        return m_controller->update(dtos);
    }

    Q_INVOKABLE QCoro::QmlTask updateWithRelationships(
        const QList<Skribisto::DirectAccess::Binder::BinderDto> &dtos) const
    {
        return m_controller->updateWithRelationships(dtos);
    }

    Q_INVOKABLE QCoro::QmlTask remove(const QList<int> &ids) const
    {
        return m_controller->remove(ids);
    }

    Q_INVOKABLE QCoro::QmlTask getRelationshipIds(
        const int entityId, const Skribisto::DirectAccess::Binder::BinderRelationshipField relationship) const
    {
        return m_controller->getRelationshipIds(entityId, relationship);
    }

    Q_INVOKABLE QCoro::QmlTask setRelationshipIds(
        const int entityId, const Skribisto::DirectAccess::Binder::BinderRelationshipField relationship,
        const QList<int> &relatedIds) const
    {
        return m_controller->setRelationshipIds(entityId, relationship, relatedIds);
    }

    Q_INVOKABLE QCoro::QmlTask moveRelationshipIds(
        const int entityId, const Skribisto::DirectAccess::Binder::BinderRelationshipField relationship,
        const QList<int> &relatedIds, int newIndex) const
    {
        return m_controller->moveRelationshipIds(entityId, relationship, relatedIds, newIndex);
    }

    Q_INVOKABLE QCoro::QmlTask getRelationshipIdsCount(
        const int entityId, const Skribisto::DirectAccess::Binder::BinderRelationshipField relationship) const
    {
        return m_controller->getRelationshipIdsCount(entityId, relationship);
    }

    Q_INVOKABLE QCoro::QmlTask getRelationshipIdsInRange(
        const int entityId, const Skribisto::DirectAccess::Binder::BinderRelationshipField relationship,
        const int offset, const int limit) const
    {
        return m_controller->getRelationshipIdsInRange(entityId, relationship, offset, limit);
    }

  Q_SIGNALS:
    void undoRedoStackIdChanged();

  private:
    void setUndoRedoStackId(int undoRedoStackId)
    {
        if (undoRedoStackId == m_controller->undoRedoStackId())
        {
            return;
        }
        m_controller->setUndoRedoStackId(undoRedoStackId);
        Q_EMIT undoRedoStackIdChanged();
    }
    int undoRedoStackId() const
    {
        return m_controller->undoRedoStackId();
    }
    Skribisto::DirectAccess::Binder::BinderController *m_controller;
};