// Generated by Qleany v1.4.5 from feature_uc_cpp.tera

#include "initialize_app_uc.h"

namespace Skribisto::HandlingAppLifecycle
{

InitializeAppUseCase::InitializeAppUseCase(std::unique_ptr<IInitializeAppUnitOfWork> uow) : m_uow(std::move(uow))
{
}

bool InitializeAppUseCase::execute() const
{
    try
    {
        if (!m_uow->beginTransaction())
            throw std::runtime_error("Failed to begin transaction");

        Q_UNIMPLEMENTED();
        throw std::runtime_error("Unimplemented code: HandlingAppLifecycle::InitializeAppUseCase::execute");

        if (!m_uow->commit())
            throw std::runtime_error("Failed to commit transaction");
    }
    catch (...)
    {
        m_uow->rollback();
        throw;
    }

    m_uow->publishInitializeAppSignal();
    return true;
}

} // namespace Skribisto::HandlingAppLifecycle
