// Generated by Qleany v1.6.1 from entity_h.tera
#pragma once

#include <QDateTime>
#include <QString>
#include <compare>
namespace Skribisto::Common::Entities
{

/// @brief Content entity (C++20 aggregate).
/// Supports designated initializers: Content{.id = 1, .name = "..."};
struct Content
{
    int id = 0;
    QDateTime createdAt{};
    QDateTime updatedAt{};
    bool activated = false;
    QString role = QString(QLatin1StringView(""));
    QString data = QString(QLatin1StringView(""));

    // Defaulted comparison operators (C++20 three-way comparison)
    [[nodiscard]] auto operator<=>(const Content &) const = default;
    [[nodiscard]] bool operator==(const Content &) const = default;
};

// Verify Content remains an aggregate
static_assert(std::is_aggregate_v<Content>);

} // namespace Skribisto::Common::Entities
