// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.10.0 from feature_dtos.tera
//
// NOTE: three hand-corrections, re-applied after every regeneration of this file. The first
// two are the same generator bugs mention_management/src/dtos.rs already records.
//
// 1. SPDX headers are stripped by generation; re-added.
//
// 2. The import inference emits `use common::entities::SceneAnalysis;` — that is not an
//    entity, it is declared further down in THIS file from the use case's own `enum_values`,
//    so importing it collides with its own declaration. The real dependency is `EntityId`.
//
// 3. `Eq` is derived on the `Vec` wrapper enum (SceneAnalyses) even though it wraps a row
//    type carrying `f64`, which is not `Eq`. The generator correctly omits `Eq` from the row
//    enum itself and then does not propagate that to its wrapper. With `Eq` it does not
//    compile.
use common::types::EntityId;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct AnalyzeBookDto {
    pub work_id: u64,
    pub scope_item_id: u64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct BookAnalysisResultDto {
    pub scene: SceneAnalysis,
    pub scenes: SceneAnalyses,
    pub total_words: u64,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum SceneAnalysis {
    #[default]
    Empty,
    Measured {
        item_id: EntityId,
        title: String,
        chapter_title: String,
        words: i64,
        sentence_mean: Option<f64>,
        sentence_stddev: Option<f64>,
        paragraph_mean: Option<f64>,
        punctuation_per_1k: f64,
        dialogue: Option<f64>,
    },
}

#[derive(Serialize, Deserialize, Default, Clone, Debug, PartialEq)]
pub enum SceneAnalyses {
    #[default]
    Empty,
    Measured(Vec<SceneAnalysis>),
}
