// Generated by Qleany v1.6.1 from entity_controller_cpp.tera
#include "work_controller.h"

#include "controller_command_helpers.h"
#include "direct_access/use_case_helpers/create_orphans_uc.h"
#include "direct_access/use_case_helpers/create_uc.h"
#include "direct_access/use_case_helpers/get_all_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_count_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_in_range_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_many_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_uc.h"
#include "direct_access/use_case_helpers/get_uc.h"
#include "direct_access/use_case_helpers/move_relationship_ids_uc.h"
#include "direct_access/use_case_helpers/remove_uc.h"
#include "direct_access/use_case_helpers/set_relationship_ids_uc.h"
#include "direct_access/use_case_helpers/update_uc.h"
#include "dto_mapper.h"
#include "entities/work.h"
#include "service_locator.h"
#include "work_unit_of_work.h"
#include <QCoro/QCoroTask>
#include <QCoro/QCoroTimer>

#include <memory>
#include <stdexcept>

namespace Skribisto::DirectAccess::Work
{
namespace SCE = Skribisto::Common::Entities;
namespace SCDWork = Skribisto::Common::DirectAccess::Work;
namespace Helpers = Skribisto::Common::ControllerHelpers;
namespace UCH = Skribisto::Common::DirectAccess::UseCaseHelpers;

// -- Type aliases for generic use case helpers --------------------------------

using GetUC = UCH::GetUseCase<WorkDto, DtoMapper, IWorkUnitOfWork>;
using GetAllUC = UCH::GetAllUseCase<WorkDto, DtoMapper, IWorkUnitOfWork>;
using UpdateUC = UCH::UpdateUseCase<SCE::Work, UpdateWorkDto, WorkDto, DtoMapper, IWorkUnitOfWork, true>;
using UpdateWithRelUC =
    UCH::UpdateWithRelationshipsUseCase<SCE::Work, WorkDto, WorkDto, DtoMapper, IWorkUnitOfWork, true>;
using RemoveUC = UCH::RemoveUseCase<IWorkUnitOfWork, true>;
using CreateUC = UCH::CreateUseCase<SCE::Work, CreateWorkDto, WorkDto, DtoMapper, IWorkUnitOfWork, true, false>;
using GetRelIdsUC = UCH::GetRelationshipIdsUseCase<DtoMapper, IWorkUnitOfWork, WorkRelationshipField>;
using GetRelIdsManyUC = UCH::GetRelationshipIdsManyUseCase<DtoMapper, IWorkUnitOfWork, WorkRelationshipField>;
using GetRelIdsCountUC = UCH::GetRelationshipIdsCountUseCase<DtoMapper, IWorkUnitOfWork, WorkRelationshipField>;
using GetRelIdsInRangeUC = UCH::GetRelationshipIdsInRangeUseCase<DtoMapper, IWorkUnitOfWork, WorkRelationshipField>;
using SetRelIdsUC = UCH::SetRelationshipIdsUseCase<SCE::Work, DtoMapper, IWorkUnitOfWork, WorkRelationshipField, true>;
using MoveRelIdsUC =
    UCH::MoveRelationshipIdsUseCase<SCE::Work, DtoMapper, IWorkUnitOfWork, WorkRelationshipField, true>;

// Default timeout for async command/query execution (ms)
static constexpr int kDefaultCommandTimeoutMs = 500;

WorkController::WorkController(QObject *parent, int undoRedoStackId)
    : QObject(parent), m_undoRedoStackId(undoRedoStackId)
{
    resolveDependencies();
}

void WorkController::setUndoRedoStackId(int undoRedoStackId)
{
    m_undoRedoStackId = undoRedoStackId;
}

int WorkController::undoRedoStackId() const
{
    return m_undoRedoStackId;
}

void WorkController::resolveDependencies()
{
    auto *locator = Common::ServiceLocator::instance();
    if (!locator) [[unlikely]]
        throw std::runtime_error("ServiceLocator not initialized — cannot construct WorkController");
    m_dbContext = locator->dbContext();
    m_eventRegistry = locator->eventRegistry();
    m_undoRedoSystem = locator->undoRedoSystem();
}

// ---------------------------------------------------------------------------
// CRUD Operations
// ---------------------------------------------------------------------------
QCoro::Task<QList<WorkDto>> WorkController::create(const QList<CreateWorkDto> &works, int ownerId, int index)
{
    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<CreateUC>(std::move(uow));

    co_return co_await Helpers::executeUndoableCommand<QList<WorkDto>>(
        m_undoRedoSystem, m_undoRedoStackId, u"Create works Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        works, ownerId, index);
}

QCoro::Task<QList<WorkDto>> WorkController::createOrphans(const QList<CreateWorkDto> &works)
{
    using CreateOrphanUC =
        UCH::CreateOrphanUseCase<SCE::Work, CreateWorkDto, WorkDto, DtoMapper, IWorkUnitOfWork, true>;

    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<CreateOrphanUC>(std::move(uow));

    co_return co_await Helpers::executeUndoableCommand<QList<WorkDto>>(
        m_undoRedoSystem, m_undoRedoStackId, u"Create orphan works Command"_s, std::move(useCase),
        kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        works);
}

QCoro::Task<QList<WorkDto>> WorkController::get(const QList<int> &workIds) const
{
    co_return co_await Helpers::executeReadQuery<QList<WorkDto>>(
        m_undoRedoSystem, u"Get works Query"_s, [this, workIds]() -> QList<WorkDto> {
            auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetUC>(std::move(uow));
            return useCase->execute(workIds);
        });
}

QCoro::Task<QList<WorkDto>> WorkController::getAll() const
{
    co_return co_await Helpers::executeReadQuery<QList<WorkDto>>(
        m_undoRedoSystem, u"GetAll works Query"_s, [this]() -> QList<WorkDto> {
            auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetAllUC>(std::move(uow));
            return useCase->execute();
        });
}

QCoro::Task<QList<WorkDto>> WorkController::update(const QList<UpdateWorkDto> &works)
{
    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<UpdateUC>(std::move(uow));

    co_return co_await Helpers::executeUndoableCommand<QList<WorkDto>>(
        m_undoRedoSystem, m_undoRedoStackId, u"Update works Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        works);
}

QCoro::Task<QList<WorkDto>> WorkController::updateWithRelationships(const QList<WorkDto> &works)
{
    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<UpdateWithRelUC>(std::move(uow));

    co_return co_await Helpers::executeUndoableCommand<QList<WorkDto>>(
        m_undoRedoSystem, m_undoRedoStackId, u"Update works with relationships Command"_s, std::move(useCase),
        kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        works);
}

QCoro::Task<QList<int>> WorkController::remove(const QList<int> &workIds)
{
    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<RemoveUC>(std::move(uow));

    co_return co_await Helpers::executeUndoableCommand<QList<int>>(
        m_undoRedoSystem, m_undoRedoStackId, u"Remove works Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        workIds);
}

// ---------------------------------------------------------------------------
// Relationship Operations
// ---------------------------------------------------------------------------

QCoro::Task<QList<int>> WorkController::getRelationshipIds(int workId, WorkRelationshipField relationship) const
{
    co_return co_await Helpers::executeReadQuery<QList<int>>(
        m_undoRedoSystem, u"Get Work Relationship IDs Query"_s, [this, workId, relationship]() -> QList<int> {
            auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsUC>(std::move(uow));
            return useCase->execute(workId, relationship);
        });
}

QCoro::Task<void> WorkController::setRelationshipIds(int workId, WorkRelationshipField relationship,
                                                     const QList<int> &relatedIds)
{
    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<SetRelIdsUC>(std::move(uow));

    co_await Helpers::executeUndoableCommandVoid(
        m_undoRedoSystem, m_undoRedoStackId, u"Set Work Relationship IDs Command"_s, std::move(useCase),
        kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        workId, relationship, relatedIds);
}

QCoro::Task<QHash<int, QList<int>>> WorkController::getRelationshipIdsMany(const QList<int> &workIds,
                                                                           WorkRelationshipField relationship) const
{
    co_return co_await Helpers::executeReadQuery<QHash<int, QList<int>>>(
        m_undoRedoSystem, u"Get Work Relationship IDs Many Query"_s,
        [this, workIds, relationship]() -> QHash<int, QList<int>> {
            auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsManyUC>(std::move(uow));
            return useCase->execute(workIds, relationship);
        });
}

QCoro::Task<int> WorkController::getRelationshipIdsCount(int workId, WorkRelationshipField relationship) const
{
    co_return co_await Helpers::executeReadQuery<int>(
        m_undoRedoSystem, u"Get Work Relationship IDs Count Query"_s, [this, workId, relationship]() -> int {
            auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsCountUC>(std::move(uow));
            return useCase->execute(workId, relationship);
        });
}

QCoro::Task<QList<int>> WorkController::getRelationshipIdsInRange(int workId, WorkRelationshipField relationship,
                                                                  int offset, int limit) const
{
    co_return co_await Helpers::executeReadQuery<QList<int>>(
        m_undoRedoSystem, u"Get Work Relationship IDs In Range Query"_s,
        [this, workId, relationship, offset, limit]() -> QList<int> {
            auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsInRangeUC>(std::move(uow));
            return useCase->execute(workId, relationship, offset, limit);
        });
}

QCoro::Task<QList<int>> WorkController::moveRelationshipIds(int workId, WorkRelationshipField relationship,
                                                            const QList<int> &idsToMove, int newIndex)
{
    auto uow = std::make_unique<WorkUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<MoveRelIdsUC>(std::move(uow));

    co_return co_await Helpers::executeUndoableCommand<QList<int>>(
        m_undoRedoSystem, m_undoRedoStackId, u"Move Work Relationship IDs Command"_s, std::move(useCase),
        kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        workId, relationship, idsToMove, newIndex);
}

} // namespace Skribisto::DirectAccess::Work
