// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.7.4 from entity_mod.tera

pub mod dict_word_controller;
pub mod dtos;
mod units_of_work;
