// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.10.0 from hashmap_store.tera

//! HashMap-based storage backend with O(1) snapshots.
//!
//! Uses `im::HashMap` (persistent/immutable data structure with structural sharing)
//! so that cloning the store for savepoints and undo is O(1).
//! The store uses `RwLock` for interior mutability and thread safety,
//! allowing `&HashMapStore` to be shared across threads via `Arc`.

use crate::entities::*;
use crate::snapshot::{StoreSnapshot, StoreSnapshotTrait};
use crate::types::EntityId;
use im::HashMap;
use std::sync::RwLock;

// ─────────────────────────────────────────────────────────────────────────────
// The Store
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Default)]
pub struct HashMapStore {
    // ── Entity tables ──────────────────────────────────────────────────
    pub roots: RwLock<HashMap<EntityId, Root>>,
    pub systems: RwLock<HashMap<EntityId, System>>,
    pub work_infos: RwLock<HashMap<EntityId, WorkInfo>>,
    pub progress_snapshots: RwLock<HashMap<EntityId, ProgressSnapshot>>,
    pub searchs: RwLock<HashMap<EntityId, Search>>,
    pub search_results: RwLock<HashMap<EntityId, SearchResult>>,
    pub recent_works: RwLock<HashMap<EntityId, RecentWork>>,
    pub works: RwLock<HashMap<EntityId, Work>>,
    pub smart_punctuations: RwLock<HashMap<EntityId, SmartPunctuation>>,
    pub trash_infos: RwLock<HashMap<EntityId, TrashInfo>>,
    pub paces: RwLock<HashMap<EntityId, Pace>>,
    pub holidays: RwLock<HashMap<EntityId, Holiday>>,
    pub milestones: RwLock<HashMap<EntityId, Milestone>>,
    pub comments: RwLock<HashMap<EntityId, Comment>>,
    pub footnotes: RwLock<HashMap<EntityId, Footnote>>,
    pub comment_replys: RwLock<HashMap<EntityId, CommentReply>>,
    pub binders: RwLock<HashMap<EntityId, Binder>>,
    pub binder_items: RwLock<HashMap<EntityId, BinderItem>>,
    pub binder_tags: RwLock<HashMap<EntityId, BinderTag>>,
    pub binder_statuss: RwLock<HashMap<EntityId, BinderStatus>>,
    pub contents: RwLock<HashMap<EntityId, Content>>,
    pub dict_words: RwLock<HashMap<EntityId, DictWord>>,
    pub text_replacement_rules: RwLock<HashMap<EntityId, TextReplacementRule>>,
    pub note_templates: RwLock<HashMap<EntityId, NoteTemplate>>,
    pub assets: RwLock<HashMap<EntityId, Asset>>,

    // ── Junction tables (one per forward relationship, shared for backward cleanup) ─
    pub jn_system_from_root_system: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_work_from_root_works: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_recent_work_from_system_recent_works: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_work_info_from_system_work_infos: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_progress_snapshot_from_work_info_progress_snapshots:
        RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_search_from_work_info_search: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_work_from_work_info_work: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_search_result_from_search_results: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_asset_from_work_assets: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_from_work_binders: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_comment_from_work_comments: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_dict_word_from_work_dict_words: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_footnote_from_work_footnotes: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_note_template_from_work_note_templates: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_pace_from_work_paces: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_smart_punctuation_from_work_smart_punctuation: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_status_from_work_statuses: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_tag_from_work_tags: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_text_replacement_rule_from_work_text_replacement_rules:
        RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_trash_info_from_work_trash_infos: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_from_trash_info_trashed_binder: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_trash_info_trashed_binder_item:
        RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_pace_book_item: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_holiday_from_pace_holidays: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_milestone_from_pace_milestones: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_milestone_target_item: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_content_from_comment_content: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_comment_reply_from_comment_replies: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_content_from_footnote_content: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_binder_binder_items: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_binder_item_books: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_content_from_binder_item_contents: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_binder_item_point_of_view: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_binder_item_references: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_status_from_binder_item_status: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_tag_from_binder_item_tags: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_binder_item_from_binder_tag_creates_in: RwLock<HashMap<EntityId, Vec<EntityId>>>,
    pub jn_note_template_from_binder_tag_note_template: RwLock<HashMap<EntityId, Vec<EntityId>>>,

    // ── ID counters (one per entity type) ──────────────────────────
    pub counters: RwLock<std::collections::HashMap<String, EntityId>>,

    // ── Savepoints ──────────────────────────────────────────────────
    savepoints: RwLock<std::collections::HashMap<u64, HashMapStoreSnapshot>>,
    next_savepoint_id: RwLock<u64>,
}

impl HashMapStore {
    pub fn new() -> Self {
        Self::default()
    }

    /// Clone the entire store for savepoint support. O(1) thanks to im::HashMap.
    /// (Poison-tolerant, but NOT atomic across tables — used for savepoints, which
    /// are taken on the single writer thread with no concurrent writer; use
    /// [`Self::freeze`] when an atomic cross-table snapshot is required.)
    pub fn snapshot(&self) -> HashMapStoreSnapshot {
        HashMapStoreSnapshot {
            roots: read_or_recover(&self.roots).clone(),
            systems: read_or_recover(&self.systems).clone(),
            work_infos: read_or_recover(&self.work_infos).clone(),
            progress_snapshots: read_or_recover(&self.progress_snapshots).clone(),
            searchs: read_or_recover(&self.searchs).clone(),
            search_results: read_or_recover(&self.search_results).clone(),
            recent_works: read_or_recover(&self.recent_works).clone(),
            works: read_or_recover(&self.works).clone(),
            smart_punctuations: read_or_recover(&self.smart_punctuations).clone(),
            trash_infos: read_or_recover(&self.trash_infos).clone(),
            paces: read_or_recover(&self.paces).clone(),
            holidays: read_or_recover(&self.holidays).clone(),
            milestones: read_or_recover(&self.milestones).clone(),
            comments: read_or_recover(&self.comments).clone(),
            footnotes: read_or_recover(&self.footnotes).clone(),
            comment_replys: read_or_recover(&self.comment_replys).clone(),
            binders: read_or_recover(&self.binders).clone(),
            binder_items: read_or_recover(&self.binder_items).clone(),
            binder_tags: read_or_recover(&self.binder_tags).clone(),
            binder_statuss: read_or_recover(&self.binder_statuss).clone(),
            contents: read_or_recover(&self.contents).clone(),
            dict_words: read_or_recover(&self.dict_words).clone(),
            text_replacement_rules: read_or_recover(&self.text_replacement_rules).clone(),
            note_templates: read_or_recover(&self.note_templates).clone(),
            assets: read_or_recover(&self.assets).clone(),
            jn_system_from_root_system: read_or_recover(&self.jn_system_from_root_system).clone(),
            jn_work_from_root_works: read_or_recover(&self.jn_work_from_root_works).clone(),
            jn_recent_work_from_system_recent_works: read_or_recover(
                &self.jn_recent_work_from_system_recent_works,
            )
            .clone(),
            jn_work_info_from_system_work_infos: read_or_recover(
                &self.jn_work_info_from_system_work_infos,
            )
            .clone(),
            jn_progress_snapshot_from_work_info_progress_snapshots: read_or_recover(
                &self.jn_progress_snapshot_from_work_info_progress_snapshots,
            )
            .clone(),
            jn_search_from_work_info_search: read_or_recover(&self.jn_search_from_work_info_search)
                .clone(),
            jn_work_from_work_info_work: read_or_recover(&self.jn_work_from_work_info_work).clone(),
            jn_search_result_from_search_results: read_or_recover(
                &self.jn_search_result_from_search_results,
            )
            .clone(),
            jn_asset_from_work_assets: read_or_recover(&self.jn_asset_from_work_assets).clone(),
            jn_binder_from_work_binders: read_or_recover(&self.jn_binder_from_work_binders).clone(),
            jn_comment_from_work_comments: read_or_recover(&self.jn_comment_from_work_comments)
                .clone(),
            jn_dict_word_from_work_dict_words: read_or_recover(
                &self.jn_dict_word_from_work_dict_words,
            )
            .clone(),
            jn_footnote_from_work_footnotes: read_or_recover(&self.jn_footnote_from_work_footnotes)
                .clone(),
            jn_note_template_from_work_note_templates: read_or_recover(
                &self.jn_note_template_from_work_note_templates,
            )
            .clone(),
            jn_pace_from_work_paces: read_or_recover(&self.jn_pace_from_work_paces).clone(),
            jn_smart_punctuation_from_work_smart_punctuation: read_or_recover(
                &self.jn_smart_punctuation_from_work_smart_punctuation,
            )
            .clone(),
            jn_binder_status_from_work_statuses: read_or_recover(
                &self.jn_binder_status_from_work_statuses,
            )
            .clone(),
            jn_binder_tag_from_work_tags: read_or_recover(&self.jn_binder_tag_from_work_tags)
                .clone(),
            jn_text_replacement_rule_from_work_text_replacement_rules: read_or_recover(
                &self.jn_text_replacement_rule_from_work_text_replacement_rules,
            )
            .clone(),
            jn_trash_info_from_work_trash_infos: read_or_recover(
                &self.jn_trash_info_from_work_trash_infos,
            )
            .clone(),
            jn_binder_from_trash_info_trashed_binder: read_or_recover(
                &self.jn_binder_from_trash_info_trashed_binder,
            )
            .clone(),
            jn_binder_item_from_trash_info_trashed_binder_item: read_or_recover(
                &self.jn_binder_item_from_trash_info_trashed_binder_item,
            )
            .clone(),
            jn_binder_item_from_pace_book_item: read_or_recover(
                &self.jn_binder_item_from_pace_book_item,
            )
            .clone(),
            jn_holiday_from_pace_holidays: read_or_recover(&self.jn_holiday_from_pace_holidays)
                .clone(),
            jn_milestone_from_pace_milestones: read_or_recover(
                &self.jn_milestone_from_pace_milestones,
            )
            .clone(),
            jn_binder_item_from_milestone_target_item: read_or_recover(
                &self.jn_binder_item_from_milestone_target_item,
            )
            .clone(),
            jn_content_from_comment_content: read_or_recover(&self.jn_content_from_comment_content)
                .clone(),
            jn_comment_reply_from_comment_replies: read_or_recover(
                &self.jn_comment_reply_from_comment_replies,
            )
            .clone(),
            jn_content_from_footnote_content: read_or_recover(
                &self.jn_content_from_footnote_content,
            )
            .clone(),
            jn_binder_item_from_binder_binder_items: read_or_recover(
                &self.jn_binder_item_from_binder_binder_items,
            )
            .clone(),
            jn_binder_item_from_binder_item_books: read_or_recover(
                &self.jn_binder_item_from_binder_item_books,
            )
            .clone(),
            jn_content_from_binder_item_contents: read_or_recover(
                &self.jn_content_from_binder_item_contents,
            )
            .clone(),
            jn_binder_item_from_binder_item_point_of_view: read_or_recover(
                &self.jn_binder_item_from_binder_item_point_of_view,
            )
            .clone(),
            jn_binder_item_from_binder_item_references: read_or_recover(
                &self.jn_binder_item_from_binder_item_references,
            )
            .clone(),
            jn_binder_status_from_binder_item_status: read_or_recover(
                &self.jn_binder_status_from_binder_item_status,
            )
            .clone(),
            jn_binder_tag_from_binder_item_tags: read_or_recover(
                &self.jn_binder_tag_from_binder_item_tags,
            )
            .clone(),
            jn_binder_item_from_binder_tag_creates_in: read_or_recover(
                &self.jn_binder_item_from_binder_tag_creates_in,
            )
            .clone(),
            jn_note_template_from_binder_tag_note_template: read_or_recover(
                &self.jn_note_template_from_binder_tag_note_template,
            )
            .clone(),
            counters: read_or_recover(&self.counters).clone(),
        }
    }

    /// Atomically snapshot the whole store into a fresh, isolated `HashMapStore`.
    ///
    /// Unlike [`Self::snapshot`], this holds a read guard on **every** table, junction,
    /// and the counters *simultaneously* while cloning, so the result is a single
    /// consistent point-in-time view of the store *at the instant freeze runs*.
    /// O(1) clones (im::HashMap structural sharing); the lock hold is just the
    /// clones. The returned store carries no savepoints and is meant to back a
    /// read-only (frozen) transaction.
    ///
    /// Deadlock-freedom depends on an **invariant** (unenforced by the type
    /// system): guards are acquired in the struct's declared field order (all
    /// entity tables, then all junctions, then counters), and no writer ever
    /// holds two *entity-table* locks simultaneously — each writer takes at most
    /// one entity table, then its junctions, in table-before-junction order (see
    /// `remove_multi`). A future cascade that nested two entity-table locks would
    /// violate this and could deadlock against freeze; keep cascades single-table.
    ///
    /// SCOPE: freeze is atomic w.r.t. *itself*, not w.r.t. a writer's *multi-step*
    /// cascade. A write transaction is not one critical section — its per-repo
    /// calls each lock/unlock independently — so a cascading delete/create can
    /// leave a brief window (e.g. child rows removed but the parent's junction not
    /// yet cleared) into which freeze can land and capture a cross-table-torn
    /// snapshot (`gather` then hits "entity vanished mid-read", or silently omits
    /// a just-added-but-unlinked row). This shrinks the torn-read window from the
    /// whole read to a single instant, but does not eliminate it; a store-wide
    /// writer/reader gate would be required to fully close it.
    pub fn freeze(&self) -> HashMapStore {
        // Acquire ALL read guards first (declared order), then clone under that
        // one consistent lock set.
        let g_roots = read_or_recover(&self.roots);
        let g_systems = read_or_recover(&self.systems);
        let g_work_infos = read_or_recover(&self.work_infos);
        let g_progress_snapshots = read_or_recover(&self.progress_snapshots);
        let g_searchs = read_or_recover(&self.searchs);
        let g_search_results = read_or_recover(&self.search_results);
        let g_recent_works = read_or_recover(&self.recent_works);
        let g_works = read_or_recover(&self.works);
        let g_smart_punctuations = read_or_recover(&self.smart_punctuations);
        let g_trash_infos = read_or_recover(&self.trash_infos);
        let g_paces = read_or_recover(&self.paces);
        let g_holidays = read_or_recover(&self.holidays);
        let g_milestones = read_or_recover(&self.milestones);
        let g_comments = read_or_recover(&self.comments);
        let g_footnotes = read_or_recover(&self.footnotes);
        let g_comment_replys = read_or_recover(&self.comment_replys);
        let g_binders = read_or_recover(&self.binders);
        let g_binder_items = read_or_recover(&self.binder_items);
        let g_binder_tags = read_or_recover(&self.binder_tags);
        let g_binder_statuss = read_or_recover(&self.binder_statuss);
        let g_contents = read_or_recover(&self.contents);
        let g_dict_words = read_or_recover(&self.dict_words);
        let g_text_replacement_rules = read_or_recover(&self.text_replacement_rules);
        let g_note_templates = read_or_recover(&self.note_templates);
        let g_assets = read_or_recover(&self.assets);
        let g_jn_system_from_root_system = read_or_recover(&self.jn_system_from_root_system);
        let g_jn_work_from_root_works = read_or_recover(&self.jn_work_from_root_works);
        let g_jn_recent_work_from_system_recent_works =
            read_or_recover(&self.jn_recent_work_from_system_recent_works);
        let g_jn_work_info_from_system_work_infos =
            read_or_recover(&self.jn_work_info_from_system_work_infos);
        let g_jn_progress_snapshot_from_work_info_progress_snapshots =
            read_or_recover(&self.jn_progress_snapshot_from_work_info_progress_snapshots);
        let g_jn_search_from_work_info_search =
            read_or_recover(&self.jn_search_from_work_info_search);
        let g_jn_work_from_work_info_work = read_or_recover(&self.jn_work_from_work_info_work);
        let g_jn_search_result_from_search_results =
            read_or_recover(&self.jn_search_result_from_search_results);
        let g_jn_asset_from_work_assets = read_or_recover(&self.jn_asset_from_work_assets);
        let g_jn_binder_from_work_binders = read_or_recover(&self.jn_binder_from_work_binders);
        let g_jn_comment_from_work_comments = read_or_recover(&self.jn_comment_from_work_comments);
        let g_jn_dict_word_from_work_dict_words =
            read_or_recover(&self.jn_dict_word_from_work_dict_words);
        let g_jn_footnote_from_work_footnotes =
            read_or_recover(&self.jn_footnote_from_work_footnotes);
        let g_jn_note_template_from_work_note_templates =
            read_or_recover(&self.jn_note_template_from_work_note_templates);
        let g_jn_pace_from_work_paces = read_or_recover(&self.jn_pace_from_work_paces);
        let g_jn_smart_punctuation_from_work_smart_punctuation =
            read_or_recover(&self.jn_smart_punctuation_from_work_smart_punctuation);
        let g_jn_binder_status_from_work_statuses =
            read_or_recover(&self.jn_binder_status_from_work_statuses);
        let g_jn_binder_tag_from_work_tags = read_or_recover(&self.jn_binder_tag_from_work_tags);
        let g_jn_text_replacement_rule_from_work_text_replacement_rules =
            read_or_recover(&self.jn_text_replacement_rule_from_work_text_replacement_rules);
        let g_jn_trash_info_from_work_trash_infos =
            read_or_recover(&self.jn_trash_info_from_work_trash_infos);
        let g_jn_binder_from_trash_info_trashed_binder =
            read_or_recover(&self.jn_binder_from_trash_info_trashed_binder);
        let g_jn_binder_item_from_trash_info_trashed_binder_item =
            read_or_recover(&self.jn_binder_item_from_trash_info_trashed_binder_item);
        let g_jn_binder_item_from_pace_book_item =
            read_or_recover(&self.jn_binder_item_from_pace_book_item);
        let g_jn_holiday_from_pace_holidays = read_or_recover(&self.jn_holiday_from_pace_holidays);
        let g_jn_milestone_from_pace_milestones =
            read_or_recover(&self.jn_milestone_from_pace_milestones);
        let g_jn_binder_item_from_milestone_target_item =
            read_or_recover(&self.jn_binder_item_from_milestone_target_item);
        let g_jn_content_from_comment_content =
            read_or_recover(&self.jn_content_from_comment_content);
        let g_jn_comment_reply_from_comment_replies =
            read_or_recover(&self.jn_comment_reply_from_comment_replies);
        let g_jn_content_from_footnote_content =
            read_or_recover(&self.jn_content_from_footnote_content);
        let g_jn_binder_item_from_binder_binder_items =
            read_or_recover(&self.jn_binder_item_from_binder_binder_items);
        let g_jn_binder_item_from_binder_item_books =
            read_or_recover(&self.jn_binder_item_from_binder_item_books);
        let g_jn_content_from_binder_item_contents =
            read_or_recover(&self.jn_content_from_binder_item_contents);
        let g_jn_binder_item_from_binder_item_point_of_view =
            read_or_recover(&self.jn_binder_item_from_binder_item_point_of_view);
        let g_jn_binder_item_from_binder_item_references =
            read_or_recover(&self.jn_binder_item_from_binder_item_references);
        let g_jn_binder_status_from_binder_item_status =
            read_or_recover(&self.jn_binder_status_from_binder_item_status);
        let g_jn_binder_tag_from_binder_item_tags =
            read_or_recover(&self.jn_binder_tag_from_binder_item_tags);
        let g_jn_binder_item_from_binder_tag_creates_in =
            read_or_recover(&self.jn_binder_item_from_binder_tag_creates_in);
        let g_jn_note_template_from_binder_tag_note_template =
            read_or_recover(&self.jn_note_template_from_binder_tag_note_template);
        let g_counters = read_or_recover(&self.counters);

        HashMapStore {
            roots: RwLock::new(g_roots.clone()),
            systems: RwLock::new(g_systems.clone()),
            work_infos: RwLock::new(g_work_infos.clone()),
            progress_snapshots: RwLock::new(g_progress_snapshots.clone()),
            searchs: RwLock::new(g_searchs.clone()),
            search_results: RwLock::new(g_search_results.clone()),
            recent_works: RwLock::new(g_recent_works.clone()),
            works: RwLock::new(g_works.clone()),
            smart_punctuations: RwLock::new(g_smart_punctuations.clone()),
            trash_infos: RwLock::new(g_trash_infos.clone()),
            paces: RwLock::new(g_paces.clone()),
            holidays: RwLock::new(g_holidays.clone()),
            milestones: RwLock::new(g_milestones.clone()),
            comments: RwLock::new(g_comments.clone()),
            footnotes: RwLock::new(g_footnotes.clone()),
            comment_replys: RwLock::new(g_comment_replys.clone()),
            binders: RwLock::new(g_binders.clone()),
            binder_items: RwLock::new(g_binder_items.clone()),
            binder_tags: RwLock::new(g_binder_tags.clone()),
            binder_statuss: RwLock::new(g_binder_statuss.clone()),
            contents: RwLock::new(g_contents.clone()),
            dict_words: RwLock::new(g_dict_words.clone()),
            text_replacement_rules: RwLock::new(g_text_replacement_rules.clone()),
            note_templates: RwLock::new(g_note_templates.clone()),
            assets: RwLock::new(g_assets.clone()),
            jn_system_from_root_system: RwLock::new(g_jn_system_from_root_system.clone()),
            jn_work_from_root_works: RwLock::new(g_jn_work_from_root_works.clone()),
            jn_recent_work_from_system_recent_works: RwLock::new(
                g_jn_recent_work_from_system_recent_works.clone(),
            ),
            jn_work_info_from_system_work_infos: RwLock::new(
                g_jn_work_info_from_system_work_infos.clone(),
            ),
            jn_progress_snapshot_from_work_info_progress_snapshots: RwLock::new(
                g_jn_progress_snapshot_from_work_info_progress_snapshots.clone(),
            ),
            jn_search_from_work_info_search: RwLock::new(g_jn_search_from_work_info_search.clone()),
            jn_work_from_work_info_work: RwLock::new(g_jn_work_from_work_info_work.clone()),
            jn_search_result_from_search_results: RwLock::new(
                g_jn_search_result_from_search_results.clone(),
            ),
            jn_asset_from_work_assets: RwLock::new(g_jn_asset_from_work_assets.clone()),
            jn_binder_from_work_binders: RwLock::new(g_jn_binder_from_work_binders.clone()),
            jn_comment_from_work_comments: RwLock::new(g_jn_comment_from_work_comments.clone()),
            jn_dict_word_from_work_dict_words: RwLock::new(
                g_jn_dict_word_from_work_dict_words.clone(),
            ),
            jn_footnote_from_work_footnotes: RwLock::new(g_jn_footnote_from_work_footnotes.clone()),
            jn_note_template_from_work_note_templates: RwLock::new(
                g_jn_note_template_from_work_note_templates.clone(),
            ),
            jn_pace_from_work_paces: RwLock::new(g_jn_pace_from_work_paces.clone()),
            jn_smart_punctuation_from_work_smart_punctuation: RwLock::new(
                g_jn_smart_punctuation_from_work_smart_punctuation.clone(),
            ),
            jn_binder_status_from_work_statuses: RwLock::new(
                g_jn_binder_status_from_work_statuses.clone(),
            ),
            jn_binder_tag_from_work_tags: RwLock::new(g_jn_binder_tag_from_work_tags.clone()),
            jn_text_replacement_rule_from_work_text_replacement_rules: RwLock::new(
                g_jn_text_replacement_rule_from_work_text_replacement_rules.clone(),
            ),
            jn_trash_info_from_work_trash_infos: RwLock::new(
                g_jn_trash_info_from_work_trash_infos.clone(),
            ),
            jn_binder_from_trash_info_trashed_binder: RwLock::new(
                g_jn_binder_from_trash_info_trashed_binder.clone(),
            ),
            jn_binder_item_from_trash_info_trashed_binder_item: RwLock::new(
                g_jn_binder_item_from_trash_info_trashed_binder_item.clone(),
            ),
            jn_binder_item_from_pace_book_item: RwLock::new(
                g_jn_binder_item_from_pace_book_item.clone(),
            ),
            jn_holiday_from_pace_holidays: RwLock::new(g_jn_holiday_from_pace_holidays.clone()),
            jn_milestone_from_pace_milestones: RwLock::new(
                g_jn_milestone_from_pace_milestones.clone(),
            ),
            jn_binder_item_from_milestone_target_item: RwLock::new(
                g_jn_binder_item_from_milestone_target_item.clone(),
            ),
            jn_content_from_comment_content: RwLock::new(g_jn_content_from_comment_content.clone()),
            jn_comment_reply_from_comment_replies: RwLock::new(
                g_jn_comment_reply_from_comment_replies.clone(),
            ),
            jn_content_from_footnote_content: RwLock::new(
                g_jn_content_from_footnote_content.clone(),
            ),
            jn_binder_item_from_binder_binder_items: RwLock::new(
                g_jn_binder_item_from_binder_binder_items.clone(),
            ),
            jn_binder_item_from_binder_item_books: RwLock::new(
                g_jn_binder_item_from_binder_item_books.clone(),
            ),
            jn_content_from_binder_item_contents: RwLock::new(
                g_jn_content_from_binder_item_contents.clone(),
            ),
            jn_binder_item_from_binder_item_point_of_view: RwLock::new(
                g_jn_binder_item_from_binder_item_point_of_view.clone(),
            ),
            jn_binder_item_from_binder_item_references: RwLock::new(
                g_jn_binder_item_from_binder_item_references.clone(),
            ),
            jn_binder_status_from_binder_item_status: RwLock::new(
                g_jn_binder_status_from_binder_item_status.clone(),
            ),
            jn_binder_tag_from_binder_item_tags: RwLock::new(
                g_jn_binder_tag_from_binder_item_tags.clone(),
            ),
            jn_binder_item_from_binder_tag_creates_in: RwLock::new(
                g_jn_binder_item_from_binder_tag_creates_in.clone(),
            ),
            jn_note_template_from_binder_tag_note_template: RwLock::new(
                g_jn_note_template_from_binder_tag_note_template.clone(),
            ),
            counters: RwLock::new(g_counters.clone()),
            savepoints: RwLock::new(std::collections::HashMap::new()),
            next_savepoint_id: RwLock::new(0),
        }
    }

    /// Restore from a savepoint snapshot.
    pub fn restore(&self, snap: &HashMapStoreSnapshot) {
        *write_or_recover(&self.roots) = snap.roots.clone();
        *write_or_recover(&self.systems) = snap.systems.clone();
        *write_or_recover(&self.work_infos) = snap.work_infos.clone();
        *write_or_recover(&self.progress_snapshots) = snap.progress_snapshots.clone();
        *write_or_recover(&self.searchs) = snap.searchs.clone();
        *write_or_recover(&self.search_results) = snap.search_results.clone();
        *write_or_recover(&self.recent_works) = snap.recent_works.clone();
        *write_or_recover(&self.works) = snap.works.clone();
        *write_or_recover(&self.smart_punctuations) = snap.smart_punctuations.clone();
        *write_or_recover(&self.trash_infos) = snap.trash_infos.clone();
        *write_or_recover(&self.paces) = snap.paces.clone();
        *write_or_recover(&self.holidays) = snap.holidays.clone();
        *write_or_recover(&self.milestones) = snap.milestones.clone();
        *write_or_recover(&self.comments) = snap.comments.clone();
        *write_or_recover(&self.footnotes) = snap.footnotes.clone();
        *write_or_recover(&self.comment_replys) = snap.comment_replys.clone();
        *write_or_recover(&self.binders) = snap.binders.clone();
        *write_or_recover(&self.binder_items) = snap.binder_items.clone();
        *write_or_recover(&self.binder_tags) = snap.binder_tags.clone();
        *write_or_recover(&self.binder_statuss) = snap.binder_statuss.clone();
        *write_or_recover(&self.contents) = snap.contents.clone();
        *write_or_recover(&self.dict_words) = snap.dict_words.clone();
        *write_or_recover(&self.text_replacement_rules) = snap.text_replacement_rules.clone();
        *write_or_recover(&self.note_templates) = snap.note_templates.clone();
        *write_or_recover(&self.assets) = snap.assets.clone();
        *write_or_recover(&self.jn_system_from_root_system) =
            snap.jn_system_from_root_system.clone();
        *write_or_recover(&self.jn_work_from_root_works) = snap.jn_work_from_root_works.clone();
        *write_or_recover(&self.jn_recent_work_from_system_recent_works) =
            snap.jn_recent_work_from_system_recent_works.clone();
        *write_or_recover(&self.jn_work_info_from_system_work_infos) =
            snap.jn_work_info_from_system_work_infos.clone();
        *write_or_recover(&self.jn_progress_snapshot_from_work_info_progress_snapshots) = snap
            .jn_progress_snapshot_from_work_info_progress_snapshots
            .clone();
        *write_or_recover(&self.jn_search_from_work_info_search) =
            snap.jn_search_from_work_info_search.clone();
        *write_or_recover(&self.jn_work_from_work_info_work) =
            snap.jn_work_from_work_info_work.clone();
        *write_or_recover(&self.jn_search_result_from_search_results) =
            snap.jn_search_result_from_search_results.clone();
        *write_or_recover(&self.jn_asset_from_work_assets) = snap.jn_asset_from_work_assets.clone();
        *write_or_recover(&self.jn_binder_from_work_binders) =
            snap.jn_binder_from_work_binders.clone();
        *write_or_recover(&self.jn_comment_from_work_comments) =
            snap.jn_comment_from_work_comments.clone();
        *write_or_recover(&self.jn_dict_word_from_work_dict_words) =
            snap.jn_dict_word_from_work_dict_words.clone();
        *write_or_recover(&self.jn_footnote_from_work_footnotes) =
            snap.jn_footnote_from_work_footnotes.clone();
        *write_or_recover(&self.jn_note_template_from_work_note_templates) =
            snap.jn_note_template_from_work_note_templates.clone();
        *write_or_recover(&self.jn_pace_from_work_paces) = snap.jn_pace_from_work_paces.clone();
        *write_or_recover(&self.jn_smart_punctuation_from_work_smart_punctuation) = snap
            .jn_smart_punctuation_from_work_smart_punctuation
            .clone();
        *write_or_recover(&self.jn_binder_status_from_work_statuses) =
            snap.jn_binder_status_from_work_statuses.clone();
        *write_or_recover(&self.jn_binder_tag_from_work_tags) =
            snap.jn_binder_tag_from_work_tags.clone();
        *write_or_recover(&self.jn_text_replacement_rule_from_work_text_replacement_rules) = snap
            .jn_text_replacement_rule_from_work_text_replacement_rules
            .clone();
        *write_or_recover(&self.jn_trash_info_from_work_trash_infos) =
            snap.jn_trash_info_from_work_trash_infos.clone();
        *write_or_recover(&self.jn_binder_from_trash_info_trashed_binder) =
            snap.jn_binder_from_trash_info_trashed_binder.clone();
        *write_or_recover(&self.jn_binder_item_from_trash_info_trashed_binder_item) = snap
            .jn_binder_item_from_trash_info_trashed_binder_item
            .clone();
        *write_or_recover(&self.jn_binder_item_from_pace_book_item) =
            snap.jn_binder_item_from_pace_book_item.clone();
        *write_or_recover(&self.jn_holiday_from_pace_holidays) =
            snap.jn_holiday_from_pace_holidays.clone();
        *write_or_recover(&self.jn_milestone_from_pace_milestones) =
            snap.jn_milestone_from_pace_milestones.clone();
        *write_or_recover(&self.jn_binder_item_from_milestone_target_item) =
            snap.jn_binder_item_from_milestone_target_item.clone();
        *write_or_recover(&self.jn_content_from_comment_content) =
            snap.jn_content_from_comment_content.clone();
        *write_or_recover(&self.jn_comment_reply_from_comment_replies) =
            snap.jn_comment_reply_from_comment_replies.clone();
        *write_or_recover(&self.jn_content_from_footnote_content) =
            snap.jn_content_from_footnote_content.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_binder_items) =
            snap.jn_binder_item_from_binder_binder_items.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_item_books) =
            snap.jn_binder_item_from_binder_item_books.clone();
        *write_or_recover(&self.jn_content_from_binder_item_contents) =
            snap.jn_content_from_binder_item_contents.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_item_point_of_view) =
            snap.jn_binder_item_from_binder_item_point_of_view.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_item_references) =
            snap.jn_binder_item_from_binder_item_references.clone();
        *write_or_recover(&self.jn_binder_status_from_binder_item_status) =
            snap.jn_binder_status_from_binder_item_status.clone();
        *write_or_recover(&self.jn_binder_tag_from_binder_item_tags) =
            snap.jn_binder_tag_from_binder_item_tags.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_tag_creates_in) =
            snap.jn_binder_item_from_binder_tag_creates_in.clone();
        *write_or_recover(&self.jn_note_template_from_binder_tag_note_template) =
            snap.jn_note_template_from_binder_tag_note_template.clone();
        *write_or_recover(&self.counters) = snap.counters.clone();
    }

    /// Create a savepoint by snapshotting the entire store. Returns a savepoint id.
    /// O(1) thanks to im::HashMap structural sharing.
    pub fn create_savepoint(&self) -> u64 {
        let snap = self.snapshot();
        let mut id_counter = write_or_recover(&self.next_savepoint_id);
        let id = *id_counter;
        *id_counter += 1;
        write_or_recover(&self.savepoints).insert(id, snap);
        id
    }

    /// Restore the store to a previously created savepoint.
    pub fn restore_savepoint(&self, savepoint_id: u64) {
        // A missing savepoint is a caller bug, but this is reached from
        // `Transaction`'s **`Drop`-time rollback** — and panicking in a `Drop`
        // that is itself running because of an earlier panic aborts the process
        // outright, no matter what the panic strategy is. That double-panic is
        // exactly what this module's poison recovery exists to avoid, so the
        // rollback must not be the thing that reintroduces it.
        //
        // Loud in a debug build, a no-op in a shipped one: nothing to restore
        // to means the store simply stays as it is.
        let Some(snap) = read_or_recover(&self.savepoints)
            .get(&savepoint_id)
            .cloned()
        else {
            debug_assert!(
                false,
                "restore_savepoint: savepoint {savepoint_id} does not exist — it was already \
                 restored, discarded, or never created"
            );
            return;
        };
        self.restore(&snap);
    }

    /// Discard a savepoint without restoring (used on successful commit, and
    /// after a rollback so a rolled-back transaction doesn't leak its snapshot).
    pub fn discard_savepoint(&self, savepoint_id: u64) {
        write_or_recover(&self.savepoints).remove(&savepoint_id);
    }

    /// Get-and-increment counter for an entity type.
    pub(crate) fn next_id(&self, entity_name: &str) -> EntityId {
        let mut counters = write_or_recover(&self.counters);
        let counter = counters.entry(entity_name.to_string()).or_insert(1);
        let id = *counter;
        *counter += 1;
        id
    }

    /// Restore entity and junction data but preserve current counters.
    /// Used for undo snapshots where IDs must remain monotonically increasing.
    pub fn restore_without_counters(&self, snap: &HashMapStoreSnapshot) {
        *write_or_recover(&self.roots) = snap.roots.clone();
        *write_or_recover(&self.systems) = snap.systems.clone();
        *write_or_recover(&self.work_infos) = snap.work_infos.clone();
        *write_or_recover(&self.progress_snapshots) = snap.progress_snapshots.clone();
        *write_or_recover(&self.searchs) = snap.searchs.clone();
        *write_or_recover(&self.search_results) = snap.search_results.clone();
        *write_or_recover(&self.recent_works) = snap.recent_works.clone();
        *write_or_recover(&self.works) = snap.works.clone();
        *write_or_recover(&self.smart_punctuations) = snap.smart_punctuations.clone();
        *write_or_recover(&self.trash_infos) = snap.trash_infos.clone();
        *write_or_recover(&self.paces) = snap.paces.clone();
        *write_or_recover(&self.holidays) = snap.holidays.clone();
        *write_or_recover(&self.milestones) = snap.milestones.clone();
        *write_or_recover(&self.comments) = snap.comments.clone();
        *write_or_recover(&self.footnotes) = snap.footnotes.clone();
        *write_or_recover(&self.comment_replys) = snap.comment_replys.clone();
        *write_or_recover(&self.binders) = snap.binders.clone();
        *write_or_recover(&self.binder_items) = snap.binder_items.clone();
        *write_or_recover(&self.binder_tags) = snap.binder_tags.clone();
        *write_or_recover(&self.binder_statuss) = snap.binder_statuss.clone();
        *write_or_recover(&self.contents) = snap.contents.clone();
        *write_or_recover(&self.dict_words) = snap.dict_words.clone();
        *write_or_recover(&self.text_replacement_rules) = snap.text_replacement_rules.clone();
        *write_or_recover(&self.note_templates) = snap.note_templates.clone();
        *write_or_recover(&self.assets) = snap.assets.clone();
        *write_or_recover(&self.jn_system_from_root_system) =
            snap.jn_system_from_root_system.clone();
        *write_or_recover(&self.jn_work_from_root_works) = snap.jn_work_from_root_works.clone();
        *write_or_recover(&self.jn_recent_work_from_system_recent_works) =
            snap.jn_recent_work_from_system_recent_works.clone();
        *write_or_recover(&self.jn_work_info_from_system_work_infos) =
            snap.jn_work_info_from_system_work_infos.clone();
        *write_or_recover(&self.jn_progress_snapshot_from_work_info_progress_snapshots) = snap
            .jn_progress_snapshot_from_work_info_progress_snapshots
            .clone();
        *write_or_recover(&self.jn_search_from_work_info_search) =
            snap.jn_search_from_work_info_search.clone();
        *write_or_recover(&self.jn_work_from_work_info_work) =
            snap.jn_work_from_work_info_work.clone();
        *write_or_recover(&self.jn_search_result_from_search_results) =
            snap.jn_search_result_from_search_results.clone();
        *write_or_recover(&self.jn_asset_from_work_assets) = snap.jn_asset_from_work_assets.clone();
        *write_or_recover(&self.jn_binder_from_work_binders) =
            snap.jn_binder_from_work_binders.clone();
        *write_or_recover(&self.jn_comment_from_work_comments) =
            snap.jn_comment_from_work_comments.clone();
        *write_or_recover(&self.jn_dict_word_from_work_dict_words) =
            snap.jn_dict_word_from_work_dict_words.clone();
        *write_or_recover(&self.jn_footnote_from_work_footnotes) =
            snap.jn_footnote_from_work_footnotes.clone();
        *write_or_recover(&self.jn_note_template_from_work_note_templates) =
            snap.jn_note_template_from_work_note_templates.clone();
        *write_or_recover(&self.jn_pace_from_work_paces) = snap.jn_pace_from_work_paces.clone();
        *write_or_recover(&self.jn_smart_punctuation_from_work_smart_punctuation) = snap
            .jn_smart_punctuation_from_work_smart_punctuation
            .clone();
        *write_or_recover(&self.jn_binder_status_from_work_statuses) =
            snap.jn_binder_status_from_work_statuses.clone();
        *write_or_recover(&self.jn_binder_tag_from_work_tags) =
            snap.jn_binder_tag_from_work_tags.clone();
        *write_or_recover(&self.jn_text_replacement_rule_from_work_text_replacement_rules) = snap
            .jn_text_replacement_rule_from_work_text_replacement_rules
            .clone();
        *write_or_recover(&self.jn_trash_info_from_work_trash_infos) =
            snap.jn_trash_info_from_work_trash_infos.clone();
        *write_or_recover(&self.jn_binder_from_trash_info_trashed_binder) =
            snap.jn_binder_from_trash_info_trashed_binder.clone();
        *write_or_recover(&self.jn_binder_item_from_trash_info_trashed_binder_item) = snap
            .jn_binder_item_from_trash_info_trashed_binder_item
            .clone();
        *write_or_recover(&self.jn_binder_item_from_pace_book_item) =
            snap.jn_binder_item_from_pace_book_item.clone();
        *write_or_recover(&self.jn_holiday_from_pace_holidays) =
            snap.jn_holiday_from_pace_holidays.clone();
        *write_or_recover(&self.jn_milestone_from_pace_milestones) =
            snap.jn_milestone_from_pace_milestones.clone();
        *write_or_recover(&self.jn_binder_item_from_milestone_target_item) =
            snap.jn_binder_item_from_milestone_target_item.clone();
        *write_or_recover(&self.jn_content_from_comment_content) =
            snap.jn_content_from_comment_content.clone();
        *write_or_recover(&self.jn_comment_reply_from_comment_replies) =
            snap.jn_comment_reply_from_comment_replies.clone();
        *write_or_recover(&self.jn_content_from_footnote_content) =
            snap.jn_content_from_footnote_content.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_binder_items) =
            snap.jn_binder_item_from_binder_binder_items.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_item_books) =
            snap.jn_binder_item_from_binder_item_books.clone();
        *write_or_recover(&self.jn_content_from_binder_item_contents) =
            snap.jn_content_from_binder_item_contents.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_item_point_of_view) =
            snap.jn_binder_item_from_binder_item_point_of_view.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_item_references) =
            snap.jn_binder_item_from_binder_item_references.clone();
        *write_or_recover(&self.jn_binder_status_from_binder_item_status) =
            snap.jn_binder_status_from_binder_item_status.clone();
        *write_or_recover(&self.jn_binder_tag_from_binder_item_tags) =
            snap.jn_binder_tag_from_binder_item_tags.clone();
        *write_or_recover(&self.jn_binder_item_from_binder_tag_creates_in) =
            snap.jn_binder_item_from_binder_tag_creates_in.clone();
        *write_or_recover(&self.jn_note_template_from_binder_tag_note_template) =
            snap.jn_note_template_from_binder_tag_note_template.clone();
        // counters intentionally NOT restored — IDs must remain monotonically increasing
    }

    /// Create a type-erased store snapshot for undo.
    pub fn store_snapshot(&self) -> StoreSnapshot {
        StoreSnapshot::new(self.snapshot())
    }

    /// Restore from a type-erased store snapshot (preserves counters).
    pub fn restore_store_snapshot(&self, snap: &StoreSnapshot) {
        let s = snap
            .downcast_ref::<HashMapStoreSnapshot>()
            .expect("StoreSnapshot must contain HashMapStoreSnapshot");
        self.restore_without_counters(s);
    }
}

/// Snapshot of the entire store. O(1) to create thanks to im::HashMap structural sharing.
///
/// Entity-table and junction fields are `pub(crate)` so the generated per-entity
/// repositories (same crate) can read the captured rows/junctions during a *scoped*
/// restore. Counters stay private (restore never touches them — ids stay monotonic).
#[derive(Debug, Clone)]
pub struct HashMapStoreSnapshot {
    pub(crate) roots: HashMap<EntityId, Root>,
    pub(crate) systems: HashMap<EntityId, System>,
    pub(crate) work_infos: HashMap<EntityId, WorkInfo>,
    pub(crate) progress_snapshots: HashMap<EntityId, ProgressSnapshot>,
    pub(crate) searchs: HashMap<EntityId, Search>,
    pub(crate) search_results: HashMap<EntityId, SearchResult>,
    pub(crate) recent_works: HashMap<EntityId, RecentWork>,
    pub(crate) works: HashMap<EntityId, Work>,
    pub(crate) smart_punctuations: HashMap<EntityId, SmartPunctuation>,
    pub(crate) trash_infos: HashMap<EntityId, TrashInfo>,
    pub(crate) paces: HashMap<EntityId, Pace>,
    pub(crate) holidays: HashMap<EntityId, Holiday>,
    pub(crate) milestones: HashMap<EntityId, Milestone>,
    pub(crate) comments: HashMap<EntityId, Comment>,
    pub(crate) footnotes: HashMap<EntityId, Footnote>,
    pub(crate) comment_replys: HashMap<EntityId, CommentReply>,
    pub(crate) binders: HashMap<EntityId, Binder>,
    pub(crate) binder_items: HashMap<EntityId, BinderItem>,
    pub(crate) binder_tags: HashMap<EntityId, BinderTag>,
    pub(crate) binder_statuss: HashMap<EntityId, BinderStatus>,
    pub(crate) contents: HashMap<EntityId, Content>,
    pub(crate) dict_words: HashMap<EntityId, DictWord>,
    pub(crate) text_replacement_rules: HashMap<EntityId, TextReplacementRule>,
    pub(crate) note_templates: HashMap<EntityId, NoteTemplate>,
    pub(crate) assets: HashMap<EntityId, Asset>,
    pub(crate) jn_system_from_root_system: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_work_from_root_works: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_recent_work_from_system_recent_works: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_work_info_from_system_work_infos: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_progress_snapshot_from_work_info_progress_snapshots:
        HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_search_from_work_info_search: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_work_from_work_info_work: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_search_result_from_search_results: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_asset_from_work_assets: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_from_work_binders: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_comment_from_work_comments: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_dict_word_from_work_dict_words: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_footnote_from_work_footnotes: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_note_template_from_work_note_templates: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_pace_from_work_paces: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_smart_punctuation_from_work_smart_punctuation: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_status_from_work_statuses: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_tag_from_work_tags: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_text_replacement_rule_from_work_text_replacement_rules:
        HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_trash_info_from_work_trash_infos: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_from_trash_info_trashed_binder: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_trash_info_trashed_binder_item: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_pace_book_item: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_holiday_from_pace_holidays: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_milestone_from_pace_milestones: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_milestone_target_item: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_content_from_comment_content: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_comment_reply_from_comment_replies: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_content_from_footnote_content: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_binder_binder_items: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_binder_item_books: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_content_from_binder_item_contents: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_binder_item_point_of_view: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_binder_item_references: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_status_from_binder_item_status: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_tag_from_binder_item_tags: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_binder_item_from_binder_tag_creates_in: HashMap<EntityId, Vec<EntityId>>,
    pub(crate) jn_note_template_from_binder_tag_note_template: HashMap<EntityId, Vec<EntityId>>,
    counters: std::collections::HashMap<String, EntityId>,
}

impl StoreSnapshotTrait for HashMapStoreSnapshot {
    fn clone_box(&self) -> Box<dyn StoreSnapshotTrait> {
        Box::new(self.clone())
    }

    fn as_any(&self) -> &dyn std::any::Any {
        self
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions
// ─────────────────────────────────────────────────────────────────────────────

/// Acquire a read guard, recovering the inner value if the lock was poisoned by
/// a panic elsewhere — and **clearing** the poison so recovery is permanent, not
/// one-shot (a recovered-but-still-poisoned lock would re-panic on the next plain
/// `.read()/.write().unwrap()`). Used throughout the store's own snapshot /
/// savepoint / restore paths so a single table poisoned by an unrelated panic
/// can't escalate a rollback (the Drop-time `restore_savepoint`) — or the very
/// next write transaction's `create_savepoint` — into a process-wide abort.
pub(crate) fn read_or_recover<T>(lock: &RwLock<T>) -> std::sync::RwLockReadGuard<'_, T> {
    match lock.read() {
        Ok(guard) => guard,
        Err(poisoned) => {
            let guard = poisoned.into_inner();
            lock.clear_poison();
            guard
        }
    }
}

/// Write-guard counterpart of [`read_or_recover`] (also clears the poison).
pub(crate) fn write_or_recover<T>(lock: &RwLock<T>) -> std::sync::RwLockWriteGuard<'_, T> {
    match lock.write() {
        Ok(guard) => guard,
        Err(poisoned) => {
            let guard = poisoned.into_inner();
            lock.clear_poison();
            guard
        }
    }
}

pub(crate) fn delete_from_backward_junction(
    junction: &RwLock<HashMap<EntityId, Vec<EntityId>>>,
    id: &EntityId,
) {
    let mut jn = write_or_recover(junction);
    let keys: Vec<EntityId> = jn.keys().copied().collect();
    for k in keys {
        // A let-chain rather than nested ifs: clippy's `collapsible_if` rejects
        // the nested form under `-D warnings`, and the generated crates are
        // edition 2024, so the chain is available.
        if let Some(right_ids) = jn.get(&k)
            && right_ids.contains(id)
        {
            let filtered: Vec<EntityId> =
                right_ids.iter().copied().filter(|eid| eid != id).collect();
            jn.insert(k, filtered);
        }
    }
}

pub(crate) fn junction_get(
    junction: &RwLock<HashMap<EntityId, Vec<EntityId>>>,
    id: &EntityId,
) -> Vec<EntityId> {
    read_or_recover(junction)
        .get(id)
        .cloned()
        .unwrap_or_default()
}

pub(crate) fn junction_set(
    junction: &RwLock<HashMap<EntityId, Vec<EntityId>>>,
    id: EntityId,
    ids: Vec<EntityId>,
) {
    write_or_recover(junction).insert(id, ids);
}

pub(crate) fn junction_remove(junction: &RwLock<HashMap<EntityId, Vec<EntityId>>>, id: &EntityId) {
    write_or_recover(junction).remove(id);
}

pub(crate) fn junction_get_relationships_from_right_ids(
    junction: &RwLock<HashMap<EntityId, Vec<EntityId>>>,
    right_ids: &[EntityId],
) -> Vec<(EntityId, Vec<EntityId>)> {
    let jn = read_or_recover(junction);
    jn.iter()
        .filter(|(_, rids)| right_ids.iter().any(|eid| rids.contains(eid)))
        .map(|(left_id, rids)| (*left_id, rids.clone()))
        .collect()
}

pub(crate) fn junction_move_ids(
    junction: &RwLock<HashMap<EntityId, Vec<EntityId>>>,
    id: &EntityId,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Vec<EntityId> {
    let current = junction_get(junction, id);
    if ids_to_move.is_empty() {
        return current;
    }
    let move_set: std::collections::HashSet<EntityId> = ids_to_move.iter().copied().collect();
    let mut remaining: Vec<EntityId> = current
        .into_iter()
        .filter(|eid| !move_set.contains(eid))
        .collect();
    let insert_pos = if new_index < 0 || (new_index as usize) > remaining.len() {
        remaining.len()
    } else {
        new_index as usize
    };
    for (i, &eid) in ids_to_move.iter().enumerate() {
        remaining.insert(insert_pos + i, eid);
    }
    junction_set(junction, *id, remaining.clone());
    remaining
}

/// Surgically reconcile an external (out-of-scope) junction list during a scoped undo restore.
///
/// `live_list` is the current ordered value of an external referrer's junction row; `snap_list`
/// is the same row at snapshot time; `scope` is the set of subtree ids being restored. Only the
/// membership/position of `scope` ids is reconciled to match the snapshot — non-scope siblings are
/// preserved in their current relative order. Scope ids absent from the snapshot are removed
/// (undo-of-create); scope ids present in the snapshot are re-inserted at their snapshot-relative
/// position (undo-of-remove). This is what keeps undo from clobbering other trunks' edits.
pub(crate) fn reconcile_backref_list(
    live_list: &[EntityId],
    snap_list: &[EntityId],
    scope: &std::collections::HashSet<EntityId>,
) -> Vec<EntityId> {
    // Scope ids that should be present after restore, in snapshot order.
    let snap_members: Vec<EntityId> = snap_list
        .iter()
        .copied()
        .filter(|x| scope.contains(x))
        .collect();
    let snap_member_set: std::collections::HashSet<EntityId> =
        snap_members.iter().copied().collect();

    // Start from the live list, dropping only scope ids that are NOT in the snapshot.
    let mut work: Vec<EntityId> = live_list
        .iter()
        .copied()
        // De Morgan'd from `!(in_scope && !in_snapshot)`: same rule, stated the
        // way clippy's `nonminimal_bool` wants it, and arguably plainer — keep
        // anything outside the scope, plus anything the snapshot still holds.
        .filter(|x| !scope.contains(x) || snap_member_set.contains(x))
        .collect();

    // Re-insert missing scope ids at their snapshot-relative position (count of snapshot
    // predecessors that survive in `work`), so they return next to their original neighbours.
    for id in &snap_members {
        if work.contains(id) {
            continue;
        }
        let snap_idx = snap_list.iter().position(|x| x == id).unwrap_or(0);
        let pos = snap_list[..snap_idx]
            .iter()
            .filter(|x| work.contains(x))
            .count()
            .min(work.len());
        work.insert(pos, *id);
    }
    work
}

// ═════════════════════════════════════════════════════════════════════════════
// Macros for entities WITH relationships (reduces boilerplate)
// ═════════════════════════════════════════════════════════════════════════════

/// Generate standard relationship methods for a HashMap table implementation.
#[macro_export]
macro_rules! impl_relationship_methods {
    ($table_type:ty, $field_enum:ty) => {
        fn get_relationship(
            &self,
            id: &$crate::types::EntityId,
            field: &$field_enum,
        ) -> Result<Vec<$crate::types::EntityId>, $crate::error::RepositoryError> {
            Ok($crate::database::hashmap_store::junction_get(
                self.resolve_junction(field),
                id,
            ))
        }

        fn get_relationship_many(
            &self,
            ids: &[$crate::types::EntityId],
            field: &$field_enum,
        ) -> Result<
            std::collections::HashMap<$crate::types::EntityId, Vec<$crate::types::EntityId>>,
            $crate::error::RepositoryError,
        > {
            let jn = self.resolve_junction(field);
            let mut map = std::collections::HashMap::new();
            for id in ids {
                map.insert(*id, $crate::database::hashmap_store::junction_get(jn, id));
            }
            Ok(map)
        }

        fn get_relationship_count(
            &self,
            id: &$crate::types::EntityId,
            field: &$field_enum,
        ) -> Result<usize, $crate::error::RepositoryError> {
            Ok(
                $crate::database::hashmap_store::junction_get(self.resolve_junction(field), id)
                    .len(),
            )
        }

        fn get_relationship_in_range(
            &self,
            id: &$crate::types::EntityId,
            field: &$field_enum,
            offset: usize,
            limit: usize,
        ) -> Result<Vec<$crate::types::EntityId>, $crate::error::RepositoryError> {
            let all =
                $crate::database::hashmap_store::junction_get(self.resolve_junction(field), id);
            Ok(all.into_iter().skip(offset).take(limit).collect())
        }

        fn get_relationships_from_right_ids(
            &self,
            field: &$field_enum,
            right_ids: &[$crate::types::EntityId],
        ) -> Result<
            Vec<($crate::types::EntityId, Vec<$crate::types::EntityId>)>,
            $crate::error::RepositoryError,
        > {
            Ok(
                $crate::database::hashmap_store::junction_get_relationships_from_right_ids(
                    self.resolve_junction(field),
                    right_ids,
                ),
            )
        }
    };
}

#[macro_export]
macro_rules! impl_write_relationship_methods {
    ($table_type:ty, $field_enum:ty) => {
        $crate::impl_relationship_methods!($table_type, $field_enum);

        fn set_relationship_multi(
            &mut self,
            field: &$field_enum,
            relationships: Vec<($crate::types::EntityId, Vec<$crate::types::EntityId>)>,
        ) -> Result<(), $crate::error::RepositoryError> {
            let jn = self.resolve_junction(field);
            for (left_id, entities) in relationships {
                $crate::database::hashmap_store::junction_set(jn, left_id, entities);
            }
            Ok(())
        }

        fn set_relationship(
            &mut self,
            id: &$crate::types::EntityId,
            field: &$field_enum,
            right_ids: &[$crate::types::EntityId],
        ) -> Result<(), $crate::error::RepositoryError> {
            $crate::database::hashmap_store::junction_set(
                self.resolve_junction(field),
                *id,
                right_ids.to_vec(),
            );
            Ok(())
        }

        fn move_relationship_ids(
            &mut self,
            id: &$crate::types::EntityId,
            field: &$field_enum,
            ids_to_move: &[$crate::types::EntityId],
            new_index: i32,
        ) -> Result<Vec<$crate::types::EntityId>, $crate::error::RepositoryError> {
            Ok($crate::database::hashmap_store::junction_move_ids(
                self.resolve_junction(field),
                id,
                ids_to_move,
                new_index,
            ))
        }
    };
}

// ═════════════════════════════════════════════════════════════════════════════
// Leaf entity macro (entities without forward relationships)
// ═════════════════════════════════════════════════════════════════════════════

#[macro_export]
macro_rules! impl_leaf_entity_table {
    (
        entity: $Entity:ident,
        entity_name: $entity_name:expr,
        store_field: $store_field:ident,
        table_trait: $TableTrait:ident,
        table_ro_trait: $TableROTrait:ident,
        table_struct: $TableStruct:ident,
        table_ro_struct: $TableROStruct:ident,
        backward_junctions: [ $( ($bj_field:ident) ),* $(,)? ],
    ) => {
        pub struct $TableStruct<'a> {
            store: &'a $crate::database::hashmap_store::HashMapStore,
        }

        impl<'a> $TableStruct<'a> {
            pub fn new(store: &'a $crate::database::hashmap_store::HashMapStore) -> Self {
                Self { store }
            }
        }

        impl<'a> $TableTrait for $TableStruct<'a> {
            fn create(&mut self, entity: &$Entity) -> Result<$Entity, $crate::error::RepositoryError> {
                self.create_multi(std::slice::from_ref(entity))
                    .and_then(|v| {
                        v.into_iter().next().ok_or_else(|| {
                            $crate::error::RepositoryError::Other(::anyhow::anyhow!(
                                "create: the store returned no row for the entity it was given"
                            ))
                        })
                    })
            }

            fn create_multi(&mut self, entities: &[$Entity]) -> Result<Vec<$Entity>, $crate::error::RepositoryError> {
                let mut created = Vec::with_capacity(entities.len());
                let mut map = $crate::database::hashmap_store::write_or_recover(&self.store.$store_field);

                for entity in entities {
                    let new_entity = if entity.id == $crate::types::EntityId::default() {
                        let id = self.store.next_id($entity_name);
                        $Entity {
                            id,
                            ..entity.clone()
                        }
                    } else {
                        if map.contains_key(&entity.id) {
                            return Err($crate::error::RepositoryError::DuplicateId {
                                entity: stringify!($Entity),
                                id: entity.id,
                            });
                        }
                        entity.clone()
                    };

                    map.insert(new_entity.id, new_entity.clone());
                    created.push(new_entity);
                }
                Ok(created)
            }

            fn get(&self, id: &$crate::types::EntityId) -> Result<Option<$Entity>, $crate::error::RepositoryError> {
                Ok($crate::database::hashmap_store::read_or_recover(&self.store.$store_field).get(id).cloned())
            }

            fn get_multi(&self, ids: &[$crate::types::EntityId]) -> Result<Vec<Option<$Entity>>, $crate::error::RepositoryError> {
                let map = $crate::database::hashmap_store::read_or_recover(&self.store.$store_field);
                Ok(ids.iter().map(|id| map.get(id).cloned()).collect())
            }

            fn get_all(&self) -> Result<Vec<$Entity>, $crate::error::RepositoryError> {
                Ok($crate::database::hashmap_store::read_or_recover(&self.store.$store_field).values().cloned().collect())
            }

            fn update(&mut self, entity: &$Entity) -> Result<$Entity, $crate::error::RepositoryError> {
                self.update_multi(std::slice::from_ref(entity))
                    .and_then(|v| {
                        v.into_iter().next().ok_or_else(|| {
                            $crate::error::RepositoryError::Other(::anyhow::anyhow!(
                                "update: the store returned no row for the entity it was given"
                            ))
                        })
                    })
            }

            fn update_multi(&mut self, entities: &[$Entity]) -> Result<Vec<$Entity>, $crate::error::RepositoryError> {
                let mut map = $crate::database::hashmap_store::write_or_recover(&self.store.$store_field);
                let mut result = Vec::with_capacity(entities.len());
                for entity in entities {
                    map.insert(entity.id, entity.clone());
                    result.push(entity.clone());
                }
                Ok(result)
            }

            fn update_with_relationships(&mut self, entity: &$Entity) -> Result<$Entity, $crate::error::RepositoryError> {
                self.update(entity)
            }

            fn update_with_relationships_multi(&mut self, entities: &[$Entity]) -> Result<Vec<$Entity>, $crate::error::RepositoryError> {
                self.update_multi(entities)
            }

            fn remove(&mut self, id: &$crate::types::EntityId) -> Result<(), $crate::error::RepositoryError> {
                self.remove_multi(std::slice::from_ref(id))
            }

            fn remove_multi(&mut self, ids: &[$crate::types::EntityId]) -> Result<(), $crate::error::RepositoryError> {
                let mut map = $crate::database::hashmap_store::write_or_recover(&self.store.$store_field);
                for id in ids {
                    map.remove(id);
                    $(
                        $crate::database::hashmap_store::delete_from_backward_junction(&self.store.$bj_field, id);
                    )*
                }
                Ok(())
            }
        }

        pub struct $TableROStruct<'a> {
            store: &'a $crate::database::hashmap_store::HashMapStore,
        }

        impl<'a> $TableROStruct<'a> {
            pub fn new(store: &'a $crate::database::hashmap_store::HashMapStore) -> Self {
                Self { store }
            }
        }

        impl<'a> $TableROTrait for $TableROStruct<'a> {
            fn get(&self, id: &$crate::types::EntityId) -> Result<Option<$Entity>, $crate::error::RepositoryError> {
                Ok($crate::database::hashmap_store::read_or_recover(&self.store.$store_field).get(id).cloned())
            }

            fn get_multi(&self, ids: &[$crate::types::EntityId]) -> Result<Vec<Option<$Entity>>, $crate::error::RepositoryError> {
                let map = $crate::database::hashmap_store::read_or_recover(&self.store.$store_field);
                Ok(ids.iter().map(|id| map.get(id).cloned()).collect())
            }

            fn get_all(&self) -> Result<Vec<$Entity>, $crate::error::RepositoryError> {
                Ok($crate::database::hashmap_store::read_or_recover(&self.store.$store_field).values().cloned().collect())
            }
        }
    };
}
