// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from feature_use_case.tera
// Custom implementation (hand-maintained): read the open Work subtree and write
// it to its `.skrib` (zip or folder, per WorkInfo / the existing target) through
// the `skrib` serializer. Read-only long operation — it never mutates the store
// (a "Save As" path/shape change is applied by the UI via update_work_info).
use crate::SaveResultDto;
use crate::SaveWorkDto;
use crate::work_io::{self, TreeReader};
use anyhow::Result;
use common::database::QueryUnitOfWork;
use common::direct_access::binder::BinderRelationshipField;
use common::direct_access::binder_item::BinderItemRelationshipField;
use common::direct_access::comment::CommentRelationshipField;
use common::direct_access::pace::PaceRelationshipField;
use common::direct_access::work::WorkRelationshipField;
use common::direct_access::work_info::WorkInfoRelationshipField;
use common::entities::{
    Asset, Binder, BinderItem, BinderTag, Comment, CommentReply, Content, DictWord, Footnote,
    Holiday, Milestone, NoteTemplate, Pace, ProgressSnapshot, SmartPunctuation,
    TextReplacementRule, TrashInfo, Work, WorkInfo,
};
use common::long_operation::{LongOperation, OperationProgress};
use common::types::EntityId;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;

pub trait SaveWorkUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn SaveWorkUnitOfWorkTrait>;
}

// Read-only unit of work. The same macro set must appear on the impl block in
// ../units_of_work/save_work_uow.rs.
#[macros::uow_action(entity = "WorkInfo", action = "GetAllRO")]
#[macros::uow_action(entity = "Work", action = "GetAllRO")]
#[macros::uow_action(entity = "Work", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "TrashInfo", action = "GetAllRO")]
#[macros::uow_action(entity = "Binder", action = "GetMultiRO")]
#[macros::uow_action(entity = "Binder", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "BinderItem", action = "GetMultiRO")]
#[macros::uow_action(entity = "BinderItem", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "BinderTag", action = "GetMultiRO")]
#[macros::uow_action(entity = "Content", action = "GetMultiRO")]
#[macros::uow_action(entity = "DictWord", action = "GetMultiRO")]
#[macros::uow_action(entity = "TextReplacementRule", action = "GetMultiRO")]
#[macros::uow_action(entity = "NoteTemplate", action = "GetMultiRO")]
#[macros::uow_action(entity = "Asset", action = "GetMultiRO")]
#[macros::uow_action(entity = "Footnote", action = "GetMultiRO")]
#[macros::uow_action(entity = "Footnote", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "SmartPunctuation", action = "GetRO")]
#[macros::uow_action(entity = "Pace", action = "GetMultiRO")]
#[macros::uow_action(entity = "Pace", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Holiday", action = "GetMultiRO")]
#[macros::uow_action(entity = "Milestone", action = "GetMultiRO")]
#[macros::uow_action(entity = "Comment", action = "GetMultiRO")]
#[macros::uow_action(entity = "Comment", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "CommentReply", action = "GetMultiRO")]
#[macros::uow_action(entity = "WorkInfo", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "ProgressSnapshot", action = "GetMultiRO")]
pub trait SaveWorkUnitOfWorkTrait: QueryUnitOfWork + Send + Sync {
    fn publish_save_work_event(&self, ids: Vec<EntityId>, data: Option<String>);
}

// Map the generated read methods onto the shared `TreeReader` surface.
impl<'a> TreeReader for dyn SaveWorkUnitOfWorkTrait + 'a {
    fn all_work(&self) -> Result<Vec<Work>> {
        self.get_all_work()
    }
    fn all_work_info(&self) -> Result<Vec<WorkInfo>> {
        self.get_all_work_info()
    }
    fn all_trash_info(&self) -> Result<Vec<TrashInfo>> {
        self.get_all_trash_info()
    }
    fn work_rel(&self, id: &EntityId, field: &WorkRelationshipField) -> Result<Vec<EntityId>> {
        self.get_work_relationship(id, field)
    }
    fn binder_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Binder>>> {
        self.get_binder_multi(ids)
    }
    fn binder_rel(&self, id: &EntityId, field: &BinderRelationshipField) -> Result<Vec<EntityId>> {
        self.get_binder_relationship(id, field)
    }
    fn item_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<BinderItem>>> {
        self.get_binder_item_multi(ids)
    }
    fn item_rel(
        &self,
        id: &EntityId,
        field: &BinderItemRelationshipField,
    ) -> Result<Vec<EntityId>> {
        self.get_binder_item_relationship(id, field)
    }
    fn tag_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<BinderTag>>> {
        self.get_binder_tag_multi(ids)
    }
    fn dict_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<DictWord>>> {
        self.get_dict_word_multi(ids)
    }
    fn text_replacement_rule_multi(
        &self,
        ids: &[EntityId],
    ) -> Result<Vec<Option<TextReplacementRule>>> {
        self.get_text_replacement_rule_multi(ids)
    }
    fn note_template_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<NoteTemplate>>> {
        self.get_note_template_multi(ids)
    }
    fn footnote_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<common::entities::Footnote>>> {
        self.get_footnote_multi(ids)
    }
    fn footnote_rel(
        &self,
        id: &EntityId,
        field: &common::direct_access::footnote::FootnoteRelationshipField,
    ) -> Result<Vec<EntityId>> {
        self.get_footnote_relationship(id, field)
    }
    fn asset_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Asset>>> {
        self.get_asset_multi(ids)
    }
    fn smart_punctuation(&self, id: &EntityId) -> Result<Option<SmartPunctuation>> {
        self.get_smart_punctuation(id)
    }
    fn content_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Content>>> {
        self.get_content_multi(ids)
    }
    fn reads_paces(&self) -> bool {
        true
    }
    fn pace_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Pace>>> {
        self.get_pace_multi(ids)
    }
    fn pace_rel(&self, id: &EntityId, field: &PaceRelationshipField) -> Result<Vec<EntityId>> {
        self.get_pace_relationship(id, field)
    }
    fn holiday_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Holiday>>> {
        self.get_holiday_multi(ids)
    }
    fn milestone_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Milestone>>> {
        self.get_milestone_multi(ids)
    }
    fn reads_comments(&self) -> bool {
        true
    }
    fn comment_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Comment>>> {
        self.get_comment_multi(ids)
    }
    fn comment_rel(
        &self,
        id: &EntityId,
        field: &CommentRelationshipField,
    ) -> Result<Vec<EntityId>> {
        self.get_comment_relationship(id, field)
    }
    fn comment_reply_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<CommentReply>>> {
        self.get_comment_reply_multi(ids)
    }
    fn work_info_rel(
        &self,
        id: &EntityId,
        field: &WorkInfoRelationshipField,
    ) -> Result<Vec<EntityId>> {
        self.get_work_info_relationship(id, field)
    }
    fn progress_snapshot_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<ProgressSnapshot>>> {
        self.get_progress_snapshot_multi(ids)
    }
}

pub struct SaveWorkUseCase {
    uow_factory: Box<dyn SaveWorkUnitOfWorkFactoryTrait>,
    dto: SaveWorkDto,
}

impl SaveWorkUseCase {
    pub fn new(uow_factory: Box<dyn SaveWorkUnitOfWorkFactoryTrait>, dto: &SaveWorkDto) -> Self {
        SaveWorkUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}

impl LongOperation for SaveWorkUseCase {
    type Output = SaveResultDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(OperationProgress) + Send>,
        cancel_flag: Arc<AtomicBool>,
    ) -> Result<Self::Output> {
        progress_callback(OperationProgress::new(0.0, Some("Starting…".to_string())));

        let uow = self.uow_factory.create();
        uow.begin_transaction()?;
        let outcome = run_save(&*uow, &self.dto, &progress_callback, &cancel_flag);
        uow.end_transaction()?;

        let (work_id, result) = outcome?;
        uow.publish_save_work_event(vec![work_id], None);
        progress_callback(OperationProgress::new(100.0, Some("completed".to_string())));
        Ok(result)
    }
}

fn run_save(
    uow: &dyn SaveWorkUnitOfWorkTrait,
    dto: &SaveWorkDto,
    progress: &(dyn Fn(OperationProgress) + Send),
    cancel: &AtomicBool,
) -> Result<(EntityId, SaveResultDto)> {
    let g = work_io::gather(uow, dto.work_id as EntityId, progress, cancel)?;
    let (target, shape, tag) = work_io::resolve_target(&dto.file_name, g.work_info.as_ref(), None)?;
    let work_id = g.work.id;
    // The per-project media directory, resolved from the caller's root: at this
    // point the Work is in hand, so its `unique_id` is known and the fallback
    // key is never needed.
    let media_dir = skrib_format::media::media_dir(
        std::path::Path::new(&target),
        &g.work.unique_id,
        std::path::Path::new(&dto.media_root),
        &g.work.unique_id,
    );
    // A save overwrites the project in place, so the file we are about to replace
    // is also the file whose history we carry forward: read it, append this state,
    // thin, write. This is the *only* write path that records — see `HistoryAction`.
    let history = work_io::HistoryAction::Record {
        source: target.clone(),
        policy: skrib_format::history::DEFAULT_POLICY,
        min_keep: skrib_format::history::DEFAULT_MIN_KEEP,
    };
    let output_path = work_io::serialize_and_write(
        &g,
        target,
        shape,
        tag,
        &media_dir,
        history,
        crate::lifecycle::SaveKind::Save,
    )?;
    Ok((work_id, SaveResultDto { output_path }))
}
