// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from macros_lib.tera

// Panic hygiene — see the same preamble in `direct_access`. It matters more here
// than anywhere else: this crate's `quote!{}` bodies are *emitted into every
// consumer's* unit of work, so one panic path in a template multiplies across the
// whole generated backend. The lint keeps that multiplier at zero.
#![warn(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod direct_access;

use proc_macro::TokenStream;

/// This macro is used to generate a unit of work (UoW) action for a given entity (e.g. Root)
/// and specific action (e.g., create, update). Apply to a trait or an impl block.
/// ex: #[unit_of_work::uow_action(entity = "Root", action = "Create", thread_safe = true)]
#[proc_macro_attribute]
pub fn uow_action(args: TokenStream, input: TokenStream) -> TokenStream {
    direct_access::uow_action_impl(args, input)
}
