// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.7.4 from common_entity_mod.tera

pub mod dict_word_repository;
pub(super) mod dict_word_table;
