// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from common_entity_mod.tera

pub mod work_info_repository;
pub(super) mod work_info_table;
pub use work_info_repository::WorkInfoRelationshipField;
