// Generated by Qleany v1.4.2 from entity_field_list_model_h.tera

#pragma once
#include "binder/binder_controller.h"
#include "binder_item/binder_item_controller.h"
#include "binder_item/dtos.h"
#include "direct_access/event_registry.h"

#include <QAbstractListModel>
#include <QPointer>

namespace Skribisto::DirectAccess::Binder
{

class BinderBinderItemsListModel : public QAbstractListModel
{
    Q_OBJECT
    Q_PROPERTY(int undoRedoStackId READ undoRedoStackId WRITE setUndoRedoStackId NOTIFY undoRedoStackIdChanged)
    Q_PROPERTY(int binderId READ binderId WRITE setBinderId NOTIFY binderIdChanged)

  public:
    enum Roles
    {
        IdRole = Qt::UserRole + 1,
        CreatedAtRole,
        UpdatedAtRole,
        TitleRole,
        SubTitleRole,
        RoleRole,
        SubRoleRole,
        LabelRole,
        ActivatedRole,
        IsFavoriteRole,
        IsPrintableRole,
        IndentRole,
        WordCountGoalRole,
        CharCountGoalRole,
        DictLanguageRole,
        ContentsRole,
        ReferencesRole,
        TagsRole,
    };
    Q_ENUM(Roles)

    explicit BinderBinderItemsListModel(QObject *parent = nullptr, int undoRedoStackId = 0);

    int undoRedoStackId() const;
    void setUndoRedoStackId(int undoRedoStackId);

    // Basic functionality:
    int rowCount(const QModelIndex &parent = QModelIndex()) const override;

    QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const override;

    // Add data:
    bool setData(const QModelIndex &index, const QVariant &value, int role = Qt::EditRole) override;

    Qt::ItemFlags flags(const QModelIndex &index) const override;

    QHash<int, QByteArray> roleNames() const override;

    int binderId() const;
    void setBinderId(int binderId);

  Q_SIGNALS:
    void binderIdChanged();
    void undoRedoStackIdChanged();

  private Q_SLOTS:
    void onBinderItemCreated(const QList<int> &ids);
    void onBinderItemUpdated(const QList<int> &ids);
    void onBinderItemRemoved(const QList<int> &ids);
    void onBinderUpdated(const QList<int> &ids);
    void onBinderRelationshipChanged(int binderId,
                                     Common::DirectAccess::Binder::BinderRelationshipField relationshipField,
                                     const QList<int> &relatedIds);

  private:
    void resolveDependencies();
    void refreshData();
    void reorderToMatch(const QList<int> &orderedIds);

    int m_binderId = -1;
    int m_undoRedoStackId = 0;
    QList<BinderItem::BinderItemDto> m_binderItems;
    bool m_lastRelationshipChangeHandled = false;

    QPointer<Common::DirectAccess::EventRegistry> m_eventRegistry;
    QPointer<BinderItem::BinderItemController> m_binderItemController;
    QPointer<BinderController> m_binderController;
};

} // namespace Skribisto::DirectAccess::Binder