// Generated by Qleany v1.4.2 from entity_controller_h.tera
#pragma once

#include "database/db_context.h"
#include "direct_access/event_registry.h"
#include "dtos.h"
#include "undo_redo/undo_redo_system.h"
#include <QCoro/QCoroTask>

#include <QPointer>

namespace Skribisto::DirectAccess::BinderItem
{
namespace SCDatabase = Skribisto::Common::Database;

class BinderItemController : public QObject
{
    Q_OBJECT
  public:
    BinderItemController(const BinderItemController &) = delete;
    BinderItemController &operator=(const BinderItemController &) = delete;
    BinderItemController(BinderItemController &&) = delete;
    BinderItemController &operator=(BinderItemController &&) = delete;
    explicit BinderItemController(QObject *parent, int undoRedoStackId = 0);

    void setUndoRedoStackId(int undoRedoStackId);
    int undoRedoStackId() const;
    QCoro::Task<QList<BinderItemDto>> create(const QList<CreateBinderItemDto> &binderItems, int ownerId,
                                             int index = -1);
    QCoro::Task<QList<BinderItemDto>> createOrphans(const QList<CreateBinderItemDto> &binderItems);
    static CreateBinderItemDto getCreateDto()
    {
        return {};
    }
    QCoro::Task<QList<BinderItemDto>> get(const QList<int> &binderItemIds) const;
    QCoro::Task<QList<BinderItemDto>> getAll() const;
    QCoro::Task<QList<BinderItemDto>> update(const QList<BinderItemDto> &binderItems);
    QCoro::Task<QList<int>> remove(const QList<int> &binderItemIds);

    QCoro::Task<QList<int>> getRelationshipIds(int binderItemId, BinderItemRelationshipField relationship) const;
    QCoro::Task<void> setRelationshipIds(int binderItemId, BinderItemRelationshipField relationship,
                                         const QList<int> &relatedIds);
    QCoro::Task<QHash<int, QList<int>>> getRelationshipIdsMany(const QList<int> &binderItemIds,
                                                               BinderItemRelationshipField relationship) const;
    QCoro::Task<int> getRelationshipIdsCount(int binderItemId, BinderItemRelationshipField relationship) const;
    QCoro::Task<QList<int>> getRelationshipIdsInRange(int binderItemId, BinderItemRelationshipField relationship,
                                                      int offset, int limit) const;
    QCoro::Task<QList<int>> moveRelationshipIds(int binderItemId, BinderItemRelationshipField relationship,
                                                const QList<int> &idsToMove, int newIndex = -1);

  private:
    void resolveDependencies();
    QPointer<SCDatabase::DbContext> m_dbContext;
    QPointer<Common::DirectAccess::EventRegistry> m_eventRegistry;
    QPointer<Common::UndoRedo::UndoRedoSystem> m_undoRedoSystem;
    int m_undoRedoStackId = 0;
};
} // namespace Skribisto::DirectAccess::BinderItem
