// Generated by Qleany v1.4.2 from dto_mapper_h.tera
#pragma once

#include "binder_item/dtos.h"
#include "direct_access/binder_item/i_binder_item_repository.h"
#include "direct_access/mapper_tools.h"
#include "entities/binder_item.h"

#include <QList>
#include <algorithm>
#include <iterator>

namespace Skribisto::DirectAccess::BinderItem
{
namespace SCE = Skribisto::Common::Entities;
namespace SCDBinderItem = Skribisto::Common::DirectAccess::BinderItem;
namespace CD = Common::DirectAccess;

/// @brief Static-only mapper between BinderItem entities and DTOs.
class DtoMapper final
{
  public:
    DtoMapper() = delete;

    static SCE::BinderItem toEntity(const CreateBinderItemDto &dto)
    {
        return SCE::BinderItem{
            .id = 0,
            .createdAt = dto.createdAt,
            .updatedAt = dto.updatedAt,
            .title = dto.title,
            .subTitle = dto.subTitle,
            .role = dto.role,
            .subRole = dto.subRole,
            .label = dto.label,
            .activated = dto.activated,
            .isFavorite = dto.isFavorite,
            .isPrintable = dto.isPrintable,
            .indent = dto.indent,
            .wordCountGoal = dto.wordCountGoal,
            .charCountGoal = dto.charCountGoal,
            .dictLanguage = dto.dictLanguage,
            .contents = dto.contents,
            .references = dto.references,
            .tags = dto.tags,
        };
    }

    static SCE::BinderItem toEntity(const BinderItemDto &dto)
    {
        return SCE::BinderItem{
            .id = dto.id,
            .createdAt = dto.createdAt,
            .updatedAt = dto.updatedAt,
            .title = dto.title,
            .subTitle = dto.subTitle,
            .role = dto.role,
            .subRole = dto.subRole,
            .label = dto.label,
            .activated = dto.activated,
            .isFavorite = dto.isFavorite,
            .isPrintable = dto.isPrintable,
            .indent = dto.indent,
            .wordCountGoal = dto.wordCountGoal,
            .charCountGoal = dto.charCountGoal,
            .dictLanguage = dto.dictLanguage,
            .contents = dto.contents,
            .references = dto.references,
            .tags = dto.tags,
        };
    }

    static BinderItemDto toDto(const SCE::BinderItem &entity)
    {
        return BinderItemDto{
            .id = entity.id,
            .createdAt = entity.createdAt,
            .updatedAt = entity.updatedAt,
            .title = entity.title,
            .subTitle = entity.subTitle,
            .role = entity.role,
            .subRole = entity.subRole,
            .label = entity.label,
            .activated = entity.activated,
            .isFavorite = entity.isFavorite,
            .isPrintable = entity.isPrintable,
            .indent = entity.indent,
            .wordCountGoal = entity.wordCountGoal,
            .charCountGoal = entity.charCountGoal,
            .dictLanguage = entity.dictLanguage,
            .contents = entity.contents,
            .references = entity.references,
            .tags = entity.tags,
        };
    }

    static QList<SCE::BinderItem> toEntityList(const QList<CreateBinderItemDto> &dtos)
    {
        QList<SCE::BinderItem> entities;
        entities.reserve(dtos.size());
        std::ranges::transform(dtos, std::back_inserter(entities),
                               [](const CreateBinderItemDto &dto) { return toEntity(dto); });
        return entities;
    }

    static QList<SCE::BinderItem> toEntityList(const QList<BinderItemDto> &dtos)
    {
        QList<SCE::BinderItem> entities;
        entities.reserve(dtos.size());
        std::ranges::transform(dtos, std::back_inserter(entities),
                               [](const BinderItemDto &dto) { return toEntity(dto); });
        return entities;
    }

    static QList<BinderItemDto> toDtoList(const QList<SCE::BinderItem> &entities)
    {
        QList<BinderItemDto> dtos;
        dtos.reserve(entities.size());
        std::ranges::transform(entities, std::back_inserter(dtos),
                               [](const SCE::BinderItem &entity) { return toDto(entity); });
        return dtos;
    }

    static SCDBinderItem::BinderItemRelationshipField toCommonRelationshipField(BinderItemRelationshipField field)
    {
        switch (field)
        {

        case BinderItemRelationshipField::Contents:
            return SCDBinderItem::BinderItemRelationshipField::Contents;
        case BinderItemRelationshipField::References:
            return SCDBinderItem::BinderItemRelationshipField::References;
        case BinderItemRelationshipField::Tags:
            return SCDBinderItem::BinderItemRelationshipField::Tags;
        }

        return SCDBinderItem::BinderItemRelationshipField::Contents; // fallback
    }
};
} // namespace Skribisto::DirectAccess::BinderItem
