// Generated by Qleany v1.4.2 from tst_one_to_one_junction_cpp.tera
#include "database/junction_table_ops/junction_cache.h"
#include "database/junction_table_ops/one_to_one.h"
#include "service_locator.h"
#include <QObject>
#include <QSignalSpy>
#include <QSqlDatabase>
#include <QSqlError>
#include <QSqlQuery>
#include <QString>
#include <QTest>
#include <QThread>
#include <memory>
#include <optional>

using namespace Skribisto::Common::Database::JunctionTableOps;

class TestOneToOneJunction : public QObject
{
    Q_OBJECT

  private Q_SLOTS:
    void initTestCase();
    void cleanupTestCase();
    void init();
    void cleanup();

    // getRightId tests
    void testGetRightId();
    void testGetRightIdMany();
    void testGetRightIdEmpty();
    void testGetRightIdNonExistent();

    // removeWithLeftId tests
    void testRemoveWithLeftId();
    void testRemoveWithLeftIdMany();
    void testRemoveWithLeftIdEmpty();
    void testRemoveWithLeftIdNonExistent();

    // upsertRightId tests
    void testUpsertRightId();
    void testUpsertRightIdMany();
    void testUpsertRightIdOptional();
    void testUpsertRightIdEmpty();
    void testUpsertRightIdOverwrite();
    void testUpsertRightIdNullOptional();

    // getLeftId tests
    void testGetLeftId();
    void testGetLeftIdMany();
    void testGetLeftIdEmpty();
    void testGetLeftIdNonExistent();

    // getRightIdCount tests
    void testGetRightIdCount();
    void testGetRightIdCountZero();
    void testGetRightIdCountNonExistent();

    // getRightIdInRange tests
    void testGetRightIdInRange();
    void testGetRightIdInRangeEmpty();

    // one-to-one constraint tests
    void testOneToOneConstraintEnforcement();
    void testCacheInvalidation();

  private:
    QSqlDatabase m_db;
    QString m_junctionTableDefinition = QStringLiteral("CREATE TABLE IF NOT EXISTS test_junction ("
                                                       "left_id INTEGER NOT NULL, "
                                                       "right_id INTEGER NOT NULL, "
                                                       "UNIQUE(left_id), "
                                                       "UNIQUE(right_id)"
                                                       ")");
    QString m_junctionTableName = QStringLiteral("test_junction");

    void setupDatabase();
    void insertTestData(const QList<QPair<int, int>> &data);
    void clearJunctionTable();
};

void TestOneToOneJunction::initTestCase()
{
    std::string duration("20000"); // 20 secondes
    QByteArray timeoutDuration(duration.c_str(), static_cast<int>(duration.length()));
    qputenv("QTEST_FUNCTION_TIMEOUT", timeoutDuration);
}

void TestOneToOneJunction::cleanupTestCase()
{
}

void TestOneToOneJunction::init()
{
    setupDatabase();
}

void TestOneToOneJunction::cleanup()
{
    if (m_db.isOpen())
    {
        QString connectionName = m_db.connectionName();
        clearJunctionTable();
        {
            QSqlDatabase db = m_db;
            m_db = QSqlDatabase(); // Reset member to avoid dangling reference

            // Clear junction cache
            Skribisto::Common::Database::JunctionTableOps::JunctionCache::instance().clear();

            // Close and remove the database connection
            db.close();
        }
        QSqlDatabase::removeDatabase(connectionName);
    }
}

void TestOneToOneJunction::setupDatabase()
{
    // Create unique in-memory database for each test
    static int counter = 0;
    QString connectionName = QStringLiteral("test_connection_%1").arg(++counter);

    m_db = QSqlDatabase::addDatabase(QStringLiteral("QSQLITE"), connectionName);
    m_db.setDatabaseName(QStringLiteral(":memory:"));

    QVERIFY(m_db.open());

    // Create junction table
    QSqlQuery query(m_db);
    QVERIFY(query.exec(m_junctionTableDefinition));
}

void TestOneToOneJunction::insertTestData(const QList<QPair<int, int>> &data)
{
    QSqlQuery query(m_db);
    query.prepare(QStringLiteral("INSERT INTO %1 (left_id, right_id) VALUES (?, ?)").arg(m_junctionTableName));

    for (const auto &pair : data)
    {
        query.addBindValue(pair.first);
        query.addBindValue(pair.second);
        QVERIFY2(query.exec(), query.lastError().text().toUtf8().data());
    }
}

void TestOneToOneJunction::clearJunctionTable()
{
    QSqlQuery query(m_db);
    QVERIFY(query.exec(QStringLiteral("DELETE FROM %1").arg(m_junctionTableName)));
}

void TestOneToOneJunction::testGetRightId()
{
    insertTestData({{1, 101}, {2, 102}});

    auto result = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(result.has_value());
    QCOMPARE(result.value(), 101);
}

void TestOneToOneJunction::testGetRightIdMany()
{
    insertTestData({{1, 101}, {2, 102}, {3, 103}});

    QList<int> leftIds = {1, 2, 4}; // 4 doesn't exist
    auto result = OneToOne::getRightIdMany(m_db, leftIds, m_junctionTableName);

    QCOMPARE(result.size(), 3);
    QVERIFY(result[1].has_value());
    QCOMPARE(result[1].value(), 101);
    QVERIFY(result[2].has_value());
    QCOMPARE(result[2].value(), 102);
    QVERIFY(!result[4].has_value()); // Should be nullopt
}

void TestOneToOneJunction::testGetRightIdEmpty()
{
    auto result = OneToOne::getRightIdMany(m_db, {}, m_junctionTableName);
    QVERIFY(result.isEmpty());
}

void TestOneToOneJunction::testGetRightIdNonExistent()
{
    insertTestData({{1, 101}});

    auto result = OneToOne::getRightId(m_db, 999, m_junctionTableName);
    QVERIFY(!result.has_value());
}

void TestOneToOneJunction::testRemoveWithLeftId()
{
    insertTestData({{1, 101}, {2, 102}});

    bool success = OneToOne::removeWithLeftId(m_db, 1, m_junctionTableName);
    QVERIFY(success);

    // Verify removal
    auto result = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(!result.has_value());

    // Verify other record still exists
    result = OneToOne::getRightId(m_db, 2, m_junctionTableName);
    QVERIFY(result.has_value());
    QCOMPARE(result.value(), 102);
}

void TestOneToOneJunction::testRemoveWithLeftIdMany()
{
    insertTestData({{1, 101}, {2, 102}, {3, 103}});

    QList<int> leftIds = {1, 3};
    auto results = OneToOne::removeWithLeftIdMany(m_db, leftIds, m_junctionTableName);

    QCOMPARE(results.size(), 2);
    QVERIFY(results[1]);
    QVERIFY(results[3]);

    // Verify removals
    auto remaining = OneToOne::getRightIdMany(m_db, {1, 2, 3}, m_junctionTableName);
    QVERIFY(!remaining[1].has_value());
    QVERIFY(remaining[2].has_value());
    QCOMPARE(remaining[2].value(), 102);
    QVERIFY(!remaining[3].has_value());
}

void TestOneToOneJunction::testRemoveWithLeftIdEmpty()
{
    auto result = OneToOne::removeWithLeftIdMany(m_db, {}, m_junctionTableName);
    QVERIFY(result.isEmpty());
}

void TestOneToOneJunction::testRemoveWithLeftIdNonExistent()
{
    bool success = OneToOne::removeWithLeftId(m_db, 999, m_junctionTableName);
    QVERIFY(success); // Should succeed even if nothing to remove
}

void TestOneToOneJunction::testUpsertRightId()
{
    // Test insert
    auto result = OneToOne::upsertRightId(m_db, 1, m_junctionTableName, 101);
    QCOMPARE(result.size(), 1);
    QCOMPARE(result[0], 101);

    // Verify insert
    auto retrieved = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(retrieved.has_value());
    QCOMPARE(retrieved.value(), 101);
}

void TestOneToOneJunction::testUpsertRightIdMany()
{
    QHash<int, int> data;
    data[1] = 101;
    data[2] = 102;

    auto results = OneToOne::upsertRightIdMany(m_db, data, m_junctionTableName);

    QCOMPARE(results.size(), 2);
    QCOMPARE(results[1].size(), 1);
    QCOMPARE(results[1][0], 101);
    QCOMPARE(results[2].size(), 1);
    QCOMPARE(results[2][0], 102);

    // Verify inserts
    auto retrieved = OneToOne::getRightIdMany(m_db, {1, 2}, m_junctionTableName);
    QVERIFY(retrieved[1].has_value());
    QCOMPARE(retrieved[1].value(), 101);
    QVERIFY(retrieved[2].has_value());
    QCOMPARE(retrieved[2].value(), 102);
}

void TestOneToOneJunction::testUpsertRightIdOptional()
{
    // Test with valid optional
    std::optional<int> rightId = 101;
    auto result = OneToOne::upsertRightId(m_db, 1, m_junctionTableName, rightId);
    QCOMPARE(result.size(), 1);
    QCOMPARE(result[0], 101);

    // Verify
    auto retrieved = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(retrieved.has_value());
    QCOMPARE(retrieved.value(), 101);
}

void TestOneToOneJunction::testUpsertRightIdEmpty()
{
    QHash<int, int> data;
    auto results = OneToOne::upsertRightIdMany(m_db, data, m_junctionTableName);
    QVERIFY(results.isEmpty());
}

void TestOneToOneJunction::testUpsertRightIdOverwrite()
{
    insertTestData({{1, 101}});

    // Update existing record
    auto result = OneToOne::upsertRightId(m_db, 1, m_junctionTableName, 201);
    QCOMPARE(result.size(), 1);
    QCOMPARE(result[0], 201);

    // Verify update
    auto retrieved = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(retrieved.has_value());
    QCOMPARE(retrieved.value(), 201);
}

void TestOneToOneJunction::testUpsertRightIdNullOptional()
{
    insertTestData({{1, 101}});

    // Test with nullopt - should remove
    QHash<int, std::optional<int>> data;
    data[1] = std::nullopt;

    auto results = OneToOne::upsertRightIdMany(m_db, data, m_junctionTableName);
    QCOMPARE(results.size(), 1);
    QVERIFY(results[1].isEmpty());

    // Verify removal
    auto retrieved = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(!retrieved.has_value());
}

void TestOneToOneJunction::testGetLeftId()
{
    insertTestData({{1, 101}, {2, 102}});

    int result = OneToOne::getLeftId(m_db, m_junctionTableName, 101);
    QCOMPARE(result, 1);
}

void TestOneToOneJunction::testGetLeftIdMany()
{
    insertTestData({{1, 101}, {2, 102}, {3, 103}});

    QList<int> rightIds = {101, 102, 404}; // 404 doesn't exist
    auto result = OneToOne::getLeftIdMany(m_db, m_junctionTableName, rightIds);

    QCOMPARE(result.size(), 2); // Only found records
    QVERIFY(result.contains(101));
    QCOMPARE(result[101], 1);
    QVERIFY(result.contains(102));
    QCOMPARE(result[102], 2);
    QVERIFY(!result.contains(404));
}

void TestOneToOneJunction::testGetLeftIdEmpty()
{
    auto result = OneToOne::getLeftIdMany(m_db, m_junctionTableName, {});
    QVERIFY(result.isEmpty());
}

void TestOneToOneJunction::testGetLeftIdNonExistent()
{
    insertTestData({{1, 101}});

    int result = OneToOne::getLeftId(m_db, m_junctionTableName, 999);
    QCOMPARE(result, -1);
}

void TestOneToOneJunction::testGetRightIdCount()
{
    insertTestData({{1, 101}});

    int count = OneToOne::getRightIdCount(m_db, 1, m_junctionTableName);
    QCOMPARE(count, 1);
}

void TestOneToOneJunction::testGetRightIdCountZero()
{
    int count = OneToOne::getRightIdCount(m_db, 1, m_junctionTableName);
    QCOMPARE(count, 0);
}

void TestOneToOneJunction::testGetRightIdCountNonExistent()
{
    insertTestData({{1, 101}});

    int count = OneToOne::getRightIdCount(m_db, 999, m_junctionTableName);
    QCOMPARE(count, 0);
}

void TestOneToOneJunction::testGetRightIdInRange()
{
    insertTestData({{1, 101}});

    auto result = OneToOne::getRightIdInRange(m_db, 1, m_junctionTableName, 0, 1);
    QCOMPARE(result.size(), 1);
    QCOMPARE(result[0], 101);
}

void TestOneToOneJunction::testGetRightIdInRangeEmpty()
{
    auto result = OneToOne::getRightIdInRange(m_db, 1, m_junctionTableName, 0, 1);
    QVERIFY(result.isEmpty());
}

void TestOneToOneJunction::testOneToOneConstraintEnforcement()
{
    insertTestData({{1, 101}});

    // Test that updating to a different right_id works
    auto result = OneToOne::upsertRightId(m_db, 1, m_junctionTableName, 201);
    QCOMPARE(result.size(), 1);
    QCOMPARE(result[0], 201);

    // Verify only one right_id per left_id
    int count = OneToOne::getRightIdCount(m_db, 1, m_junctionTableName);
    QCOMPARE(count, 1);

    auto retrieved = OneToOne::getRightId(m_db, 1, m_junctionTableName);
    QVERIFY(retrieved.has_value());
    QCOMPARE(retrieved.value(), 201);
}

void TestOneToOneJunction::testCacheInvalidation()
{
    insertTestData({{1, 101}});

    // Get count to populate cache
    int initialCount = OneToOne::getRightIdCount(m_db, 1, m_junctionTableName);
    QCOMPARE(initialCount, 1);

    // Remove the record - this should invalidate cache
    bool success = OneToOne::removeWithLeftId(m_db, 1, m_junctionTableName);
    QVERIFY(success);

    // Count should now be 0 (cache should be invalidated)
    int newCount = OneToOne::getRightIdCount(m_db, 1, m_junctionTableName);
    QCOMPARE(newCount, 0);

    // Add back and test upsert cache invalidation
    OneToOne::upsertRightId(m_db, 1, m_junctionTableName, 102);
    int finalCount = OneToOne::getRightIdCount(m_db, 1, m_junctionTableName);
    QCOMPARE(finalCount, 1);
}

QTEST_MAIN(TestOneToOneJunction)

#include "tst_one_to_one_junction.moc"