// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

//! A `<text:p>` whose paragraph style declares an outline level is a heading.
//!
//! ODF has two ways to say "this is a heading at depth N". `<text:h text:outline-level="N">` is
//! the obvious one, and for a long time it was the only one this scanner read. The other is
//! `style:default-outline-level` on a **paragraph style** — and it is not exotic: it is what
//! every document written from a novel template uses. Chapters are `<text:p>` in a "Chapter
//! title" style, and the file contains no `<text:h>` at all.
//!
//! Read only the first way, a 90 000-word manuscript with twenty-seven chapters imports as a
//! single scene, because not one of its headings is recognised. That is a real report against a
//! real manuscript, and these fixtures are its shape reduced to the parts that matter.
//!
//! Written as flat ODF (`.fodt`) so each fixture is a readable string literal rather than a
//! binary blob regenerated by a script — the styles under test are the point, and here they are
//! visible.

use document_ingest::block::SourceBlock;
use document_ingest::scanner::ScannerRegistry;

fn scan(fodt: &str) -> document_ingest::block::SourceDocument {
    ScannerRegistry::with_builtin_scanners()
        .scan_bytes(std::path::Path::new("novel.fodt"), fodt.as_bytes())
}

fn headings(doc: &document_ingest::block::SourceDocument) -> Vec<(u8, String)> {
    doc.blocks
        .iter()
        .filter_map(|b| match b {
            SourceBlock::Heading { level, text } => Some((*level, text.clone())),
            _ => None,
        })
        .collect()
}

/// The shape a novel template produces: named styles carrying the level, **automatic** styles
/// applied to the paragraphs, and not a single `<text:h>`.
const NOVEL_TEMPLATE: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<office:document
  xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0"
  xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
  office:mimetype="application/vnd.oasis.opendocument.text">
  <office:styles>
    <style:style style:name="Chapter_20_title" style:display-name="Chapter title"
                 style:family="paragraph" style:default-outline-level="2"/>
    <style:style style:name="Scene_20_title" style:display-name="Scene title"
                 style:family="paragraph" style:default-outline-level="3"/>
    <style:style style:name="Novel_20_body" style:display-name="Novel body"
                 style:family="paragraph"/>
  </office:styles>
  <office:automatic-styles>
    <style:style style:name="P12" style:family="paragraph"
                 style:parent-style-name="Chapter_20_title"/>
    <style:style style:name="P7" style:family="paragraph"
                 style:parent-style-name="Novel_20_body"/>
  </office:automatic-styles>
  <office:body>
    <office:text>
      <text:p text:style-name="P12">Chapitre 1 : Douces vacances</text:p>
      <text:p text:style-name="P7">The wind rose over the hills.</text:p>
      <text:p text:style-name="Scene_20_title">Scene 1</text:p>
      <text:p text:style-name="Novel_20_body">She counted the lamps again.</text:p>
      <text:p text:style-name="P12">Chapitre 2 : Un long voyage</text:p>
      <text:p text:style-name="P7">The harbour was quiet.</text:p>
    </office:text>
  </office:body>
</office:document>"#;

#[test]
fn a_paragraph_style_declaring_an_outline_level_is_a_heading() {
    let doc = scan(NOVEL_TEMPLATE);
    assert_eq!(
        headings(&doc),
        vec![
            (2, "Chapitre 1 : Douces vacances".to_string()),
            (3, "Scene 1".to_string()),
            (2, "Chapitre 2 : Un long voyage".to_string()),
        ],
        "every styled chapter and scene title must be a heading at the depth its style \
         declares — not body prose. blocks = {:#?}",
        doc.blocks
    );
}

/// The level must be reachable through an **automatic** style's parent, which is how a real
/// document applies it: the paragraph names `P12`, and only `P12`'s parent carries the level.
#[test]
fn the_level_is_found_through_an_automatic_styles_parent() {
    let doc = scan(NOVEL_TEMPLATE);
    let h = headings(&doc);
    assert!(
        h.iter().filter(|(l, _)| *l == 2).count() == 2,
        "both `P12` paragraphs inherit level 2 from `Chapter title`: {h:?}"
    );
}

/// Body prose must not be promoted. A style with no declared level, and no ancestor carrying
/// one, is ordinary text however it is named.
#[test]
fn an_undeclared_style_stays_body_prose() {
    let doc = scan(NOVEL_TEMPLATE);
    let prose: Vec<&str> = doc
        .blocks
        .iter()
        .filter_map(|b| match b {
            SourceBlock::Prose { text, .. } => Some(text.as_str()),
            _ => None,
        })
        .collect();
    assert!(
        prose.iter().any(|t| t.contains("The wind rose")),
        "novel body must stay prose: {prose:?}"
    );
    assert!(
        !headings(&doc).iter().any(|(_, t)| t.contains("wind rose")),
        "…and must not become a heading"
    );
}

/// An empty paragraph left in a heading style is spacing, not a titleless chapter.
#[test]
fn an_empty_styled_paragraph_is_not_a_heading() {
    let fodt = NOVEL_TEMPLATE.replace(
        r#"<text:p text:style-name="P12">Chapitre 2 : Un long voyage</text:p>"#,
        r#"<text:p text:style-name="P12"/><text:p text:style-name="P12">   </text:p>"#,
    );
    let doc = scan(&fodt);
    assert_eq!(
        headings(&doc).len(),
        2,
        "the two blank chapter-styled paragraphs must not open chapters: {:?}",
        headings(&doc)
    );
}

/// `<text:h>` still works, and still wins on its own terms — the new path is an addition, not
/// a replacement.
#[test]
fn an_explicit_text_h_is_unaffected() {
    let fodt = NOVEL_TEMPLATE.replace(
        r#"<text:p text:style-name="P12">Chapitre 1 : Douces vacances</text:p>"#,
        r#"<text:h text:outline-level="1">Le Vent se lève</text:h>"#,
    );
    let doc = scan(&fodt);
    assert!(
        headings(&doc).contains(&(1, "Le Vent se lève".to_string())),
        "{:?}",
        headings(&doc)
    );
}
