// Generated by Qleany v1.4.2 from entity_events_h.tera
#pragma once

#include "direct_access/content/i_content_repository.h"
#include "entities/content.h"
#include <QList>
#include <QMetaObject>
#include <QObject>

// Ensure metatypes are declared for queued connections
Q_DECLARE_METATYPE(Skribisto::Common::Entities::Content)

namespace Skribisto::Common::DirectAccess::Content
{

class ContentEvents : public QObject
{
    Q_OBJECT
  public:
    explicit ContentEvents(QObject *parent = nullptr) : QObject(parent)
    {
        // Register metatypes for cross-thread signal delivery
        qRegisterMetaType<Entities::Content>("Content");
        qRegisterMetaType<QList<Entities::Content>>("QList<Content>");
        qRegisterMetaType<QList<int>>("QList<int>");
        qRegisterMetaType<ContentRelationshipField>("ContentRelationshipField");
    }

  public Q_SLOTS:
    // These methods can be invoked from any thread; they will emit signals in this object's thread
    void publishCreated(const QList<int> &ids)
    {
        Q_EMIT created(ids);
    }
    void publishUpdated(const QList<int> &ids)
    {
        Q_EMIT updated(ids);
    }
    void publishRemoved(const QList<int> &ids)
    {
        Q_EMIT removed(ids);
    }

  Q_SIGNALS:
    void created(const QList<int> &ids);
    void updated(const QList<int> &ids);
    void removed(const QList<int> &ids);
};

} // namespace Skribisto::Common::DirectAccess::Content
