// Generated by Qleany v1.4.2 from entity_table_h.tera
#pragma once

#include "database/db_context.h"
#include "database/snapshot_types.h"
#include "direct_access/content/content_repository.h"
#include "entities/content.h"

#include <QList>

namespace Skribisto::Common::DirectAccess::Content
{
namespace SCE = Skribisto::Common::Entities;

class ContentTable final : public IContentTable
{
  public:
    explicit ContentTable(Database::DbSubContext &dbSubContext);

    QList<SCE::Content> createMany(const QList<SCE::Content> &contents) override;
    QList<SCE::Content> updateMany(const QList<SCE::Content> &contents) override;
    [[nodiscard]] QList<SCE::Content> findMany(const QList<int> &ids) const override;
    [[nodiscard]] QList<SCE::Content> findAll() const override;
    QList<int> removeMany(const QList<int> &ids) override;
    void setRelationshipIds(int contentId, ContentRelationshipField relationship, QList<int> relatedId) override;
    [[nodiscard]] QHash<int, QList<int>> getRelationshipIdsMany(const QList<int> &contentIds,
                                                                ContentRelationshipField relationship) const override;
    int getRelationshipIdsCount(int rootId, ContentRelationshipField relationship) const override;
    QList<int> getRelationshipIdsInRange(int rootId, ContentRelationshipField relationship, int offset,
                                         int limit) const override;
    QList<int> moveRelationshipIds(int contentId, ContentRelationshipField relationship, const QList<int> &idsToMove,
                                   int newIndex) override;

    // Snapshot / Restore (table level)
    Database::TableLevelSnapshot snapshotRows(const QList<int> &ids) override;
    void restoreRows(const Database::TableLevelSnapshot &snap) override;
    [[nodiscard]] QList<int> getOwnerIds(const QList<int> &childIds) const override;

  private:
    Database::DbSubContext &m_dbSubContext;
};

} // namespace Skribisto::Common::DirectAccess::Content
