// Generated by Qleany v1.4.2 from feature_dtos_h.tera

#pragma once

#include <QObject>
#include <QString>
#include <qobjectdefs.h>

namespace Skribisto::WorkManagement
{
Q_NAMESPACE
struct LoadWorkDto
{
    Q_GADGET
    Q_PROPERTY(QString fileName MEMBER fileName)

  public:
    int id = 0;
    QString fileName{};
};
struct SaveWorkDto
{
    Q_GADGET
    Q_PROPERTY(QString fileName MEMBER fileName)
    Q_PROPERTY(bool overwrite MEMBER overwrite)

  public:
    int id = 0;
    QString fileName{};
    bool overwrite = false;
};

} // namespace Skribisto::WorkManagement
Q_DECLARE_METATYPE(Skribisto::WorkManagement::LoadWorkDto)
Q_DECLARE_METATYPE(Skribisto::WorkManagement::SaveWorkDto)
