// Generated by Qleany v1.6.1 from dto_mapper_h.tera
#pragma once

#include "direct_access/mapper_tools.h"
#include "direct_access/root/i_root_repository.h"
#include "entities/root.h"
#include "root/dtos.h"

#include <QList>
#include <algorithm>
#include <iterator>

namespace Skribisto::DirectAccess::Root
{
namespace SCE = Skribisto::Common::Entities;
namespace SCDRoot = Skribisto::Common::DirectAccess::Root;
namespace CD = Common::DirectAccess;

/// @brief Static-only mapper between Root entities and DTOs.
class DtoMapper final
{
  public:
    DtoMapper() = delete;

    static SCE::Root toEntity(const CreateRootDto &dto)
    {
        return SCE::Root{
            .id = 0,
            .createdAt = dto.createdAt,
            .updatedAt = dto.updatedAt,
            .system = dto.system,
            .works = dto.works,
        };
    }

    static SCE::Root toEntity(const RootDto &dto)
    {
        return SCE::Root{
            .id = dto.id,
            .createdAt = dto.createdAt,
            .updatedAt = dto.updatedAt,
            .system = dto.system,
            .works = dto.works,
        };
    }

    static RootDto toDto(const SCE::Root &entity)
    {
        return RootDto{
            .id = entity.id,
            .createdAt = entity.createdAt,
            .updatedAt = entity.updatedAt,
            .system = entity.system,
            .works = entity.works,
        };
    }

    static SCE::Root toEntity(const UpdateRootDto &dto)
    {
        return SCE::Root{
            .id = dto.id,
            .createdAt = dto.createdAt,
            .updatedAt = dto.updatedAt,
        };
    }

    static QList<SCE::Root> toEntityList(const QList<UpdateRootDto> &dtos)
    {
        QList<SCE::Root> entities;
        entities.reserve(dtos.size());
        std::ranges::transform(dtos, std::back_inserter(entities),
                               [](const UpdateRootDto &dto) { return toEntity(dto); });
        return entities;
    }

    static QList<SCE::Root> toEntityList(const QList<CreateRootDto> &dtos)
    {
        QList<SCE::Root> entities;
        entities.reserve(dtos.size());
        std::ranges::transform(dtos, std::back_inserter(entities),
                               [](const CreateRootDto &dto) { return toEntity(dto); });
        return entities;
    }

    static QList<SCE::Root> toEntityList(const QList<RootDto> &dtos)
    {
        QList<SCE::Root> entities;
        entities.reserve(dtos.size());
        std::ranges::transform(dtos, std::back_inserter(entities), [](const RootDto &dto) { return toEntity(dto); });
        return entities;
    }

    static QList<RootDto> toDtoList(const QList<SCE::Root> &entities)
    {
        QList<RootDto> dtos;
        dtos.reserve(entities.size());
        std::ranges::transform(entities, std::back_inserter(dtos),
                               [](const SCE::Root &entity) { return toDto(entity); });
        return dtos;
    }

    static SCDRoot::RootRelationshipField toCommonRelationshipField(RootRelationshipField field)
    {
        switch (field)
        {

        case RootRelationshipField::System:
            return SCDRoot::RootRelationshipField::System;
        case RootRelationshipField::Works:
            return SCDRoot::RootRelationshipField::Works;
        }

        return SCDRoot::RootRelationshipField::System; // fallback
    }
};
} // namespace Skribisto::DirectAccess::Root
