// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from common_entity_table.tera

// ═══════════════════════════════════════════════════════════════════════
// Entity WITH forward relationships — explicit struct implementation
// ═══════════════════════════════════════════════════════════════════════
use crate::database::hashmap_store::{
    HashMapStore, delete_from_backward_junction, junction_get, junction_remove, junction_set,
    read_or_recover, write_or_recover,
};
use crate::entities::Binder;
use crate::error::RepositoryError;
use crate::types::EntityId;
use crate::{impl_relationship_methods, impl_write_relationship_methods};
use im::HashMap;
use std::sync::RwLock;

use super::binder_repository::BinderRelationshipField;
use super::binder_repository::BinderTable;
use super::binder_repository::BinderTableRO;

pub struct BinderHashMapTable<'a> {
    store: &'a HashMapStore,
}

impl<'a> BinderHashMapTable<'a> {
    pub fn new(store: &'a HashMapStore) -> Self {
        Self { store }
    }

    fn resolve_junction(
        &self,
        field: &BinderRelationshipField,
    ) -> &RwLock<HashMap<EntityId, Vec<EntityId>>> {
        match field {
            BinderRelationshipField::BinderItems => {
                &self.store.jn_binder_item_from_binder_binder_items
            }
        }
    }

    fn hydrate(&self, entity: &mut Binder) {
        entity.binder_items = junction_get(
            &self.store.jn_binder_item_from_binder_binder_items,
            &entity.id,
        );
    }
}

impl<'a> BinderTable for BinderHashMapTable<'a> {
    fn create(&mut self, entity: &Binder) -> Result<Binder, RepositoryError> {
        self.create_multi(std::slice::from_ref(entity))
            .and_then(|v| {
                // `create_multi` is contracted to return one row per input, so this
                // is unreachable — but it used to be `.unwrap()`, and a store that
                // ever broke that contract would take the whole process down rather
                // than fail the one call that noticed.
                v.into_iter().next().ok_or_else(|| {
                    RepositoryError::Other(anyhow::anyhow!(
                        "create: the store returned no row for the entity it was given"
                    ))
                })
            })
    }

    fn create_multi(&mut self, entities: &[Binder]) -> Result<Vec<Binder>, RepositoryError> {
        let mut created = Vec::with_capacity(entities.len());
        let mut binder_map = write_or_recover(&self.store.binders);

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                let id = self.store.next_id("binder");
                Binder {
                    id,
                    ..entity.clone()
                }
            } else {
                if binder_map.contains_key(&entity.id) {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Binder",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            binder_map.insert(new_entity.id, new_entity.clone());

            junction_set(
                &self.store.jn_binder_item_from_binder_binder_items,
                new_entity.id,
                new_entity.binder_items.clone(),
            );

            created.push(new_entity);
        }
        Ok(created)
    }

    fn get(&self, id: &EntityId) -> Result<Option<Binder>, RepositoryError> {
        let binder_map = read_or_recover(&self.store.binders);
        match binder_map.get(id) {
            Some(entity) => {
                let mut e = entity.clone();
                drop(binder_map);
                self.hydrate(&mut e);
                Ok(Some(e))
            }
            None => Ok(None),
        }
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Binder>>, RepositoryError> {
        let mut result = Vec::with_capacity(ids.len());
        for id in ids {
            result.push(self.get(id)?);
        }
        Ok(result)
    }

    fn get_all(&self) -> Result<Vec<Binder>, RepositoryError> {
        let binder_map = read_or_recover(&self.store.binders);
        let entries: Vec<Binder> = binder_map.values().cloned().collect();
        drop(binder_map);
        let mut result = Vec::with_capacity(entries.len());
        for mut entity in entries {
            self.hydrate(&mut entity);
            result.push(entity);
        }
        Ok(result)
    }

    fn update(&mut self, entity: &Binder) -> Result<Binder, RepositoryError> {
        self.update_multi(std::slice::from_ref(entity))
            .and_then(|v| {
                // `update_multi` is contracted to return one row per input, so this
                // is unreachable — but it used to be `.unwrap()`, and a store that
                // ever broke that contract would take the whole process down rather
                // than fail the one call that noticed.
                v.into_iter().next().ok_or_else(|| {
                    RepositoryError::Other(anyhow::anyhow!(
                        "update: the store returned no row for the entity it was given"
                    ))
                })
            })
    }

    // Scalar-only update: writes entity data but does NOT touch junction tables.
    fn update_multi(&mut self, entities: &[Binder]) -> Result<Vec<Binder>, RepositoryError> {
        let mut binder_map = write_or_recover(&self.store.binders);
        for entity in entities {
            binder_map.insert(entity.id, entity.clone());
        }
        drop(binder_map);
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships(&mut self, entity: &Binder) -> Result<Binder, RepositoryError> {
        self.update_with_relationships_multi(std::slice::from_ref(entity))
            .and_then(|v| {
                // `update_with_relationships_multi` is contracted to return one row per input, so this
                // is unreachable — but it used to be `.unwrap()`, and a store that
                // ever broke that contract would take the whole process down rather
                // than fail the one call that noticed.
                v.into_iter().next().ok_or_else(|| {
                    RepositoryError::Other(anyhow::anyhow!(
                        "update_with_relationships: the store returned no row for the entity it was given"
                    ))
                })
            })
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Binder],
    ) -> Result<Vec<Binder>, RepositoryError> {
        let mut binder_map = write_or_recover(&self.store.binders);
        for entity in entities {
            binder_map.insert(entity.id, entity.clone());

            junction_set(
                &self.store.jn_binder_item_from_binder_binder_items,
                entity.id,
                entity.binder_items.clone(),
            );
        }
        drop(binder_map);
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut binder_map = write_or_recover(&self.store.binders);
        for id in ids {
            binder_map.remove(id);

            // Remove forward junction entries

            junction_remove(&self.store.jn_binder_item_from_binder_binder_items, id);

            // Clean up backward references (uses the owning entity's forward junction)

            delete_from_backward_junction(&self.store.jn_binder_from_work_binders, id);
            delete_from_backward_junction(&self.store.jn_binder_from_trash_info_trashed_binder, id);
        }
        Ok(())
    }

    impl_write_relationship_methods!(BinderHashMapTable<'a>, BinderRelationshipField);
}

pub struct BinderHashMapTableRO<'a> {
    store: &'a HashMapStore,
}

impl<'a> BinderHashMapTableRO<'a> {
    pub fn new(store: &'a HashMapStore) -> Self {
        Self { store }
    }

    fn resolve_junction(
        &self,
        field: &BinderRelationshipField,
    ) -> &RwLock<HashMap<EntityId, Vec<EntityId>>> {
        match field {
            BinderRelationshipField::BinderItems => {
                &self.store.jn_binder_item_from_binder_binder_items
            }
        }
    }

    fn hydrate(&self, entity: &mut Binder) {
        entity.binder_items = junction_get(
            &self.store.jn_binder_item_from_binder_binder_items,
            &entity.id,
        );
    }
}

impl<'a> BinderTableRO for BinderHashMapTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Binder>, RepositoryError> {
        let binder_map = read_or_recover(&self.store.binders);
        match binder_map.get(id) {
            Some(entity) => {
                let mut e = entity.clone();
                drop(binder_map);
                self.hydrate(&mut e);
                Ok(Some(e))
            }
            None => Ok(None),
        }
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Binder>>, RepositoryError> {
        let mut result = Vec::with_capacity(ids.len());
        for id in ids {
            result.push(self.get(id)?);
        }
        Ok(result)
    }

    fn get_all(&self) -> Result<Vec<Binder>, RepositoryError> {
        let binder_map = read_or_recover(&self.store.binders);
        let entries: Vec<Binder> = binder_map.values().cloned().collect();
        drop(binder_map);
        let mut result = Vec::with_capacity(entries.len());
        for mut entity in entries {
            self.hydrate(&mut entity);
            result.push(entity);
        }
        Ok(result)
    }

    impl_relationship_methods!(BinderHashMapTableRO<'a>, BinderRelationshipField);
}