// Generated by Qleany v1.4.2 from entity_controller_cpp.tera
#include "trash_info_controller.h"

#include "controller_command_helpers.h"
#include "direct_access/use_case_helpers/create_orphans_uc.h"
#include "direct_access/use_case_helpers/create_uc.h"
#include "direct_access/use_case_helpers/get_all_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_count_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_in_range_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_many_uc.h"
#include "direct_access/use_case_helpers/get_relationship_ids_uc.h"
#include "direct_access/use_case_helpers/get_uc.h"
#include "direct_access/use_case_helpers/move_relationship_ids_uc.h"
#include "direct_access/use_case_helpers/remove_uc.h"
#include "direct_access/use_case_helpers/set_relationship_ids_uc.h"
#include "direct_access/use_case_helpers/update_uc.h"
#include "dto_mapper.h"
#include "entities/trash_info.h"
#include "service_locator.h"
#include "trash_info_unit_of_work.h"
#include <QCoro/QCoroTask>
#include <QCoro/QCoroTimer>

#include <memory>
#include <stdexcept>

namespace Skribisto::DirectAccess::TrashInfo
{
namespace SCE = Skribisto::Common::Entities;
namespace SCDTrashInfo = Skribisto::Common::DirectAccess::TrashInfo;
namespace Helpers = Skribisto::Common::ControllerHelpers;
namespace UCH = Skribisto::Common::DirectAccess::UseCaseHelpers;

// -- Type aliases for generic use case helpers --------------------------------

using GetUC = UCH::GetUseCase<TrashInfoDto, DtoMapper, ITrashInfoUnitOfWork>;
using GetAllUC = UCH::GetAllUseCase<TrashInfoDto, DtoMapper, ITrashInfoUnitOfWork>;
using UpdateUC = UCH::UpdateUseCase<SCE::TrashInfo, TrashInfoDto, DtoMapper, ITrashInfoUnitOfWork, false>;
using RemoveUC = UCH::RemoveUseCase<ITrashInfoUnitOfWork, false>;
using CreateUC =
    UCH::CreateUseCase<SCE::TrashInfo, CreateTrashInfoDto, TrashInfoDto, DtoMapper, ITrashInfoUnitOfWork, false, false>;
using GetRelIdsUC = UCH::GetRelationshipIdsUseCase<DtoMapper, ITrashInfoUnitOfWork, TrashInfoRelationshipField>;
using GetRelIdsManyUC = UCH::GetRelationshipIdsManyUseCase<DtoMapper, ITrashInfoUnitOfWork, TrashInfoRelationshipField>;
using GetRelIdsCountUC =
    UCH::GetRelationshipIdsCountUseCase<DtoMapper, ITrashInfoUnitOfWork, TrashInfoRelationshipField>;
using GetRelIdsInRangeUC =
    UCH::GetRelationshipIdsInRangeUseCase<DtoMapper, ITrashInfoUnitOfWork, TrashInfoRelationshipField>;
using SetRelIdsUC =
    UCH::SetRelationshipIdsUseCase<SCE::TrashInfo, DtoMapper, ITrashInfoUnitOfWork, TrashInfoRelationshipField, false>;
using MoveRelIdsUC =
    UCH::MoveRelationshipIdsUseCase<SCE::TrashInfo, DtoMapper, ITrashInfoUnitOfWork, TrashInfoRelationshipField, false>;

// Default timeout for async command/query execution (ms)
static constexpr int kDefaultCommandTimeoutMs = 500;

TrashInfoController::TrashInfoController(QObject *parent, int undoRedoStackId)
    : QObject(parent), m_undoRedoStackId(undoRedoStackId)
{
    resolveDependencies();
}

void TrashInfoController::setUndoRedoStackId(int undoRedoStackId)
{
    m_undoRedoStackId = undoRedoStackId;
}

int TrashInfoController::undoRedoStackId() const
{
    return m_undoRedoStackId;
}

void TrashInfoController::resolveDependencies()
{
    auto *locator = Common::ServiceLocator::instance();
    if (!locator) [[unlikely]]
        throw std::runtime_error("ServiceLocator not initialized — cannot construct TrashInfoController");
    m_dbContext = locator->dbContext();
    m_eventRegistry = locator->eventRegistry();
    m_undoRedoSystem = locator->undoRedoSystem();
}

// ---------------------------------------------------------------------------
// CRUD Operations
// ---------------------------------------------------------------------------
QCoro::Task<QList<TrashInfoDto>> TrashInfoController::create(const QList<CreateTrashInfoDto> &trashInfos, int ownerId,
                                                             int index)
{
    auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<CreateUC>(std::move(uow));

    co_return co_await Helpers::executeNotUndoableCommand<QList<TrashInfoDto>>(
        m_undoRedoSystem, u"Create trashInfos Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        trashInfos, ownerId, index);
}

QCoro::Task<QList<TrashInfoDto>> TrashInfoController::createOrphans(const QList<CreateTrashInfoDto> &trashInfos)
{
    using CreateOrphanUC = UCH::CreateOrphanUseCase<SCE::TrashInfo, CreateTrashInfoDto, TrashInfoDto, DtoMapper,
                                                    ITrashInfoUnitOfWork, false>;

    auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<CreateOrphanUC>(std::move(uow));

    co_return co_await Helpers::executeNotUndoableCommand<QList<TrashInfoDto>>(
        m_undoRedoSystem, u"Create orphan trashInfos Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        trashInfos);
}

QCoro::Task<QList<TrashInfoDto>> TrashInfoController::get(const QList<int> &trashInfoIds) const
{
    co_return co_await Helpers::executeReadQuery<QList<TrashInfoDto>>(
        m_undoRedoSystem, u"Get trashInfos Query"_s, [this, trashInfoIds]() -> QList<TrashInfoDto> {
            auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetUC>(std::move(uow));
            return useCase->execute(trashInfoIds);
        });
}

QCoro::Task<QList<TrashInfoDto>> TrashInfoController::getAll() const
{
    co_return co_await Helpers::executeReadQuery<QList<TrashInfoDto>>(
        m_undoRedoSystem, u"GetAll trashInfos Query"_s, [this]() -> QList<TrashInfoDto> {
            auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetAllUC>(std::move(uow));
            return useCase->execute();
        });
}

QCoro::Task<QList<TrashInfoDto>> TrashInfoController::update(const QList<TrashInfoDto> &trashInfos)
{
    auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<UpdateUC>(std::move(uow));

    co_return co_await Helpers::executeNotUndoableCommand<QList<TrashInfoDto>>(
        m_undoRedoSystem, u"Update trashInfos Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        trashInfos);
}

QCoro::Task<QList<int>> TrashInfoController::remove(const QList<int> &trashInfoIds)
{
    auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<RemoveUC>(std::move(uow));

    co_return co_await Helpers::executeNotUndoableCommand<QList<int>>(
        m_undoRedoSystem, u"Remove trashInfos Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        trashInfoIds);
}

// ---------------------------------------------------------------------------
// Relationship Operations
// ---------------------------------------------------------------------------

QCoro::Task<QList<int>> TrashInfoController::getRelationshipIds(int trashInfoId,
                                                                TrashInfoRelationshipField relationship) const
{
    co_return co_await Helpers::executeReadQuery<QList<int>>(
        m_undoRedoSystem, u"Get TrashInfo Relationship IDs Query"_s, [this, trashInfoId, relationship]() -> QList<int> {
            auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsUC>(std::move(uow));
            return useCase->execute(trashInfoId, relationship);
        });
}

QCoro::Task<void> TrashInfoController::setRelationshipIds(int trashInfoId, TrashInfoRelationshipField relationship,
                                                          const QList<int> &relatedIds)
{
    auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<SetRelIdsUC>(std::move(uow));

    co_await Helpers::executeNotUndoableCommandVoid(
        m_undoRedoSystem, u"Set TrashInfo Relationship IDs Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        trashInfoId, relationship, relatedIds);
}

QCoro::Task<QHash<int, QList<int>>> TrashInfoController::getRelationshipIdsMany(
    const QList<int> &trashInfoIds, TrashInfoRelationshipField relationship) const
{
    co_return co_await Helpers::executeReadQuery<QHash<int, QList<int>>>(
        m_undoRedoSystem, u"Get TrashInfo Relationship IDs Many Query"_s,
        [this, trashInfoIds, relationship]() -> QHash<int, QList<int>> {
            auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsManyUC>(std::move(uow));
            return useCase->execute(trashInfoIds, relationship);
        });
}

QCoro::Task<int> TrashInfoController::getRelationshipIdsCount(int trashInfoId,
                                                              TrashInfoRelationshipField relationship) const
{
    co_return co_await Helpers::executeReadQuery<int>(
        m_undoRedoSystem, u"Get TrashInfo Relationship IDs Count Query"_s, [this, trashInfoId, relationship]() -> int {
            auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsCountUC>(std::move(uow));
            return useCase->execute(trashInfoId, relationship);
        });
}

QCoro::Task<QList<int>> TrashInfoController::getRelationshipIdsInRange(int trashInfoId,
                                                                       TrashInfoRelationshipField relationship,
                                                                       int offset, int limit) const
{
    co_return co_await Helpers::executeReadQuery<QList<int>>(
        m_undoRedoSystem, u"Get TrashInfo Relationship IDs In Range Query"_s,
        [this, trashInfoId, relationship, offset, limit]() -> QList<int> {
            auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
            auto useCase = std::make_unique<GetRelIdsInRangeUC>(std::move(uow));
            return useCase->execute(trashInfoId, relationship, offset, limit);
        });
}

QCoro::Task<QList<int>> TrashInfoController::moveRelationshipIds(int trashInfoId,
                                                                 TrashInfoRelationshipField relationship,
                                                                 const QList<int> &idsToMove, int newIndex)
{
    auto uow = std::make_unique<TrashInfoUnitOfWork>(*m_dbContext, m_eventRegistry);
    auto useCase = std::make_shared<MoveRelIdsUC>(std::move(uow));

    co_return co_await Helpers::executeNotUndoableCommand<QList<int>>(
        m_undoRedoSystem, u"Move TrashInfo Relationship IDs Command"_s, std::move(useCase), kDefaultCommandTimeoutMs,
        [this](const QString &cmd, const QString &msg) {
            if (m_eventRegistry)
                m_eventRegistry->publishError(cmd, msg);
        },
        trashInfoId, relationship, idsToMove, newIndex);
}

} // namespace Skribisto::DirectAccess::TrashInfo
