// Generated by Qleany v1.4.2 from entity_controller_h.tera
#pragma once

#include "database/db_context.h"
#include "direct_access/event_registry.h"
#include "dtos.h"
#include "undo_redo/undo_redo_system.h"
#include <QCoro/QCoroTask>

#include <QPointer>

namespace Skribisto::DirectAccess::TrashInfo
{
namespace SCDatabase = Skribisto::Common::Database;

class TrashInfoController : public QObject
{
    Q_OBJECT
  public:
    TrashInfoController(const TrashInfoController &) = delete;
    TrashInfoController &operator=(const TrashInfoController &) = delete;
    TrashInfoController(TrashInfoController &&) = delete;
    TrashInfoController &operator=(TrashInfoController &&) = delete;
    explicit TrashInfoController(QObject *parent, int undoRedoStackId = 0);

    void setUndoRedoStackId(int undoRedoStackId);
    int undoRedoStackId() const;
    QCoro::Task<QList<TrashInfoDto>> create(const QList<CreateTrashInfoDto> &trashInfos, int ownerId, int index = -1);
    QCoro::Task<QList<TrashInfoDto>> createOrphans(const QList<CreateTrashInfoDto> &trashInfos);
    static CreateTrashInfoDto getCreateDto()
    {
        return {};
    }
    QCoro::Task<QList<TrashInfoDto>> get(const QList<int> &trashInfoIds) const;
    QCoro::Task<QList<TrashInfoDto>> getAll() const;
    QCoro::Task<QList<TrashInfoDto>> update(const QList<TrashInfoDto> &trashInfos);
    QCoro::Task<QList<int>> remove(const QList<int> &trashInfoIds);

    QCoro::Task<QList<int>> getRelationshipIds(int trashInfoId, TrashInfoRelationshipField relationship) const;
    QCoro::Task<void> setRelationshipIds(int trashInfoId, TrashInfoRelationshipField relationship,
                                         const QList<int> &relatedIds);
    QCoro::Task<QHash<int, QList<int>>> getRelationshipIdsMany(const QList<int> &trashInfoIds,
                                                               TrashInfoRelationshipField relationship) const;
    QCoro::Task<int> getRelationshipIdsCount(int trashInfoId, TrashInfoRelationshipField relationship) const;
    QCoro::Task<QList<int>> getRelationshipIdsInRange(int trashInfoId, TrashInfoRelationshipField relationship,
                                                      int offset, int limit) const;
    QCoro::Task<QList<int>> moveRelationshipIds(int trashInfoId, TrashInfoRelationshipField relationship,
                                                const QList<int> &idsToMove, int newIndex = -1);

  private:
    void resolveDependencies();
    QPointer<SCDatabase::DbContext> m_dbContext;
    QPointer<Common::DirectAccess::EventRegistry> m_eventRegistry;
    QPointer<Common::UndoRedo::UndoRedoSystem> m_undoRedoSystem;
    int m_undoRedoStackId = 0;
};
} // namespace Skribisto::DirectAccess::TrashInfo
