// Generated by Qleany v1.4.2 from uc_helper_remove_h.tera
/******************************************************************************
 * Generic Remove Use Case
 *
 * Header-only C++20 template that replaces per-entity Remove use cases.
 *
 * Template parameters:
 *   UoWInterfaceT - Unit of work interface
 *   IsUndoable    - Compile-time flag for undo/redo support
 ******************************************************************************/

#pragma once

#include "database/snapshot_types.h"
#include "undo_redo/undo_redo_command.h"

#include <QList>
#include <memory>
#include <stdexcept>
#include <type_traits>

using namespace Qt::StringLiterals;

namespace Skribisto::Common::DirectAccess::UseCaseHelpers
{

namespace SCDatabase = Skribisto::Common::Database;
namespace SCU = Skribisto::Common::UndoRedo;

template <typename UoWInterfaceT, bool IsUndoable = false> class RemoveUseCase
{
  public:
    explicit RemoveUseCase(std::unique_ptr<UoWInterfaceT> uow) : m_uow(std::move(uow))
    {
    }
    ~RemoveUseCase() = default;

    QList<int> execute(const QList<int> &ids)
    {
        if (m_hasExecuted)
            return m_removedIds;

        try
        {
            if (!m_uow->beginTransaction())
                throw std::runtime_error("Failed to begin transaction");

            if constexpr (IsUndoable)
            {
                m_undoState.originalIds = ids;
                m_undoState.treeSnapshot = m_uow->snapshot(ids);
            }

            m_removedIds = m_uow->remove(ids);

            if (!m_uow->commit())
                throw std::runtime_error("Failed to commit transaction");

            m_hasExecuted = true;
        }
        catch (...)
        {
            m_uow->rollback();
            throw;
        }

        return m_removedIds;
    }

    SCU::Result<void> undo()
        requires(IsUndoable)
    {
        if (!m_hasExecuted || m_removedIds.isEmpty())
            return SCU::Result<void>("Cannot undo: no entities were removed"_L1);

        try
        {
            if (!m_uow->beginTransaction())
                throw std::runtime_error("Failed to begin transaction");

            m_uow->restore(m_undoState.treeSnapshot);

            if (!m_uow->commit())
                throw std::runtime_error("Failed to commit transaction");

            return SCU::Result<void>();
        }
        catch (...)
        {
            m_uow->rollback();
            throw;
        }
    }

    SCU::Result<void> redo()
        requires(IsUndoable)
    {
        if (!m_hasExecuted)
            return SCU::Result<void>("Cannot redo: execute() must be called first"_L1);

        try
        {
            if (!m_uow->beginTransaction())
                throw std::runtime_error("Failed to begin transaction");

            m_undoState.treeSnapshot = m_uow->snapshot(m_undoState.originalIds);
            m_uow->remove(m_undoState.originalIds);

            if (!m_uow->commit())
                throw std::runtime_error("Failed to commit transaction");

            return SCU::Result<void>();
        }
        catch (...)
        {
            m_uow->rollback();
            throw;
        }
    }

  private:
    std::unique_ptr<UoWInterfaceT> m_uow;
    QList<int> m_removedIds;
    bool m_hasExecuted = false;

    struct UndoState
    {
        QList<int> originalIds;
        SCDatabase::EntityTreeSnapshot treeSnapshot;
    };
    struct NoState
    {
    };
    [[no_unique_address]] std::conditional_t<IsUndoable, UndoState, NoState> m_undoState{};
};

} // namespace Skribisto::Common::DirectAccess::UseCaseHelpers
