// Generated by Qleany v1.4.2 from entity_field_list_model_h.tera

#pragma once
#include "binder_item/binder_item_controller.h"
#include "binder_tag/binder_tag_controller.h"
#include "binder_tag/dtos.h"
#include "direct_access/event_registry.h"

#include <QAbstractListModel>
#include <QPointer>

namespace Skribisto::DirectAccess::BinderItem
{

class BinderItemTagsListModel : public QAbstractListModel
{
    Q_OBJECT
    Q_PROPERTY(int undoRedoStackId READ undoRedoStackId WRITE setUndoRedoStackId NOTIFY undoRedoStackIdChanged)
    Q_PROPERTY(int binderItemId READ binderItemId WRITE setBinderItemId NOTIFY binderItemIdChanged)

  public:
    enum Roles
    {
        IdRole = Qt::UserRole + 1,
        CreatedAtRole,
        UpdatedAtRole,
        NameRole,
        ColorRole,
        TextColorRole,
    };
    Q_ENUM(Roles)

    explicit BinderItemTagsListModel(QObject *parent = nullptr, int undoRedoStackId = 0);

    int undoRedoStackId() const;
    void setUndoRedoStackId(int undoRedoStackId);

    // Basic functionality:
    int rowCount(const QModelIndex &parent = QModelIndex()) const override;

    QVariant data(const QModelIndex &index, int role = Qt::DisplayRole) const override;

    // Add data:
    bool setData(const QModelIndex &index, const QVariant &value, int role = Qt::EditRole) override;

    Qt::ItemFlags flags(const QModelIndex &index) const override;

    QHash<int, QByteArray> roleNames() const override;

    int binderItemId() const;
    void setBinderItemId(int binderItemId);

  Q_SIGNALS:
    void binderItemIdChanged();
    void undoRedoStackIdChanged();

  private Q_SLOTS:
    void onBinderTagCreated(const QList<int> &ids);
    void onBinderTagUpdated(const QList<int> &ids);
    void onBinderTagRemoved(const QList<int> &ids);
    void onBinderItemUpdated(const QList<int> &ids);
    void onBinderItemRelationshipChanged(
        int binderItemId, Common::DirectAccess::BinderItem::BinderItemRelationshipField relationshipField,
        const QList<int> &relatedIds);

  private:
    void resolveDependencies();
    void refreshData();
    void reorderToMatch(const QList<int> &orderedIds);

    int m_binderItemId = -1;
    int m_undoRedoStackId = 0;
    QList<BinderTag::BinderTagDto> m_binderTags;
    bool m_lastRelationshipChangeHandled = false;

    QPointer<Common::DirectAccess::EventRegistry> m_eventRegistry;
    QPointer<BinderTag::BinderTagController> m_binderTagController;
    QPointer<BinderItemController> m_binderItemController;
};

} // namespace Skribisto::DirectAccess::BinderItem