// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from common_entity_repository.tera

use std::fmt::Display;

use crate::{
    database::hashmap_store::HashMapStoreSnapshot,
    // `*_or_recover` rather than a plain `.read()/.write().unwrap()`: a panic
    // anywhere under a table's guard poisons that lock for the rest of the
    // process, and the release profile unwinds, so the poison is reachable in a
    // shipped build. Recovering (and clearing) it keeps one unrelated failure
    // from escalating into a second panic on every later access to the store.
    database::hashmap_store::{read_or_recover, write_or_recover},
    database::transactions::Transaction,
    direct_access::repository_factory,
    entities::RecentWork,
    event::{DirectAccessEntity, EntityEvent, Event, EventBuffer, Origin},
    snapshot::EntityTreeSnapshot,
    types::EntityId,
};

use crate::direct_access::system::SystemRelationshipField;
use crate::error::RepositoryError;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RecentWorkRelationshipField {}

impl Display for RecentWorkRelationshipField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub trait RecentWorkTable {
    fn create(&mut self, entity: &RecentWork) -> Result<RecentWork, RepositoryError>;
    fn create_multi(&mut self, entities: &[RecentWork])
    -> Result<Vec<RecentWork>, RepositoryError>;
    fn get(&self, id: &EntityId) -> Result<Option<RecentWork>, RepositoryError>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<RecentWork>>, RepositoryError>;
    fn get_all(&self) -> Result<Vec<RecentWork>, RepositoryError>;
    fn update(&mut self, entity: &RecentWork) -> Result<RecentWork, RepositoryError>;
    fn update_multi(&mut self, entities: &[RecentWork])
    -> Result<Vec<RecentWork>, RepositoryError>;
    fn update_with_relationships(
        &mut self,
        entity: &RecentWork,
    ) -> Result<RecentWork, RepositoryError>;
    fn update_with_relationships_multi(
        &mut self,
        entities: &[RecentWork],
    ) -> Result<Vec<RecentWork>, RepositoryError>;
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError>;
    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError>;
}

pub trait RecentWorkTableRO {
    fn get(&self, id: &EntityId) -> Result<Option<RecentWork>, RepositoryError>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<RecentWork>>, RepositoryError>;
    fn get_all(&self) -> Result<Vec<RecentWork>, RepositoryError>;
}

pub struct RecentWorkRepository<'a> {
    table: Box<dyn RecentWorkTable + 'a>,
    transaction: &'a Transaction,
}

impl<'a> RecentWorkRepository<'a> {
    pub fn new(table: Box<dyn RecentWorkTable + 'a>, transaction: &'a Transaction) -> Self {
        RecentWorkRepository { table, transaction }
    }

    pub fn create_orphan(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &RecentWork,
    ) -> Result<RecentWork, RepositoryError> {
        let new = self.table.create(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Created)),
            ids: vec![new.id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_orphan_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[RecentWork],
    ) -> Result<Vec<RecentWork>, RepositoryError> {
        let new_entities = self.table.create_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Created)),
            ids: new_entities.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(new_entities)
    }
    pub fn create(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &RecentWork,
        owner_id: EntityId,
        index: i32,
    ) -> Result<RecentWork, RepositoryError> {
        let new = self.table.create(entity)?;
        let created_id = new.id;

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        // Insert at index
        if index >= 0 && (index as usize) < relationship_ids.len() {
            relationship_ids.insert(index as usize, created_id);
        } else {
            relationship_ids.push(created_id);
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Created)),
            ids: vec![created_id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[RecentWork],
        owner_id: EntityId,
        index: i32,
    ) -> Result<Vec<RecentWork>, RepositoryError> {
        let new_entities = self.table.create_multi(entities)?;
        let created_ids: Vec<EntityId> = new_entities.iter().map(|e| e.id).collect();

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        if index >= 0 && (index as usize) < relationship_ids.len() {
            for (i, id) in created_ids.iter().enumerate() {
                relationship_ids.insert(index as usize + i, *id);
            }
        } else {
            relationship_ids.extend(created_ids.iter());
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Created)),
            ids: created_ids,
            data: None,
        });
        Ok(new_entities)
    }

    pub fn get(&self, id: &EntityId) -> Result<Option<RecentWork>, RepositoryError> {
        self.table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<RecentWork>>, RepositoryError> {
        self.table.get_multi(ids)
    }
    pub fn get_all(&self) -> Result<Vec<RecentWork>, RepositoryError> {
        self.table.get_all()
    }

    pub fn update(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &RecentWork,
    ) -> Result<RecentWork, RepositoryError> {
        let updated = self.table.update(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[RecentWork],
    ) -> Result<Vec<RecentWork>, RepositoryError> {
        let updated = self.table.update_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn update_with_relationships(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &RecentWork,
    ) -> Result<RecentWork, RepositoryError> {
        let updated = self.table.update_with_relationships(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_with_relationships_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[RecentWork],
    ) -> Result<Vec<RecentWork>, RepositoryError> {
        let updated = self.table.update_with_relationships_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn remove(
        &mut self,
        event_buffer: &mut EventBuffer,
        id: &EntityId,
    ) -> Result<(), RepositoryError> {
        let _entity = match self.table.get(id)? {
            Some(e) => e,
            None => return Ok(()),
        };
        // get all strong forward relationship fields

        // remove all strong relationships, initiating a cascade remove

        // Before removal, find which owner(s) reference this entity
        let affected_owner_ids: Vec<EntityId> = {
            let owner_repo = repository_factory::write::create_system_repository(self.transaction)?;
            owner_repo
                .get_relationships_from_right_ids(&SystemRelationshipField::RecentWorks, &[*id])?
                .into_iter()
                .map(|(owner_id, _)| owner_id)
                .collect()
        };
        // Save each owner's current relationship IDs (properly ordered via get_relationships_from_owner)
        let mut owner_rel_before: std::collections::HashMap<EntityId, Vec<EntityId>> =
            std::collections::HashMap::new();
        for owner_id in &affected_owner_ids {
            owner_rel_before.insert(*owner_id, self.get_relationships_from_owner(owner_id)?);
        }

        // remove entity
        self.table.remove(id)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Removed)),
            ids: vec![*id],
            data: None,
        });
        // Update each affected owner's relationship to exclude removed ID (emits Updated event)
        for owner_id in &affected_owner_ids {
            if let Some(rel_ids) = owner_rel_before.get(owner_id) {
                let updated: Vec<EntityId> =
                    rel_ids.iter().copied().filter(|rid| *rid != *id).collect();
                self.set_relationships_in_owner(event_buffer, owner_id, &updated)?;
            }
        }

        Ok(())
    }

    pub fn remove_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let entities = self.table.get_multi(ids)?;
        if entities.is_empty() || entities.iter().all(|e| e.is_none()) {
            return Ok(());
        }

        // get all strong forward relationship fields

        // remove all strong relationships, initiating a cascade remove

        // Before removal, find which owner(s) reference these entities
        let affected_owner_ids: Vec<EntityId> = {
            let owner_repo = repository_factory::write::create_system_repository(self.transaction)?;
            owner_repo
                .get_relationships_from_right_ids(&SystemRelationshipField::RecentWorks, ids)?
                .into_iter()
                .map(|(owner_id, _)| owner_id)
                .collect()
        };
        // Save each owner's current relationship IDs (properly ordered via get_relationships_from_owner)
        let mut owner_rel_before: std::collections::HashMap<EntityId, Vec<EntityId>> =
            std::collections::HashMap::new();
        for owner_id in &affected_owner_ids {
            owner_rel_before.insert(*owner_id, self.get_relationships_from_owner(owner_id)?);
        }

        self.table.remove_multi(ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Removed)),
            ids: ids.into(),
            data: None,
        });
        // Update each affected owner's relationship to exclude removed IDs (emits Updated event)
        {
            let removed_set: std::collections::HashSet<EntityId> = ids.iter().copied().collect();
            for owner_id in &affected_owner_ids {
                if let Some(rel_ids) = owner_rel_before.get(owner_id) {
                    let updated: Vec<EntityId> = rel_ids
                        .iter()
                        .copied()
                        .filter(|rid| !removed_set.contains(rid))
                        .collect();
                    self.set_relationships_in_owner(event_buffer, owner_id, &updated)?;
                }
            }
        }

        Ok(())
    }
    pub fn get_relationships_from_owner(
        &self,
        owner_id: &EntityId,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let repo = repository_factory::write::create_system_repository(self.transaction)?;
        repo.get_relationship(owner_id, &SystemRelationshipField::RecentWorks)
    }

    pub fn set_relationships_in_owner(
        &mut self,
        event_buffer: &mut EventBuffer,
        owner_id: &EntityId,
        ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut repo = repository_factory::write::create_system_repository(self.transaction)?;
        repo.set_relationship(
            event_buffer,
            owner_id,
            &SystemRelationshipField::RecentWorks,
            ids,
        )
    }

    pub fn snapshot(&self, ids: &[EntityId]) -> Result<EntityTreeSnapshot, RepositoryError> {
        // O(1) whole-store capture (im::HashMap structural sharing). Restore is scoped to `ids`.
        let store_snap = self.transaction.snapshot_store();
        Ok(EntityTreeSnapshot {
            store_snapshot: Some(store_snap),
            root_ids: ids.to_vec(),
        })
    }

    pub fn restore(
        &mut self,
        event_buffer: &mut EventBuffer,
        snap: &EntityTreeSnapshot,
    ) -> Result<(), RepositoryError> {
        let store_snap = snap
            .store_snapshot
            .as_ref()
            .ok_or_else(|| RepositoryError::Serialization("missing store snapshot".into()))?;
        let snap_store = store_snap
            .downcast_ref::<HashMapStoreSnapshot>()
            .ok_or_else(|| RepositoryError::Serialization("snapshot type mismatch".into()))?;

        // Scoped restore: walk the subtree rooted at the captured ids (strong relationships only),
        // in both the snapshot and the live store, and reconcile only it.
        let mut visited = std::collections::HashSet::new();
        self.restore_subtree(event_buffer, snap_store, &snap.root_ids, &mut visited)?;

        // Surgically reconcile the root ids' placement in their (external) strong owner,
        // preserving sibling edits made on other undo stacks.
        self.reconcile_backref_system_recent_works(event_buffer, snap_store, &snap.root_ids)?;

        Ok(())
    }

    /// Restore the subtree rooted at `ids` (of this entity type) to the snapshot state, recursing
    /// into strong children. Touches only the subtree: in-scope rows and the forward junctions they
    /// own are restored wholesale; external referrers are reconciled surgically; everything else
    /// (other trunks, non-undoable data) is left untouched. `visited` guards against cycles.
    pub(crate) fn restore_subtree(
        &self,
        event_buffer: &mut EventBuffer,
        snap: &HashMapStoreSnapshot,
        ids: &[EntityId],
        // Keyed by (entity type, id): EntityIds are per-type, not globally unique, so a bare
        // id set would let one entity type's id falsely mask another's.
        visited: &mut std::collections::HashSet<(&'static str, EntityId)>,
    ) -> Result<(), RepositoryError> {
        let ids: Vec<EntityId> = ids
            .iter()
            .copied()
            .filter(|id| visited.insert(("recent_work", *id)))
            .collect();
        if ids.is_empty() {
            return Ok(());
        }

        let store = self.transaction.get_store();

        // Three-way partition by presence in snapshot vs live store (read before mutating).
        let mut to_create: Vec<EntityId> = Vec::new(); // in snapshot, gone from live -> re-add
        let mut to_update: Vec<EntityId> = Vec::new(); // in both                    -> revert
        let mut to_delete: Vec<EntityId> = Vec::new(); // live only (created after)  -> delete
        {
            let live = read_or_recover(&store.recent_works);
            for id in &ids {
                match (snap.recent_works.contains_key(id), live.contains_key(id)) {
                    (true, false) => to_create.push(*id),
                    (true, true) => to_update.push(*id),
                    (false, true) => to_delete.push(*id),
                    (false, false) => {}
                }
            }
        }

        // 1. Recurse into strong children first (collect child ids from snapshot + live, then drop
        //    all locks before recursing so self-referential ownership cannot deadlock).

        // 2. Entity rows: revert/re-add from snapshot, delete the ones created after it.
        {
            let mut live = write_or_recover(&store.recent_works);
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(row) = snap.recent_works.get(id) {
                    live.insert(*id, row.clone());
                }
            }
            for id in &to_delete {
                live.remove(id);
            }
        }

        // 3. This entity's own forward junctions (strong + weak): restored wholesale because the
        //    junction key is in-scope (owned exclusively by this trunk).

        // 4. External weak referrers of these ids: reconcile surgically (membership only).

        // 5. Events: precise per-id (Created/Updated/Removed), not a whole-store storm.
        if !to_create.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Created)),
                ids: to_create.clone(),
                data: None,
            });
        }
        if !to_update.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Updated)),
                ids: to_update.clone(),
                data: None,
            });
        }
        if !to_delete.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::RecentWork(EntityEvent::Removed)),
                ids: to_delete.clone(),
                data: None,
            });
        }

        Ok(())
    }

    /// Surgically reconcile one external referrer junction (out-of-scope key -> in-scope values):
    /// `system.recent_works`.
    fn reconcile_backref_system_recent_works(
        &self,
        event_buffer: &mut EventBuffer,
        snap: &HashMapStoreSnapshot,
        scope_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let scope: std::collections::HashSet<EntityId> = scope_ids.iter().copied().collect();
        if scope.is_empty() {
            return Ok(());
        }
        let store = self.transaction.get_store();

        // External left keys whose ordered list references any scope id, in snapshot or live.
        let mut left_keys: std::collections::HashSet<EntityId> = std::collections::HashSet::new();
        for (left, rights) in snap.jn_recent_work_from_system_recent_works.iter() {
            if rights.iter().any(|rid| scope.contains(rid)) {
                left_keys.insert(*left);
            }
        }
        {
            let live_jn = read_or_recover(&store.jn_recent_work_from_system_recent_works);
            for (left, rights) in live_jn.iter() {
                if rights.iter().any(|rid| scope.contains(rid)) {
                    left_keys.insert(*left);
                }
            }
        }

        for left in left_keys {
            let snap_list: Vec<EntityId> = snap
                .jn_recent_work_from_system_recent_works
                .get(&left)
                .cloned()
                .unwrap_or_default();
            let new_list = {
                let live_jn = read_or_recover(&store.jn_recent_work_from_system_recent_works);
                let live_list: Vec<EntityId> = live_jn.get(&left).cloned().unwrap_or_default();
                let reconciled = crate::database::hashmap_store::reconcile_backref_list(
                    &live_list, &snap_list, &scope,
                );
                if reconciled == live_list {
                    None
                } else {
                    Some(reconciled)
                }
            };
            if let Some(reconciled) = new_list {
                write_or_recover(&store.jn_recent_work_from_system_recent_works)
                    .insert(left, reconciled);
                event_buffer.push(Event {
                    origin: Origin::DirectAccess(DirectAccessEntity::System(EntityEvent::Updated)),
                    ids: vec![left],
                    data: None,
                });
            }
        }
        Ok(())
    }
}

pub struct RecentWorkRepositoryRO<'a> {
    table: Box<dyn RecentWorkTableRO + 'a>,
}
impl<'a> RecentWorkRepositoryRO<'a> {
    pub fn new(table: Box<dyn RecentWorkTableRO + 'a>) -> Self {
        RecentWorkRepositoryRO { table }
    }
    pub fn get(&self, id: &EntityId) -> Result<Option<RecentWork>, RepositoryError> {
        self.table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<RecentWork>>, RepositoryError> {
        self.table.get_multi(ids)
    }
    pub fn get_all(&self) -> Result<Vec<RecentWork>, RepositoryError> {
        self.table.get_all()
    }
}
