// Generated by Qleany v1.4.5 from feature_dtos_h.tera
#pragma once

#include <QObject>
#include <qobjectdefs.h>

namespace Skribisto::HandlingAppLifecycle
{
Q_NAMESPACE

} // namespace Skribisto::HandlingAppLifecycle
