#ifndef GLOBAL_WRITINGZONE_H
#define GLOBAL_WRITINGZONE_H

#include <QtCore/QtGlobal>

#if defined(PLUME_CREATOR_WRITINGZONE_LIBRARY)
#  define EXPORT_WRITINGZONE Q_DECL_EXPORT
#else
#  define EXPORT_WRITINGZONE Q_DECL_IMPORT
#endif

#endif // GLOBAL_WRITINGZONE_H
