// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from common_entity_repository.tera

use std::fmt::Display;

use crate::{
    database::hashmap_store::HashMapStoreSnapshot,
    database::transactions::Transaction,
    direct_access::repository_factory,
    entities::Work,
    event::{DirectAccessEntity, EntityEvent, Event, EventBuffer, Origin},
    snapshot::EntityTreeSnapshot,
    types::EntityId,
};

use crate::direct_access::root::RootRelationshipField;
use crate::error::RepositoryError;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkRelationshipField {
    Binders,
    DictWords,
    NoteTemplates,
    Paces,
    SmartPunctuation,
    Tags,
    TextReplacementRules,
    TrashInfos,
}

impl Display for WorkRelationshipField {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

pub trait WorkTable {
    fn create(&mut self, entity: &Work) -> Result<Work, RepositoryError>;
    fn create_multi(&mut self, entities: &[Work]) -> Result<Vec<Work>, RepositoryError>;
    fn get(&self, id: &EntityId) -> Result<Option<Work>, RepositoryError>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Work>>, RepositoryError>;
    fn get_all(&self) -> Result<Vec<Work>, RepositoryError>;
    fn update(&mut self, entity: &Work) -> Result<Work, RepositoryError>;
    fn update_multi(&mut self, entities: &[Work]) -> Result<Vec<Work>, RepositoryError>;
    fn update_with_relationships(&mut self, entity: &Work) -> Result<Work, RepositoryError>;
    fn update_with_relationships_multi(
        &mut self,
        entities: &[Work],
    ) -> Result<Vec<Work>, RepositoryError>;
    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError>;
    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError>;
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError>;
    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &WorkRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError>;
    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<usize, RepositoryError>;
    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError>;
    fn get_relationships_from_right_ids(
        &self,
        field: &WorkRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError>;
    fn set_relationship_multi(
        &mut self,
        field: &WorkRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError>;
    fn set_relationship(
        &mut self,
        id: &EntityId,
        field: &WorkRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError>;
    fn move_relationship_ids(
        &mut self,
        id: &EntityId,
        field: &WorkRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError>;
}

pub trait WorkTableRO {
    fn get(&self, id: &EntityId) -> Result<Option<Work>, RepositoryError>;
    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Work>>, RepositoryError>;
    fn get_all(&self) -> Result<Vec<Work>, RepositoryError>;
    fn get_relationship(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError>;
    fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &WorkRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError>;
    fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<usize, RepositoryError>;
    fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError>;
    fn get_relationships_from_right_ids(
        &self,
        field: &WorkRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError>;
}

pub struct WorkRepository<'a> {
    table: Box<dyn WorkTable + 'a>,
    transaction: &'a Transaction,
}

impl<'a> WorkRepository<'a> {
    pub fn new(table: Box<dyn WorkTable + 'a>, transaction: &'a Transaction) -> Self {
        WorkRepository { table, transaction }
    }

    pub fn create_orphan(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &Work,
    ) -> Result<Work, RepositoryError> {
        let new = self.table.create(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Created)),
            ids: vec![new.id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_orphan_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[Work],
    ) -> Result<Vec<Work>, RepositoryError> {
        let new_entities = self.table.create_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Created)),
            ids: new_entities.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(new_entities)
    }
    pub fn create(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &Work,
        owner_id: EntityId,
        index: i32,
    ) -> Result<Work, RepositoryError> {
        let new = self.table.create(entity)?;
        let created_id = new.id;

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        // Insert at index
        if index >= 0 && (index as usize) < relationship_ids.len() {
            relationship_ids.insert(index as usize, created_id);
        } else {
            relationship_ids.push(created_id);
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Created)),
            ids: vec![created_id],
            data: None,
        });
        Ok(new)
    }

    pub fn create_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[Work],
        owner_id: EntityId,
        index: i32,
    ) -> Result<Vec<Work>, RepositoryError> {
        let new_entities = self.table.create_multi(entities)?;
        let created_ids: Vec<EntityId> = new_entities.iter().map(|e| e.id).collect();

        let mut relationship_ids = self.get_relationships_from_owner(&owner_id)?;
        if index >= 0 && (index as usize) < relationship_ids.len() {
            for (i, id) in created_ids.iter().enumerate() {
                relationship_ids.insert(index as usize + i, *id);
            }
        } else {
            relationship_ids.extend(created_ids.iter());
        }

        self.set_relationships_in_owner(event_buffer, &owner_id, &relationship_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Created)),
            ids: created_ids,
            data: None,
        });
        Ok(new_entities)
    }

    pub fn get(&self, id: &EntityId) -> Result<Option<Work>, RepositoryError> {
        self.table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Work>>, RepositoryError> {
        self.table.get_multi(ids)
    }
    pub fn get_all(&self) -> Result<Vec<Work>, RepositoryError> {
        self.table.get_all()
    }

    pub fn update(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &Work,
    ) -> Result<Work, RepositoryError> {
        let updated = self.table.update(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[Work],
    ) -> Result<Vec<Work>, RepositoryError> {
        let updated = self.table.update_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn update_with_relationships(
        &mut self,
        event_buffer: &mut EventBuffer,
        entity: &Work,
    ) -> Result<Work, RepositoryError> {
        let updated = self.table.update_with_relationships(entity)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
            ids: vec![updated.id],
            data: None,
        });
        Ok(updated)
    }

    pub fn update_with_relationships_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        entities: &[Work],
    ) -> Result<Vec<Work>, RepositoryError> {
        let updated = self.table.update_with_relationships_multi(entities)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
            ids: updated.iter().map(|e| e.id).collect(),
            data: None,
        });
        Ok(updated)
    }

    pub fn remove(
        &mut self,
        event_buffer: &mut EventBuffer,
        id: &EntityId,
    ) -> Result<(), RepositoryError> {
        let entity = match self.table.get(id)? {
            Some(e) => e,
            None => return Ok(()),
        };
        // get all strong forward relationship fields

        let binders = entity.binders.clone();
        let tags = entity.tags.clone();
        let dict_words = entity.dict_words.clone();
        let text_replacement_rules = entity.text_replacement_rules.clone();
        let note_templates = entity.note_templates.clone();
        let smart_punctuation = entity.smart_punctuation.clone();
        let trash_infos = entity.trash_infos.clone();
        let paces = entity.paces.clone();

        // remove all strong relationships, initiating a cascade remove

        repository_factory::write::create_binder_repository(self.transaction)?
            .remove_multi(event_buffer, &binders)?;
        repository_factory::write::create_binder_tag_repository(self.transaction)?
            .remove_multi(event_buffer, &tags)?;
        repository_factory::write::create_dict_word_repository(self.transaction)?
            .remove_multi(event_buffer, &dict_words)?;
        repository_factory::write::create_text_replacement_rule_repository(self.transaction)?
            .remove_multi(event_buffer, &text_replacement_rules)?;
        repository_factory::write::create_note_template_repository(self.transaction)?
            .remove_multi(event_buffer, &note_templates)?;
        repository_factory::write::create_smart_punctuation_repository(self.transaction)?
            .remove(event_buffer, &smart_punctuation)?;
        repository_factory::write::create_trash_info_repository(self.transaction)?
            .remove_multi(event_buffer, &trash_infos)?;
        repository_factory::write::create_pace_repository(self.transaction)?
            .remove_multi(event_buffer, &paces)?;
        // Before removal, find which owner(s) reference this entity
        let affected_owner_ids: Vec<EntityId> = {
            let owner_repo = repository_factory::write::create_root_repository(self.transaction)?;
            owner_repo
                .get_relationships_from_right_ids(&RootRelationshipField::Works, &[*id])?
                .into_iter()
                .map(|(owner_id, _)| owner_id)
                .collect()
        };
        // Save each owner's current relationship IDs (properly ordered via get_relationships_from_owner)
        let mut owner_rel_before: std::collections::HashMap<EntityId, Vec<EntityId>> =
            std::collections::HashMap::new();
        for owner_id in &affected_owner_ids {
            owner_rel_before.insert(*owner_id, self.get_relationships_from_owner(owner_id)?);
        }

        // remove entity
        self.table.remove(id)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Removed)),
            ids: vec![*id],
            data: None,
        });
        // Update each affected owner's relationship to exclude removed ID (emits Updated event)
        for owner_id in &affected_owner_ids {
            if let Some(rel_ids) = owner_rel_before.get(owner_id) {
                let updated: Vec<EntityId> =
                    rel_ids.iter().copied().filter(|rid| *rid != *id).collect();
                self.set_relationships_in_owner(event_buffer, owner_id, &updated)?;
            }
        }

        Ok(())
    }

    pub fn remove_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let entities = self.table.get_multi(ids)?;
        if entities.is_empty() || entities.iter().all(|e| e.is_none()) {
            return Ok(());
        }

        // get all strong forward relationship fields

        let mut binders_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| entity.as_ref().map(|entity| entity.binders.clone()))
            .flatten()
            .collect();
        // remove duplicates
        binders_ids.sort();
        binders_ids.dedup();
        let mut tags_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| entity.as_ref().map(|entity| entity.tags.clone()))
            .flatten()
            .collect();
        // remove duplicates
        tags_ids.sort();
        tags_ids.dedup();
        let mut dict_words_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| entity.as_ref().map(|entity| entity.dict_words.clone()))
            .flatten()
            .collect();
        // remove duplicates
        dict_words_ids.sort();
        dict_words_ids.dedup();
        let mut text_replacement_rules_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| {
                entity
                    .as_ref()
                    .map(|entity| entity.text_replacement_rules.clone())
            })
            .flatten()
            .collect();
        // remove duplicates
        text_replacement_rules_ids.sort();
        text_replacement_rules_ids.dedup();
        let mut note_templates_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| entity.as_ref().map(|entity| entity.note_templates.clone()))
            .flatten()
            .collect();
        // remove duplicates
        note_templates_ids.sort();
        note_templates_ids.dedup();
        let smart_punctuation_ids: Vec<EntityId> = entities
            .iter()
            .filter_map(|entity| entity.as_ref().map(|entity| entity.smart_punctuation))
            .collect();
        let mut trash_infos_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| entity.as_ref().map(|entity| entity.trash_infos.clone()))
            .flatten()
            .collect();
        // remove duplicates
        trash_infos_ids.sort();
        trash_infos_ids.dedup();
        let mut paces_ids: Vec<EntityId> = entities
            .iter()
            .flat_map(|entity| entity.as_ref().map(|entity| entity.paces.clone()))
            .flatten()
            .collect();
        // remove duplicates
        paces_ids.sort();
        paces_ids.dedup();

        // remove all strong relationships, initiating a cascade remove

        repository_factory::write::create_binder_repository(self.transaction)?
            .remove_multi(event_buffer, &binders_ids)?;
        repository_factory::write::create_binder_tag_repository(self.transaction)?
            .remove_multi(event_buffer, &tags_ids)?;
        repository_factory::write::create_dict_word_repository(self.transaction)?
            .remove_multi(event_buffer, &dict_words_ids)?;
        repository_factory::write::create_text_replacement_rule_repository(self.transaction)?
            .remove_multi(event_buffer, &text_replacement_rules_ids)?;
        repository_factory::write::create_note_template_repository(self.transaction)?
            .remove_multi(event_buffer, &note_templates_ids)?;
        repository_factory::write::create_smart_punctuation_repository(self.transaction)?
            .remove_multi(event_buffer, &smart_punctuation_ids)?;
        repository_factory::write::create_trash_info_repository(self.transaction)?
            .remove_multi(event_buffer, &trash_infos_ids)?;
        repository_factory::write::create_pace_repository(self.transaction)?
            .remove_multi(event_buffer, &paces_ids)?;
        // Before removal, find which owner(s) reference these entities
        let affected_owner_ids: Vec<EntityId> = {
            let owner_repo = repository_factory::write::create_root_repository(self.transaction)?;
            owner_repo
                .get_relationships_from_right_ids(&RootRelationshipField::Works, ids)?
                .into_iter()
                .map(|(owner_id, _)| owner_id)
                .collect()
        };
        // Save each owner's current relationship IDs (properly ordered via get_relationships_from_owner)
        let mut owner_rel_before: std::collections::HashMap<EntityId, Vec<EntityId>> =
            std::collections::HashMap::new();
        for owner_id in &affected_owner_ids {
            owner_rel_before.insert(*owner_id, self.get_relationships_from_owner(owner_id)?);
        }

        self.table.remove_multi(ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Removed)),
            ids: ids.into(),
            data: None,
        });
        // Update each affected owner's relationship to exclude removed IDs (emits Updated event)
        {
            let removed_set: std::collections::HashSet<EntityId> = ids.iter().copied().collect();
            for owner_id in &affected_owner_ids {
                if let Some(rel_ids) = owner_rel_before.get(owner_id) {
                    let updated: Vec<EntityId> = rel_ids
                        .iter()
                        .copied()
                        .filter(|rid| !removed_set.contains(rid))
                        .collect();
                    self.set_relationships_in_owner(event_buffer, owner_id, &updated)?;
                }
            }
        }

        Ok(())
    }
    pub fn get_relationship(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        self.table.get_relationship(id, field)
    }
    pub fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &WorkRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        self.table.get_relationship_many(ids, field)
    }
    pub fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<usize, RepositoryError> {
        self.table.get_relationship_count(id, field)
    }
    pub fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        self.table
            .get_relationship_in_range(id, field, offset, limit)
    }
    pub fn get_relationships_from_right_ids(
        &self,
        field: &WorkRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        self.table
            .get_relationships_from_right_ids(field, right_ids)
    }

    pub fn set_relationship_multi(
        &mut self,
        event_buffer: &mut EventBuffer,
        field: &WorkRelationshipField,
        relationships: Vec<(EntityId, Vec<EntityId>)>,
    ) -> Result<(), RepositoryError> {
        // Validate that all right_ids exist
        let all_right_ids: Vec<EntityId> = relationships
            .iter()
            .flat_map(|(_, ids)| ids.iter().copied())
            .collect();
        if !all_right_ids.is_empty() {
            match field {
                WorkRelationshipField::Binders => {
                    let child_repo =
                        repository_factory::write::create_binder_repository(self.transaction)?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::DictWords => {
                    let child_repo =
                        repository_factory::write::create_dict_word_repository(self.transaction)?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::NoteTemplates => {
                    let child_repo = repository_factory::write::create_note_template_repository(
                        self.transaction,
                    )?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::Paces => {
                    let child_repo =
                        repository_factory::write::create_pace_repository(self.transaction)?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::SmartPunctuation => {
                    let child_repo =
                        repository_factory::write::create_smart_punctuation_repository(
                            self.transaction,
                        )?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::Tags => {
                    let child_repo =
                        repository_factory::write::create_binder_tag_repository(self.transaction)?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::TextReplacementRules => {
                    let child_repo =
                        repository_factory::write::create_text_replacement_rule_repository(
                            self.transaction,
                        )?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::TrashInfos => {
                    let child_repo =
                        repository_factory::write::create_trash_info_repository(self.transaction)?;
                    let found = child_repo.get_multi(&all_right_ids)?;
                    let missing: Vec<_> = all_right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship_multi",
                            ids: missing,
                        });
                    }
                }
            }
        }
        self.table
            .set_relationship_multi(field, relationships.clone())?;
        for (left_id, right_ids) in relationships {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
                ids: vec![left_id],
                data: Some(format!(
                    "{}:{}",
                    field,
                    right_ids
                        .iter()
                        .map(|id| id.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                )),
            });
        }
        Ok(())
    }

    pub fn set_relationship(
        &mut self,
        event_buffer: &mut EventBuffer,
        id: &EntityId,
        field: &WorkRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        // Validate that all right_ids exist
        if !right_ids.is_empty() {
            match field {
                WorkRelationshipField::Binders => {
                    let child_repo =
                        repository_factory::write::create_binder_repository(self.transaction)?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::DictWords => {
                    let child_repo =
                        repository_factory::write::create_dict_word_repository(self.transaction)?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::NoteTemplates => {
                    let child_repo = repository_factory::write::create_note_template_repository(
                        self.transaction,
                    )?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::Paces => {
                    let child_repo =
                        repository_factory::write::create_pace_repository(self.transaction)?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::SmartPunctuation => {
                    let child_repo =
                        repository_factory::write::create_smart_punctuation_repository(
                            self.transaction,
                        )?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::Tags => {
                    let child_repo =
                        repository_factory::write::create_binder_tag_repository(self.transaction)?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::TextReplacementRules => {
                    let child_repo =
                        repository_factory::write::create_text_replacement_rule_repository(
                            self.transaction,
                        )?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
                WorkRelationshipField::TrashInfos => {
                    let child_repo =
                        repository_factory::write::create_trash_info_repository(self.transaction)?;
                    let found = child_repo.get_multi(right_ids)?;
                    let missing: Vec<_> = right_ids
                        .iter()
                        .zip(found.iter())
                        .filter(|(_, entity)| entity.is_none())
                        .map(|(id, _)| *id)
                        .collect();
                    if !missing.is_empty() {
                        return Err(RepositoryError::MissingRelationshipTarget {
                            operation: "set_relationship",
                            ids: missing,
                        });
                    }
                }
            }
        }
        self.table.set_relationship(id, field, right_ids)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
            ids: vec![*id],
            data: Some(format!(
                "{}:{}",
                field,
                right_ids
                    .iter()
                    .map(|id| id.to_string())
                    .collect::<Vec<_>>()
                    .join(",")
            )),
        });
        Ok(())
    }

    pub fn move_relationship_ids(
        &mut self,
        event_buffer: &mut EventBuffer,
        id: &EntityId,
        field: &WorkRelationshipField,
        ids_to_move: &[EntityId],
        new_index: i32,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let reordered = self
            .table
            .move_relationship_ids(id, field, ids_to_move, new_index)?;
        event_buffer.push(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
            ids: vec![*id],
            data: Some(format!(
                "{}:{}",
                field,
                reordered
                    .iter()
                    .map(|id| id.to_string())
                    .collect::<Vec<_>>()
                    .join(",")
            )),
        });
        Ok(reordered)
    }
    pub fn get_relationships_from_owner(
        &self,
        owner_id: &EntityId,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        let repo = repository_factory::write::create_root_repository(self.transaction)?;
        repo.get_relationship(owner_id, &RootRelationshipField::Works)
    }

    pub fn set_relationships_in_owner(
        &mut self,
        event_buffer: &mut EventBuffer,
        owner_id: &EntityId,
        ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let mut repo = repository_factory::write::create_root_repository(self.transaction)?;
        repo.set_relationship(event_buffer, owner_id, &RootRelationshipField::Works, ids)
    }

    pub fn snapshot(&self, ids: &[EntityId]) -> Result<EntityTreeSnapshot, RepositoryError> {
        // O(1) whole-store capture (im::HashMap structural sharing). Restore is scoped to `ids`.
        let store_snap = self.transaction.snapshot_store();
        Ok(EntityTreeSnapshot {
            store_snapshot: Some(store_snap),
            root_ids: ids.to_vec(),
        })
    }

    pub fn restore(
        &mut self,
        event_buffer: &mut EventBuffer,
        snap: &EntityTreeSnapshot,
    ) -> Result<(), RepositoryError> {
        let store_snap = snap
            .store_snapshot
            .as_ref()
            .ok_or_else(|| RepositoryError::Serialization("missing store snapshot".into()))?;
        let snap_store = store_snap
            .downcast_ref::<HashMapStoreSnapshot>()
            .ok_or_else(|| RepositoryError::Serialization("snapshot type mismatch".into()))?;

        // Scoped restore: walk the subtree rooted at the captured ids (strong relationships only),
        // in both the snapshot and the live store, and reconcile only it.
        let mut visited = std::collections::HashSet::new();
        self.restore_subtree(event_buffer, snap_store, &snap.root_ids, &mut visited)?;

        // Surgically reconcile the root ids' placement in their (external) strong owner,
        // preserving sibling edits made on other undo stacks.
        self.reconcile_backref_root_works(event_buffer, snap_store, &snap.root_ids)?;

        Ok(())
    }

    /// Restore the subtree rooted at `ids` (of this entity type) to the snapshot state, recursing
    /// into strong children. Touches only the subtree: in-scope rows and the forward junctions they
    /// own are restored wholesale; external referrers are reconciled surgically; everything else
    /// (other trunks, non-undoable data) is left untouched. `visited` guards against cycles.
    pub(crate) fn restore_subtree(
        &self,
        event_buffer: &mut EventBuffer,
        snap: &HashMapStoreSnapshot,
        ids: &[EntityId],
        // Keyed by (entity type, id): EntityIds are per-type, not globally unique, so a bare
        // id set would let one entity type's id falsely mask another's.
        visited: &mut std::collections::HashSet<(&'static str, EntityId)>,
    ) -> Result<(), RepositoryError> {
        let ids: Vec<EntityId> = ids
            .iter()
            .copied()
            .filter(|id| visited.insert(("work", *id)))
            .collect();
        if ids.is_empty() {
            return Ok(());
        }

        let store = self.transaction.get_store();

        // Three-way partition by presence in snapshot vs live store (read before mutating).
        let mut to_create: Vec<EntityId> = Vec::new(); // in snapshot, gone from live -> re-add
        let mut to_update: Vec<EntityId> = Vec::new(); // in both                    -> revert
        let mut to_delete: Vec<EntityId> = Vec::new(); // live only (created after)  -> delete
        {
            let live = store.works.read().unwrap();
            for id in &ids {
                match (snap.works.contains_key(id), live.contains_key(id)) {
                    (true, false) => to_create.push(*id),
                    (true, true) => to_update.push(*id),
                    (false, true) => to_delete.push(*id),
                    (false, false) => {}
                }
            }
        }

        // 1. Recurse into strong children first (collect child ids from snapshot + live, then drop
        //    all locks before recursing so self-referential ownership cannot deadlock).
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap.jn_binder_from_work_binders.get(id) {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store.jn_binder_from_work_binders.read().unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_binder_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap.jn_binder_tag_from_work_tags.get(id) {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store.jn_binder_tag_from_work_tags.read().unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_binder_tag_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap.jn_dict_word_from_work_dict_words.get(id) {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store.jn_dict_word_from_work_dict_words.read().unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_dict_word_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap
                    .jn_text_replacement_rule_from_work_text_replacement_rules
                    .get(id)
                {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store
                    .jn_text_replacement_rule_from_work_text_replacement_rules
                    .read()
                    .unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_text_replacement_rule_repository(
                    self.transaction,
                )?
                .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap.jn_note_template_from_work_note_templates.get(id) {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store
                    .jn_note_template_from_work_note_templates
                    .read()
                    .unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_note_template_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap
                    .jn_smart_punctuation_from_work_smart_punctuation
                    .get(id)
                {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store
                    .jn_smart_punctuation_from_work_smart_punctuation
                    .read()
                    .unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_smart_punctuation_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap.jn_trash_info_from_work_trash_infos.get(id) {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store.jn_trash_info_from_work_trash_infos.read().unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_trash_info_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }
        {
            let mut child_ids: Vec<EntityId> = Vec::new();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(list) = snap.jn_pace_from_work_paces.get(id) {
                    child_ids.extend(list.iter().copied());
                }
            }
            {
                let live_jn = store.jn_pace_from_work_paces.read().unwrap();
                for id in &ids {
                    if let Some(list) = live_jn.get(id) {
                        child_ids.extend(list.iter().copied());
                    }
                }
            }
            child_ids.sort();
            child_ids.dedup();
            if !child_ids.is_empty() {
                repository_factory::write::create_pace_repository(self.transaction)?
                    .restore_subtree(event_buffer, snap, &child_ids, visited)?;
            }
        }

        // 2. Entity rows: revert/re-add from snapshot, delete the ones created after it.
        {
            let mut live = store.works.write().unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                if let Some(row) = snap.works.get(id) {
                    live.insert(*id, row.clone());
                }
            }
            for id in &to_delete {
                live.remove(id);
            }
        }

        // 3. This entity's own forward junctions (strong + weak): restored wholesale because the
        //    junction key is in-scope (owned exclusively by this trunk).
        {
            let mut live_jn = store.jn_binder_from_work_binders.write().unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap.jn_binder_from_work_binders.get(id) {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store.jn_dict_word_from_work_dict_words.write().unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap.jn_dict_word_from_work_dict_words.get(id) {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store
                .jn_note_template_from_work_note_templates
                .write()
                .unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap.jn_note_template_from_work_note_templates.get(id) {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store.jn_pace_from_work_paces.write().unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap.jn_pace_from_work_paces.get(id) {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store
                .jn_smart_punctuation_from_work_smart_punctuation
                .write()
                .unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap
                    .jn_smart_punctuation_from_work_smart_punctuation
                    .get(id)
                {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store.jn_binder_tag_from_work_tags.write().unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap.jn_binder_tag_from_work_tags.get(id) {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store
                .jn_text_replacement_rule_from_work_text_replacement_rules
                .write()
                .unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap
                    .jn_text_replacement_rule_from_work_text_replacement_rules
                    .get(id)
                {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }
        {
            let mut live_jn = store.jn_trash_info_from_work_trash_infos.write().unwrap();
            for id in to_create.iter().chain(to_update.iter()) {
                match snap.jn_trash_info_from_work_trash_infos.get(id) {
                    Some(v) => {
                        live_jn.insert(*id, v.clone());
                    }
                    None => {
                        live_jn.remove(id);
                    }
                }
            }
            for id in &to_delete {
                live_jn.remove(id);
            }
        }

        // 4. External weak referrers of these ids: reconcile surgically (membership only).
        self.reconcile_backref_work_info_work(event_buffer, snap, &ids)?;

        // 5. Events: precise per-id (Created/Updated/Removed), not a whole-store storm.
        if !to_create.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Created)),
                ids: to_create.clone(),
                data: None,
            });
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
                ids: to_create.clone(),
                data: None,
            });
        }
        if !to_update.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Updated)),
                ids: to_update.clone(),
                data: None,
            });
        }
        if !to_delete.is_empty() {
            event_buffer.push(Event {
                origin: Origin::DirectAccess(DirectAccessEntity::Work(EntityEvent::Removed)),
                ids: to_delete.clone(),
                data: None,
            });
        }

        Ok(())
    }

    /// Surgically reconcile one external referrer junction (out-of-scope key -> in-scope values):
    /// `work_info.work`.
    fn reconcile_backref_work_info_work(
        &self,
        event_buffer: &mut EventBuffer,
        snap: &HashMapStoreSnapshot,
        scope_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let scope: std::collections::HashSet<EntityId> = scope_ids.iter().copied().collect();
        if scope.is_empty() {
            return Ok(());
        }
        let store = self.transaction.get_store();

        // External left keys whose ordered list references any scope id, in snapshot or live.
        let mut left_keys: std::collections::HashSet<EntityId> = std::collections::HashSet::new();
        for (left, rights) in snap.jn_work_from_work_info_work.iter() {
            if rights.iter().any(|rid| scope.contains(rid)) {
                left_keys.insert(*left);
            }
        }
        {
            let live_jn = store.jn_work_from_work_info_work.read().unwrap();
            for (left, rights) in live_jn.iter() {
                if rights.iter().any(|rid| scope.contains(rid)) {
                    left_keys.insert(*left);
                }
            }
        }

        for left in left_keys {
            let snap_list: Vec<EntityId> = snap
                .jn_work_from_work_info_work
                .get(&left)
                .cloned()
                .unwrap_or_default();
            let new_list = {
                let live_jn = store.jn_work_from_work_info_work.read().unwrap();
                let live_list: Vec<EntityId> = live_jn.get(&left).cloned().unwrap_or_default();
                let reconciled = crate::database::hashmap_store::reconcile_backref_list(
                    &live_list, &snap_list, &scope,
                );
                if reconciled == live_list {
                    None
                } else {
                    Some(reconciled)
                }
            };
            if let Some(reconciled) = new_list {
                store
                    .jn_work_from_work_info_work
                    .write()
                    .unwrap()
                    .insert(left, reconciled);
                event_buffer.push(Event {
                    origin: Origin::DirectAccess(DirectAccessEntity::WorkInfo(
                        EntityEvent::Updated,
                    )),
                    ids: vec![left],
                    data: None,
                });
            }
        }
        Ok(())
    }

    /// Surgically reconcile one external referrer junction (out-of-scope key -> in-scope values):
    /// `root.works`.
    fn reconcile_backref_root_works(
        &self,
        event_buffer: &mut EventBuffer,
        snap: &HashMapStoreSnapshot,
        scope_ids: &[EntityId],
    ) -> Result<(), RepositoryError> {
        let scope: std::collections::HashSet<EntityId> = scope_ids.iter().copied().collect();
        if scope.is_empty() {
            return Ok(());
        }
        let store = self.transaction.get_store();

        // External left keys whose ordered list references any scope id, in snapshot or live.
        let mut left_keys: std::collections::HashSet<EntityId> = std::collections::HashSet::new();
        for (left, rights) in snap.jn_work_from_root_works.iter() {
            if rights.iter().any(|rid| scope.contains(rid)) {
                left_keys.insert(*left);
            }
        }
        {
            let live_jn = store.jn_work_from_root_works.read().unwrap();
            for (left, rights) in live_jn.iter() {
                if rights.iter().any(|rid| scope.contains(rid)) {
                    left_keys.insert(*left);
                }
            }
        }

        for left in left_keys {
            let snap_list: Vec<EntityId> = snap
                .jn_work_from_root_works
                .get(&left)
                .cloned()
                .unwrap_or_default();
            let new_list = {
                let live_jn = store.jn_work_from_root_works.read().unwrap();
                let live_list: Vec<EntityId> = live_jn.get(&left).cloned().unwrap_or_default();
                let reconciled = crate::database::hashmap_store::reconcile_backref_list(
                    &live_list, &snap_list, &scope,
                );
                if reconciled == live_list {
                    None
                } else {
                    Some(reconciled)
                }
            };
            if let Some(reconciled) = new_list {
                store
                    .jn_work_from_root_works
                    .write()
                    .unwrap()
                    .insert(left, reconciled);
                event_buffer.push(Event {
                    origin: Origin::DirectAccess(DirectAccessEntity::Root(EntityEvent::Updated)),
                    ids: vec![left],
                    data: None,
                });
            }
        }
        Ok(())
    }
}

pub struct WorkRepositoryRO<'a> {
    table: Box<dyn WorkTableRO + 'a>,
}
impl<'a> WorkRepositoryRO<'a> {
    pub fn new(table: Box<dyn WorkTableRO + 'a>) -> Self {
        WorkRepositoryRO { table }
    }
    pub fn get(&self, id: &EntityId) -> Result<Option<Work>, RepositoryError> {
        self.table.get(id)
    }
    pub fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Work>>, RepositoryError> {
        self.table.get_multi(ids)
    }
    pub fn get_all(&self) -> Result<Vec<Work>, RepositoryError> {
        self.table.get_all()
    }
    pub fn get_relationship(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        self.table.get_relationship(id, field)
    }
    pub fn get_relationship_many(
        &self,
        ids: &[EntityId],
        field: &WorkRelationshipField,
    ) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>, RepositoryError> {
        self.table.get_relationship_many(ids, field)
    }
    pub fn get_relationship_count(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
    ) -> Result<usize, RepositoryError> {
        self.table.get_relationship_count(id, field)
    }
    pub fn get_relationship_in_range(
        &self,
        id: &EntityId,
        field: &WorkRelationshipField,
        offset: usize,
        limit: usize,
    ) -> Result<Vec<EntityId>, RepositoryError> {
        self.table
            .get_relationship_in_range(id, field, offset, limit)
    }
    pub fn get_relationships_from_right_ids(
        &self,
        field: &WorkRelationshipField,
        right_ids: &[EntityId],
    ) -> Result<Vec<(EntityId, Vec<EntityId>)>, RepositoryError> {
        self.table
            .get_relationships_from_right_ids(field, right_ids)
    }
}
