// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from entity_dtos.tera

use common::entities::NoteTemplate;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct NoteTemplateDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub body: String,
    pub starred: bool,
}

impl From<NoteTemplateDto> for NoteTemplate {
    fn from(dto: NoteTemplateDto) -> Self {
        NoteTemplate {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            body: dto.body,
            starred: dto.starred,
        }
    }
}

impl From<&NoteTemplateDto> for NoteTemplate {
    fn from(dto: &NoteTemplateDto) -> Self {
        NoteTemplate {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            body: dto.body.clone(),
            starred: dto.starred.clone(),
        }
    }
}

impl From<NoteTemplate> for NoteTemplateDto {
    fn from(entity: NoteTemplate) -> Self {
        NoteTemplateDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            body: entity.body,
            starred: entity.starred,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CreateNoteTemplateDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub body: String,
    pub starred: bool,
}

impl From<CreateNoteTemplateDto> for NoteTemplate {
    fn from(dto: CreateNoteTemplateDto) -> Self {
        NoteTemplate {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            body: dto.body,
            starred: dto.starred,
        }
    }
}

impl From<&CreateNoteTemplateDto> for NoteTemplate {
    fn from(dto: &CreateNoteTemplateDto) -> Self {
        NoteTemplate {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            body: dto.body.clone(),
            starred: dto.starred.clone(),
        }
    }
}

impl From<NoteTemplate> for CreateNoteTemplateDto {
    fn from(entity: NoteTemplate) -> Self {
        CreateNoteTemplateDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            body: entity.body,
            starred: entity.starred,
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct UpdateNoteTemplateDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub name: String,
    pub body: String,
    pub starred: bool,
}

impl From<UpdateNoteTemplateDto> for NoteTemplate {
    fn from(dto: UpdateNoteTemplateDto) -> Self {
        NoteTemplate {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            body: dto.body,
            starred: dto.starred,
        }
    }
}

impl From<&UpdateNoteTemplateDto> for NoteTemplate {
    fn from(dto: &UpdateNoteTemplateDto) -> Self {
        NoteTemplate {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            name: dto.name.clone(),
            body: dto.body.clone(),
            starred: dto.starred.clone(),
        }
    }
}

impl From<NoteTemplate> for UpdateNoteTemplateDto {
    fn from(entity: NoteTemplate) -> Self {
        UpdateNoteTemplateDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            name: entity.name,
            body: entity.body,
            starred: entity.starred,
        }
    }
}

impl From<NoteTemplateDto> for UpdateNoteTemplateDto {
    fn from(dto: NoteTemplateDto) -> Self {
        UpdateNoteTemplateDto {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            name: dto.name,
            body: dto.body,
            starred: dto.starred,
        }
    }
}
