// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.7.4 from feature_use_case_uow.tera
// Modify-and-protect scaffold: don't blanket-regenerate. Hand-added the
// `write_guard` field/acquire (see `begin_transaction` below) — this write
// transaction is reachable from a live UI action and must be covered by
// `common::database::write_guard`'s process-wide single-writer invariant.
// See that module's doc for the full rationale.

use crate::use_cases::empty_trash_uc::{
    EmptyTrashUnitOfWorkFactoryTrait, EmptyTrashUnitOfWorkTrait,
};
use anyhow::{Ok, Result};
use common::database::CommandUnitOfWork;
use common::database::write_guard::WriteTransactionGuard;
use common::database::{db_context::DbContext, transactions::Transaction};
#[allow(unused_imports)]
use common::entities::{Binder, BinderItem, Content, TrashInfo, Work};
use common::event::TrashManagementEvent::EmptyTrash;
use common::event::{AllEvent, DirectAccessEntity, Event, EventBuffer, EventHub, Origin};
#[allow(unused_imports)]
use common::types;
#[allow(unused_imports)]
use common::types::EntityId;
use std::cell::RefCell;
use std::sync::Arc;

// Unit of work for EmptyTrash

pub struct EmptyTrashUnitOfWork {
    context: DbContext,
    transaction: Option<Transaction>,
    // RAII: acquired in `begin_transaction`, released via `commit`/`rollback`
    // falling out of scope alongside `transaction` — see
    // `common::database::write_guard`'s module doc.
    write_guard: Option<WriteTransactionGuard>,
    event_hub: Arc<EventHub>,
    event_buffer: RefCell<EventBuffer>,
}

impl EmptyTrashUnitOfWork {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        EmptyTrashUnitOfWork {
            context: db_context.clone(),
            transaction: None,
            write_guard: None,
            event_hub: event_hub.clone(),
            event_buffer: RefCell::new(EventBuffer::new()),
        }
    }
}

impl CommandUnitOfWork for EmptyTrashUnitOfWork {
    fn begin_transaction(&mut self) -> Result<()> {
        // Acquire BEFORE the write transaction itself — see
        // `common::database::write_guard`'s module doc for why this call must
        // stay UI-thread-synchronous unless given a real off-thread gate.
        self.write_guard = Some(WriteTransactionGuard::acquire(&self.context, "empty_trash")?);
        self.transaction = Some(Transaction::begin_write_transaction(&self.context)?);
        self.event_buffer.get_mut().begin_buffering();
        Ok(())
    }

    fn commit(&mut self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .commit()?;
        self.write_guard = None;
        for event in self.event_buffer.get_mut().flush() {
            self.event_hub.send_event(event);
        }
        Ok(())
    }

    fn rollback(&mut self) -> Result<()> {
        self.transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .rollback()?;
        self.write_guard = None;
        self.event_buffer.get_mut().discard();
        Ok(())
    }

    fn create_savepoint(&self) -> Result<types::Savepoint> {
        self.transaction
            .as_ref()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?
            .create_savepoint()
    }

    fn restore_to_savepoint(&mut self, savepoint: types::Savepoint) -> Result<()> {
        let mut transaction = self
            .transaction
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active transaction"))?;
        transaction.restore_to_savepoint(savepoint)?;

        // Discard buffered events — savepoint restore invalidated them
        self.event_buffer.get_mut().discard();

        // Send Reset immediately (not buffered — UI must refresh now)
        self.event_hub.send_event(Event {
            origin: Origin::DirectAccess(DirectAccessEntity::All(AllEvent::Reset)),
            ids: vec![],
            data: None,
        });

        // Recreate the transaction after restoring to savepoint
        self.transaction = Some(transaction);

        Ok(())
    }
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti, Snapshot, Restore
//
// You have here a read-write unit of work.
//
// RO means Read Only, so *RO actions should not used be here.
// Don't forget to set thread_safe = true for long operation's unit of work.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../use_cases/empty_trash_uc.rs
//
#[macros::uow_action(entity = "TrashInfo", action = "GetRelationship")]
#[macros::uow_action(entity = "TrashInfo", action = "RemoveMulti")]
#[macros::uow_action(entity = "Work", action = "GetAll")]
#[macros::uow_action(entity = "Work", action = "GetRelationship")]
#[macros::uow_action(entity = "Work", action = "SetRelationship")]
#[macros::uow_action(entity = "Work", action = "Snapshot")]
#[macros::uow_action(entity = "Work", action = "Restore")]
#[macros::uow_action(entity = "Binder", action = "GetRelationship")]
#[macros::uow_action(entity = "Binder", action = "GetRelationshipsFromRightIds")]
#[macros::uow_action(entity = "Binder", action = "SetRelationship")]
#[macros::uow_action(entity = "Binder", action = "RemoveMulti")]
#[macros::uow_action(entity = "BinderItem", action = "GetMulti")]
#[macros::uow_action(entity = "BinderItem", action = "GetRelationship")]
#[macros::uow_action(entity = "BinderItem", action = "RemoveMulti")]
#[macros::uow_action(entity = "Content", action = "RemoveMulti")]
impl EmptyTrashUnitOfWorkTrait for EmptyTrashUnitOfWork {
    fn publish_empty_trash_event(&self, ids: Vec<EntityId>, data: Option<String>) {
        self.event_hub.send_event(Event {
            origin: Origin::TrashManagement(EmptyTrash),
            ids,
            data,
        });
    }
}

pub struct EmptyTrashUnitOfWorkFactory {
    context: DbContext,
    event_hub: Arc<EventHub>,
}

impl EmptyTrashUnitOfWorkFactory {
    pub fn new(db_context: &DbContext, event_hub: &Arc<EventHub>) -> Self {
        EmptyTrashUnitOfWorkFactory {
            context: db_context.clone(),
            event_hub: event_hub.clone(),
        }
    }
}

impl EmptyTrashUnitOfWorkFactoryTrait for EmptyTrashUnitOfWorkFactory {
    fn create(&self) -> Box<dyn EmptyTrashUnitOfWorkTrait> {
        Box::new(EmptyTrashUnitOfWork::new(&self.context, &self.event_hub))
    }
}
