// Generated by Qleany v1.8.0 from feature_use_case.tera
use crate::RestoreItemsDto;
use crate::RestoreResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{Binder, BinderItem, Content, System, TrashInfo};
use common::types::EntityId;

pub trait RestoreItemsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn RestoreItemsUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/restore_items_uow.rs
//
#[macros::uow_action(entity = "System", action = "Get")]
#[macros::uow_action(entity = "System", action = "GetMulti")]
#[macros::uow_action(entity = "System", action = "Snapshot")]
#[macros::uow_action(entity = "System", action = "Restore")]
#[macros::uow_action(entity = "TrashInfo", action = "Get")]
#[macros::uow_action(entity = "TrashInfo", action = "GetMulti")]
#[macros::uow_action(entity = "TrashInfo", action = "Snapshot")]
#[macros::uow_action(entity = "TrashInfo", action = "Restore")]
#[macros::uow_action(entity = "Binder", action = "Get")]
#[macros::uow_action(entity = "Binder", action = "GetMulti")]
#[macros::uow_action(entity = "Binder", action = "Snapshot")]
#[macros::uow_action(entity = "Binder", action = "Restore")]
#[macros::uow_action(entity = "BinderItem", action = "Get")]
#[macros::uow_action(entity = "BinderItem", action = "GetMulti")]
#[macros::uow_action(entity = "BinderItem", action = "Snapshot")]
#[macros::uow_action(entity = "BinderItem", action = "Restore")]
#[macros::uow_action(entity = "Content", action = "Get")]
#[macros::uow_action(entity = "Content", action = "GetMulti")]
#[macros::uow_action(entity = "Content", action = "Snapshot")]
#[macros::uow_action(entity = "Content", action = "Restore")]
pub trait RestoreItemsUnitOfWorkTrait: CommandUnitOfWork {
    fn publish_restore_items_event(&self, ids: Vec<EntityId>, data: Option<String>);
}

pub struct RestoreItemsUseCase {
    uow_factory: Box<dyn RestoreItemsUnitOfWorkFactoryTrait>,
}

impl RestoreItemsUseCase {
    pub fn new(uow_factory: Box<dyn RestoreItemsUnitOfWorkFactoryTrait>) -> Self {
        RestoreItemsUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &RestoreItemsDto) -> Result<RestoreResultDto> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: RestoreItemsUseCase to be implemented
        unimplemented!("RestoreItemsUseCase unimplemented");
        uow.commit()?;

        uow.publish_restore_items_event(vec![], None);
        //Ok(RestoreResultDto {
        //
        //})
        // placeholder to allow compilation
        Err(anyhow!("Not implemented"))
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for RestoreItemsUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: RestoreItemsUseCase  undo to be implemented
        unimplemented!("RestoreItemsUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: RestoreItemsUseCase  redo to be implemented
        unimplemented!("RestoreItemsUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
