// Generated by Qleany v1.8.0 from feature_use_case.tera
use crate::TrashBinderItemsDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::entities::{BinderItem, Content, System, TrashInfo};
use common::types::EntityId;

pub trait TrashBinderItemsUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn TrashBinderItemsUnitOfWorkTrait>;
}

//TODO: adapt entities and actions to real use :
// Create, CreateMulti, Get, GetMulti, Update (scalar-only), UpdateMulti (scalar-only),
// UpdateWithRelationships, UpdateWithRelationshipsMulti,
// Remove, RemoveMulti, GetRelationship, GetRelationshipsFromRightIds,
// SetRelationship, SetRelationshipMulti
//
// You have here a read-write unit of work trait.
//
// RO means Read Only.
// Do not mix read-only and write actions in the same unit of work.
//
// Exactly the same macros must be set in the use case uow trait file in ../units_of_work/trash_binder_items_uow.rs
//
#[macros::uow_action(entity = "System", action = "Get")]
#[macros::uow_action(entity = "System", action = "GetMulti")]
#[macros::uow_action(entity = "System", action = "Snapshot")]
#[macros::uow_action(entity = "System", action = "Restore")]
#[macros::uow_action(entity = "TrashInfo", action = "Get")]
#[macros::uow_action(entity = "TrashInfo", action = "GetMulti")]
#[macros::uow_action(entity = "TrashInfo", action = "Snapshot")]
#[macros::uow_action(entity = "TrashInfo", action = "Restore")]
#[macros::uow_action(entity = "BinderItem", action = "Get")]
#[macros::uow_action(entity = "BinderItem", action = "GetMulti")]
#[macros::uow_action(entity = "BinderItem", action = "Snapshot")]
#[macros::uow_action(entity = "BinderItem", action = "Restore")]
#[macros::uow_action(entity = "Content", action = "Get")]
#[macros::uow_action(entity = "Content", action = "GetMulti")]
#[macros::uow_action(entity = "Content", action = "Snapshot")]
#[macros::uow_action(entity = "Content", action = "Restore")]
pub trait TrashBinderItemsUnitOfWorkTrait: CommandUnitOfWork {
    fn publish_trash_binder_items_event(&self, ids: Vec<EntityId>, data: Option<String>);
}

pub struct TrashBinderItemsUseCase {
    uow_factory: Box<dyn TrashBinderItemsUnitOfWorkFactoryTrait>,
}

impl TrashBinderItemsUseCase {
    pub fn new(uow_factory: Box<dyn TrashBinderItemsUnitOfWorkFactoryTrait>) -> Self {
        TrashBinderItemsUseCase { uow_factory }
    }

    pub fn execute(&mut self, dto: &TrashBinderItemsDto) -> Result<()> {
        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        //TODO: TrashBinderItemsUseCase to be implemented
        unimplemented!("TrashBinderItemsUseCase unimplemented");
        uow.commit()?;

        uow.publish_trash_binder_items_event(vec![], None);
        Ok(())
    }
}
use common::undo_redo::UndoRedoCommand;
use std::any::Any;
impl UndoRedoCommand for TrashBinderItemsUseCase {
    fn undo(&mut self) -> Result<()> {
        //TODO: TrashBinderItemsUseCase  undo to be implemented
        unimplemented!("TrashBinderItemsUseCase undo unimplemented");

        Ok(())
    }

    fn redo(&mut self) -> Result<()> {
        //TODO: TrashBinderItemsUseCase  redo to be implemented
        unimplemented!("TrashBinderItemsUseCase redo unimplemented");

        Ok(())
    }
    fn as_any(&self) -> &dyn Any {
        self
    }
}
