// Generated by Qleany v1.4.2 from entity_table_h.tera
#pragma once

#include "database/db_context.h"
#include "database/snapshot_types.h"
#include "direct_access/dict_word/dict_word_repository.h"
#include "entities/dict_word.h"

#include <QList>

namespace Skribisto::Common::DirectAccess::DictWord
{
namespace SCE = Skribisto::Common::Entities;

class DictWordTable final : public IDictWordTable
{
  public:
    explicit DictWordTable(Database::DbSubContext &dbSubContext);

    QList<SCE::DictWord> createMany(const QList<SCE::DictWord> &dictWords) override;
    QList<SCE::DictWord> updateMany(const QList<SCE::DictWord> &dictWords) override;
    [[nodiscard]] QList<SCE::DictWord> findMany(const QList<int> &ids) const override;
    [[nodiscard]] QList<SCE::DictWord> findAll() const override;
    QList<int> removeMany(const QList<int> &ids) override;
    void setRelationshipIds(int dictWordId, DictWordRelationshipField relationship, QList<int> relatedId) override;
    [[nodiscard]] QHash<int, QList<int>> getRelationshipIdsMany(const QList<int> &dictWordIds,
                                                                DictWordRelationshipField relationship) const override;
    int getRelationshipIdsCount(int rootId, DictWordRelationshipField relationship) const override;
    QList<int> getRelationshipIdsInRange(int rootId, DictWordRelationshipField relationship, int offset,
                                         int limit) const override;
    QList<int> moveRelationshipIds(int dictWordId, DictWordRelationshipField relationship, const QList<int> &idsToMove,
                                   int newIndex) override;

    // Snapshot / Restore (table level)
    Database::TableLevelSnapshot snapshotRows(const QList<int> &ids) override;
    void restoreRows(const Database::TableLevelSnapshot &snap) override;
    [[nodiscard]] QList<int> getOwnerIds(const QList<int> &childIds) const override;

  private:
    Database::DbSubContext &m_dbSubContext;
};

} // namespace Skribisto::Common::DirectAccess::DictWord
