// Generated by Qleany v1.6.1 from entity_repository_h.tera
#pragma once

#include "database/db_context.h"
#include "database/snapshot_types.h"
#include "direct_access/dict_word/dict_word_events.h"
#include "direct_access/dict_word/i_dict_word_repository.h"
#include "direct_access/event_registry.h"
#include "entities/dict_word.h"
#include "signal_buffer.h"
#include <QPointer>

namespace Skribisto::Common::DirectAccess::DictWord
{
namespace SCE = Skribisto::Common::Entities;

class IDictWordTable
{
  public:
    virtual ~IDictWordTable() = default;

    // Creation assigns new ids
    virtual QList<SCE::DictWord> createMany(const QList<SCE::DictWord> &dictWords) = 0;

    // Update
    virtual QList<SCE::DictWord> updateMany(const QList<SCE::DictWord> &dictWords) = 0;
    virtual QList<SCE::DictWord> updateWithRelationshipsMany(const QList<SCE::DictWord> &dictWords) = 0;

    // Query/Delete
    [[nodiscard]] virtual QList<SCE::DictWord> findMany(const QList<int> &ids) const = 0;
    [[nodiscard]] virtual QList<SCE::DictWord> findAll() const = 0;
    virtual QList<int> removeMany(const QList<int> &ids) = 0;
    // Relationship setters/getters
    // Set the relationship value for a given DictWord id
    virtual void setRelationshipIds(int dictWordId, DictWordRelationshipField relationship, QList<int> relatedId) = 0;

    // Get the relationship value for a given DictWord id
    [[nodiscard]] virtual QHash<int, QList<int>> getRelationshipIdsMany(
        const QList<int> &dictWordIds, DictWordRelationshipField relationship) const = 0;
    virtual int getRelationshipIdsCount(int rootId, DictWordRelationshipField relationship) const = 0;
    virtual QList<int> getRelationshipIdsInRange(int rootId, DictWordRelationshipField relationship, int offset,
                                                 int limit) const = 0;

    // Move specific related IDs to a new position (only meaningful for ordered relationships)
    virtual QList<int> moveRelationshipIds(int dictWordId, DictWordRelationshipField relationship,
                                           const QList<int> &idsToMove, int newIndex) = 0;

    // Snapshot / Restore (table level)
    virtual Database::TableLevelSnapshot snapshotRows(const QList<int> &ids) = 0;
    virtual void restoreRows(const Database::TableLevelSnapshot &snap) = 0;
    // Reverse lookup: find owner IDs that reference the given child IDs via the owner junction
    [[nodiscard]] virtual QList<int> getOwnerIds(const QList<int> &childIds) const = 0;
};

class DictWordRepository : public IDictWordRepository
{
  public:
    DictWordRepository(std::unique_ptr<IDictWordTable> table, Database::DbSubContext &dbSubContext,
                       QPointer<EventRegistry> eventRegistry, QPointer<Common::SignalBuffer> signalBuffer);

    ~DictWordRepository() override = default;

    // CRUD
    QList<SCE::DictWord> createOrphans(const QList<SCE::DictWord> &dictWords) override;
    QList<SCE::DictWord> create(const QList<SCE::DictWord> &dictWords, int ownerId, int index) override;
    QList<int> getRelationshipsFromOwner(int ownerId) const override;
    void setRelationshipsInOwner(const QList<int> &itemIds, int ownerId) override;
    QList<SCE::DictWord> get(const QList<int> &dictWordIds) const override;
    QList<SCE::DictWord> getAll() const override;
    QList<SCE::DictWord> update(const QList<SCE::DictWord> &dictWords) override;
    QList<SCE::DictWord> updateWithRelationships(const QList<SCE::DictWord> &dictWords) override;
    QList<int> remove(const QList<int> &dictWordIds) override;

    // Snapshot / Restore
    Database::EntityTreeSnapshot snapshot(const QList<int> &ids) override;
    void restore(const Database::EntityTreeSnapshot &snap) override;

  private:
    std::unique_ptr<IDictWordTable> m_table;
    QPointer<DictWordEvents> m_events;             // not owned
    QPointer<EventRegistry> m_eventRegistry;       // not owned
    QPointer<Common::SignalBuffer> m_signalBuffer; // not owned

    // For cascade operations
    Database::DbSubContext &m_dbSubContext;

    void emitCreated(const QList<int> &ids) const;
    void emitUpdated(const QList<int> &ids) const;
    void emitRemoved(const QList<int> &ids) const;
};

} // namespace Skribisto::Common::DirectAccess::DictWord
