// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from frontend_feature_commands.tera

//! HandlingAppLifecycle feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use handling_app_lifecycle::{InitializeAppResultDto, handling_app_lifecycle_controller};

pub fn initialize_app(ctx: &AppContext) -> Result<InitializeAppResultDto> {
    handling_app_lifecycle_controller::initialize_app(&ctx.db_context, &ctx.event_hub)
        .context("initialize_app")
}

pub fn clean_up_before_exit(ctx: &AppContext) -> Result<()> {
    handling_app_lifecycle_controller::clean_up_before_exit(&ctx.db_context, &ctx.event_hub)
        .context("clean_up_before_exit")
}
