// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from frontend_entity_commands.tera

//! Milestone entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::direct_access::milestone::MilestoneRelationshipField;
use common::types::EntityId;
use direct_access::MilestoneRelationshipDto;
use direct_access::{CreateMilestoneDto, MilestoneDto, UpdateMilestoneDto, milestone_controller};

/// Create a new milestone entity (orphan, no parent)
pub fn create_orphan_milestone(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateMilestoneDto,
) -> Result<MilestoneDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating milestone")
}
/// Create a new milestone entity as child of owner
pub fn create_milestone(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateMilestoneDto,
    owner_id: EntityId,
    index: i32,
) -> Result<MilestoneDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating milestone")
}
/// Create multiple milestone entities (orphan, no parent)
pub fn create_orphan_milestone_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateMilestoneDto],
) -> Result<Vec<MilestoneDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating milestone entities")
}
/// Create multiple milestone entities as children of owner
pub fn create_milestone_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateMilestoneDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<MilestoneDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating milestone entities")
}
/// Get a milestone entity by ID
pub fn get_milestone(ctx: &AppContext, id: &EntityId) -> Result<Option<MilestoneDto>> {
    milestone_controller::get(&ctx.db_context, id).context("getting milestone")
}

/// Get multiple milestone entities by IDs
pub fn get_milestone_multi(
    ctx: &AppContext,
    ids: &[EntityId],
) -> Result<Vec<Option<MilestoneDto>>> {
    milestone_controller::get_multi(&ctx.db_context, ids).context("getting milestone entities")
}

/// Get all milestone entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_milestone(ctx: &AppContext) -> Result<Vec<MilestoneDto>> {
    milestone_controller::get_all(&ctx.db_context).context("getting all milestone entities")
}

/// Update a milestone entity
pub fn update_milestone(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdateMilestoneDto,
) -> Result<MilestoneDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating milestone")
}

/// Update multiple milestone entities
pub fn update_milestone_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdateMilestoneDto],
) -> Result<Vec<MilestoneDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating milestone entities")
}

/// Update a milestone entity with relationships
pub fn update_milestone_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &MilestoneDto,
) -> Result<MilestoneDto> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating milestone with relationships")
}

/// Update multiple milestone entities with relationships
pub fn update_milestone_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[MilestoneDto],
) -> Result<Vec<MilestoneDto>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating milestone entities with relationships")
}

/// Remove a milestone entity by ID
pub fn remove_milestone(ctx: &AppContext, stack_id: Option<u64>, id: &EntityId) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing milestone")
}

/// Remove multiple milestone entities by IDs
pub fn remove_milestone_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing milestone entities")
}

/// Get a milestone relationship
pub fn get_milestone_relationship(
    ctx: &AppContext,
    id: &EntityId,
    field: &MilestoneRelationshipField,
) -> Result<Vec<EntityId>> {
    milestone_controller::get_relationship(&ctx.db_context, id, field)
        .context("getting milestone relationship")
}

/// Get relationship IDs for multiple milestone entities at once
pub fn get_milestone_relationship_many(
    ctx: &AppContext,
    ids: &[EntityId],
    field: &MilestoneRelationshipField,
) -> Result<std::collections::HashMap<EntityId, Vec<EntityId>>> {
    milestone_controller::get_relationship_many(&ctx.db_context, ids, field)
        .context("getting milestone relationships (many)")
}

/// Get relationship count for a milestone entity
pub fn get_milestone_relationship_count(
    ctx: &AppContext,
    id: &EntityId,
    field: &MilestoneRelationshipField,
) -> Result<usize> {
    milestone_controller::get_relationship_count(&ctx.db_context, id, field)
        .context("getting milestone relationship count")
}

/// Get relationship IDs for a milestone entity with pagination
pub fn get_milestone_relationship_in_range(
    ctx: &AppContext,
    id: &EntityId,
    field: &MilestoneRelationshipField,
    offset: usize,
    limit: usize,
) -> Result<Vec<EntityId>> {
    milestone_controller::get_relationship_in_range(&ctx.db_context, id, field, offset, limit)
        .context("getting milestone relationship range")
}

/// Set a milestone relationship
pub fn set_milestone_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &MilestoneRelationshipDto,
) -> Result<()> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::set_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("setting milestone relationship")
}

/// Move (reorder) IDs within a milestone relationship
pub fn move_milestone_relationship(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
    field: &MilestoneRelationshipField,
    ids_to_move: &[EntityId],
    new_index: i32,
) -> Result<Vec<EntityId>> {
    let mut undo_redo_manager = ctx.undo_redo_manager.lock().unwrap();
    milestone_controller::move_relationship(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
        field,
        ids_to_move,
        new_index,
    )
    .context("moving milestone relationship")
}
