// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from frontend_feature_commands.tera

//! ProgressManagement feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use progress_management::{
    RecordProgressSnapshotDto, WordCountResultDto, progress_management_controller,
};

use common::long_operation::OperationProgress;

/// count_words (long operation)
pub fn count_words(ctx: &AppContext) -> Result<String> {
    progress_management_controller::count_words(
        &ctx.db_context,
        &ctx.event_hub,
        &mut ctx.long_operation_manager.lock().unwrap(),
    )
    .context("count_words")
}

/// Get the progress of a count_words operation
pub fn get_count_words_progress(ctx: &AppContext, operation_id: &str) -> Option<OperationProgress> {
    progress_management_controller::get_count_words_progress(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
}

/// Get the result of a count_words operation
pub fn get_count_words_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<WordCountResultDto>> {
    progress_management_controller::get_count_words_result(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
    .context("getting count_words result")
}

pub fn record_progress_snapshot(ctx: &AppContext, dto: &RecordProgressSnapshotDto) -> Result<()> {
    progress_management_controller::record_progress_snapshot(&ctx.db_context, &ctx.event_hub, dto)
        .context("record_progress_snapshot")
}
