// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from frontend_entity_commands.tera

//! ProgressSnapshot entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::types::EntityId;
use direct_access::{
    CreateProgressSnapshotDto, ProgressSnapshotDto, UpdateProgressSnapshotDto,
    progress_snapshot_controller,
};

/// Create a new progress_snapshot entity (orphan, no parent)
pub fn create_orphan_progress_snapshot(
    ctx: &AppContext,

    dto: &CreateProgressSnapshotDto,
) -> Result<ProgressSnapshotDto> {
    progress_snapshot_controller::create_orphan(&ctx.db_context, &ctx.event_hub, dto)
        .context("creating progress_snapshot")
}
/// Create a new progress_snapshot entity as child of owner
pub fn create_progress_snapshot(
    ctx: &AppContext,

    dto: &CreateProgressSnapshotDto,
    owner_id: EntityId,
    index: i32,
) -> Result<ProgressSnapshotDto> {
    progress_snapshot_controller::create(&ctx.db_context, &ctx.event_hub, dto, owner_id, index)
        .context("creating progress_snapshot")
}
/// Create multiple progress_snapshot entities (orphan, no parent)
pub fn create_orphan_progress_snapshot_multi(
    ctx: &AppContext,

    dtos: &[CreateProgressSnapshotDto],
) -> Result<Vec<ProgressSnapshotDto>> {
    progress_snapshot_controller::create_orphan_multi(&ctx.db_context, &ctx.event_hub, dtos)
        .context("creating progress_snapshot entities")
}
/// Create multiple progress_snapshot entities as children of owner
pub fn create_progress_snapshot_multi(
    ctx: &AppContext,

    dtos: &[CreateProgressSnapshotDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<ProgressSnapshotDto>> {
    progress_snapshot_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        dtos,
        owner_id,
        index,
    )
    .context("creating progress_snapshot entities")
}
/// Get a progress_snapshot entity by ID
pub fn get_progress_snapshot(
    ctx: &AppContext,
    id: &EntityId,
) -> Result<Option<ProgressSnapshotDto>> {
    progress_snapshot_controller::get(&ctx.db_context, id).context("getting progress_snapshot")
}

/// Get multiple progress_snapshot entities by IDs
pub fn get_progress_snapshot_multi(
    ctx: &AppContext,
    ids: &[EntityId],
) -> Result<Vec<Option<ProgressSnapshotDto>>> {
    progress_snapshot_controller::get_multi(&ctx.db_context, ids)
        .context("getting progress_snapshot entities")
}

/// Get all progress_snapshot entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_progress_snapshot(ctx: &AppContext) -> Result<Vec<ProgressSnapshotDto>> {
    progress_snapshot_controller::get_all(&ctx.db_context)
        .context("getting all progress_snapshot entities")
}

/// Update a progress_snapshot entity
pub fn update_progress_snapshot(
    ctx: &AppContext,

    dto: &UpdateProgressSnapshotDto,
) -> Result<ProgressSnapshotDto> {
    progress_snapshot_controller::update(&ctx.db_context, &ctx.event_hub, dto)
        .context("updating progress_snapshot")
}

/// Update multiple progress_snapshot entities
pub fn update_progress_snapshot_multi(
    ctx: &AppContext,

    dtos: &[UpdateProgressSnapshotDto],
) -> Result<Vec<ProgressSnapshotDto>> {
    progress_snapshot_controller::update_multi(&ctx.db_context, &ctx.event_hub, dtos)
        .context("updating progress_snapshot entities")
}

/// Update a progress_snapshot entity with relationships
pub fn update_progress_snapshot_with_relationships(
    ctx: &AppContext,

    dto: &ProgressSnapshotDto,
) -> Result<ProgressSnapshotDto> {
    progress_snapshot_controller::update_with_relationships(&ctx.db_context, &ctx.event_hub, dto)
        .context("updating progress_snapshot with relationships")
}

/// Update multiple progress_snapshot entities with relationships
pub fn update_progress_snapshot_with_relationships_multi(
    ctx: &AppContext,

    dtos: &[ProgressSnapshotDto],
) -> Result<Vec<ProgressSnapshotDto>> {
    progress_snapshot_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        dtos,
    )
    .context("updating progress_snapshot entities with relationships")
}

/// Remove a progress_snapshot entity by ID
pub fn remove_progress_snapshot(ctx: &AppContext, id: &EntityId) -> Result<()> {
    progress_snapshot_controller::remove(&ctx.db_context, &ctx.event_hub, id)
        .context("removing progress_snapshot")
}

/// Remove multiple progress_snapshot entities by IDs
pub fn remove_progress_snapshot_multi(ctx: &AppContext, ids: &[EntityId]) -> Result<()> {
    progress_snapshot_controller::remove_multi(&ctx.db_context, &ctx.event_hub, ids)
        .context("removing progress_snapshot entities")
}
