// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.9.0 from frontend_entity_commands.tera

//! SmartPunctuation entity commands
#![allow(unused_imports, dead_code)]

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use common::types::EntityId;
use direct_access::{
    CreateSmartPunctuationDto, SmartPunctuationDto, UpdateSmartPunctuationDto,
    smart_punctuation_controller,
};

/// Create a new smart_punctuation entity (orphan, no parent)
pub fn create_orphan_smart_punctuation(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateSmartPunctuationDto,
) -> Result<SmartPunctuationDto> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::create_orphan(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("creating smart_punctuation")
}
/// Create a new smart_punctuation entity as child of owner
pub fn create_smart_punctuation(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &CreateSmartPunctuationDto,
    owner_id: EntityId,
    index: i32,
) -> Result<SmartPunctuationDto> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::create(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
        owner_id,
        index,
    )
    .context("creating smart_punctuation")
}
/// Create multiple smart_punctuation entities (orphan, no parent)
pub fn create_orphan_smart_punctuation_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateSmartPunctuationDto],
) -> Result<Vec<SmartPunctuationDto>> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::create_orphan_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("creating smart_punctuation entities")
}
/// Create multiple smart_punctuation entities as children of owner
pub fn create_smart_punctuation_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[CreateSmartPunctuationDto],
    owner_id: EntityId,
    index: i32,
) -> Result<Vec<SmartPunctuationDto>> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::create_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
        owner_id,
        index,
    )
    .context("creating smart_punctuation entities")
}
/// Get a smart_punctuation entity by ID
pub fn get_smart_punctuation(
    ctx: &AppContext,
    id: &EntityId,
) -> Result<Option<SmartPunctuationDto>> {
    smart_punctuation_controller::get(&ctx.db_context, id).context("getting smart_punctuation")
}

/// Get multiple smart_punctuation entities by IDs
pub fn get_smart_punctuation_multi(
    ctx: &AppContext,
    ids: &[EntityId],
) -> Result<Vec<Option<SmartPunctuationDto>>> {
    smart_punctuation_controller::get_multi(&ctx.db_context, ids)
        .context("getting smart_punctuation entities")
}

/// Get all smart_punctuation entities.
/// Note: returns entities in database key order (by EntityId), not insertion order
/// or any user-defined sort. For ordered collections, use relationship-based
/// retrieval (e.g. get_*_relationship for ordered_one_to_many fields).
pub fn get_all_smart_punctuation(ctx: &AppContext) -> Result<Vec<SmartPunctuationDto>> {
    smart_punctuation_controller::get_all(&ctx.db_context)
        .context("getting all smart_punctuation entities")
}

/// Update a smart_punctuation entity
pub fn update_smart_punctuation(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &UpdateSmartPunctuationDto,
) -> Result<SmartPunctuationDto> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::update(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating smart_punctuation")
}

/// Update multiple smart_punctuation entities
pub fn update_smart_punctuation_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[UpdateSmartPunctuationDto],
) -> Result<Vec<SmartPunctuationDto>> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::update_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating smart_punctuation entities")
}

/// Update a smart_punctuation entity with relationships
pub fn update_smart_punctuation_with_relationships(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dto: &SmartPunctuationDto,
) -> Result<SmartPunctuationDto> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::update_with_relationships(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dto,
    )
    .context("updating smart_punctuation with relationships")
}

/// Update multiple smart_punctuation entities with relationships
pub fn update_smart_punctuation_with_relationships_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    dtos: &[SmartPunctuationDto],
) -> Result<Vec<SmartPunctuationDto>> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::update_with_relationships_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        dtos,
    )
    .context("updating smart_punctuation entities with relationships")
}

/// Remove a smart_punctuation entity by ID
pub fn remove_smart_punctuation(
    ctx: &AppContext,
    stack_id: Option<u64>,
    id: &EntityId,
) -> Result<()> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::remove(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        id,
    )
    .context("removing smart_punctuation")
}

/// Remove multiple smart_punctuation entities by IDs
pub fn remove_smart_punctuation_multi(
    ctx: &AppContext,
    stack_id: Option<u64>,
    ids: &[EntityId],
) -> Result<()> {
    let mut undo_redo_manager = common::long_operation::lock_or_recover(&ctx.undo_redo_manager);
    smart_punctuation_controller::remove_multi(
        &ctx.db_context,
        &ctx.event_hub,
        &mut undo_redo_manager,
        stack_id,
        ids,
    )
    .context("removing smart_punctuation entities")
}