// Generated by Qleany v1.7.4 from frontend_feature_commands.tera

//! WorkManagement feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use work_management::{LoadWorkDto, NewWorkDto, SaveWorkDto, work_management_controller};

pub fn load_work(ctx: &AppContext, dto: &LoadWorkDto) -> Result<()> {
    work_management_controller::load_work(&ctx.db_context, &ctx.event_hub, dto).context("load_work")
}

pub fn save_work(ctx: &AppContext, dto: &SaveWorkDto) -> Result<()> {
    work_management_controller::save_work(&ctx.db_context, &ctx.event_hub, dto).context("save_work")
}

pub fn close_work(ctx: &AppContext) -> Result<()> {
    work_management_controller::close_work(&ctx.db_context, &ctx.event_hub).context("close_work")
}

pub fn new_work(ctx: &AppContext, dto: &NewWorkDto) -> Result<()> {
    work_management_controller::new_work(&ctx.db_context, &ctx.event_hub, dto).context("new_work")
}
