// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from frontend_feature_commands.tera

//! WorkManagement feature commands

use crate::app_context::AppContext;
use anyhow::{Context, Result};
use work_management::{
    BackupNowDto, BackupResultDto, LoadWorkDto, NewWorkDto, SaveAsDto, SaveAsResultDto,
    SaveResultDto, SaveWorkDto, work_management_controller,
};

use common::long_operation::OperationProgress;

pub fn load_work(ctx: &AppContext, dto: &LoadWorkDto) -> Result<()> {
    work_management_controller::load_work(&ctx.db_context, &ctx.event_hub, dto).context("load_work")
}

/// save_work (long operation)
pub fn save_work(ctx: &AppContext, dto: &SaveWorkDto) -> Result<String> {
    work_management_controller::save_work(
        &ctx.db_context,
        &ctx.event_hub,
        &mut ctx.long_operation_manager.lock().unwrap(),
        dto,
    )
    .context("save_work")
}

/// Get the progress of a save_work operation
pub fn get_save_work_progress(ctx: &AppContext, operation_id: &str) -> Option<OperationProgress> {
    work_management_controller::get_save_work_progress(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
}

/// Get the result of a save_work operation
pub fn get_save_work_result(ctx: &AppContext, operation_id: &str) -> Result<Option<SaveResultDto>> {
    work_management_controller::get_save_work_result(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
    .context("getting save_work result")
}

/// save_as (long operation)
pub fn save_as(ctx: &AppContext, dto: &SaveAsDto) -> Result<String> {
    work_management_controller::save_as(
        &ctx.db_context,
        &ctx.event_hub,
        &mut ctx.long_operation_manager.lock().unwrap(),
        dto,
    )
    .context("save_as")
}

/// Get the progress of a save_as operation
pub fn get_save_as_progress(ctx: &AppContext, operation_id: &str) -> Option<OperationProgress> {
    work_management_controller::get_save_as_progress(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
}

/// Get the result of a save_as operation
pub fn get_save_as_result(ctx: &AppContext, operation_id: &str) -> Result<Option<SaveAsResultDto>> {
    work_management_controller::get_save_as_result(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
    .context("getting save_as result")
}

/// backup_now (long operation)
pub fn backup_now(ctx: &AppContext, dto: &BackupNowDto) -> Result<String> {
    work_management_controller::backup_now(
        &ctx.db_context,
        &ctx.event_hub,
        &mut ctx.long_operation_manager.lock().unwrap(),
        dto,
    )
    .context("backup_now")
}

/// Get the progress of a backup_now operation
pub fn get_backup_now_progress(ctx: &AppContext, operation_id: &str) -> Option<OperationProgress> {
    work_management_controller::get_backup_now_progress(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
}

/// Get the result of a backup_now operation
pub fn get_backup_now_result(
    ctx: &AppContext,
    operation_id: &str,
) -> Result<Option<BackupResultDto>> {
    work_management_controller::get_backup_now_result(
        &ctx.long_operation_manager.lock().unwrap(),
        operation_id,
    )
    .context("getting backup_now result")
}

pub fn close_work(ctx: &AppContext) -> Result<()> {
    work_management_controller::close_work(&ctx.db_context, &ctx.event_hub).context("close_work")
}

pub fn new_work(ctx: &AppContext, dto: &NewWorkDto) -> Result<()> {
    work_management_controller::new_work(&ctx.db_context, &ctx.event_hub, dto).context("new_work")
}
