# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cyril/Devel/workspace_eric/plume-creator/src/plume/gui/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(618, 539)
        Preferences.setSizeGripEnabled(True)
        Preferences.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previousButton = QtWidgets.QToolButton(Preferences)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pics/32x32/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon)
        self.previousButton.setIconSize(QtCore.QSize(32, 32))
        self.previousButton.setArrowType(QtCore.Qt.NoArrow)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_2.addWidget(self.previousButton)
        self.titleLabel = QtWidgets.QLabel(Preferences)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(Preferences)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 438))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.displayBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.displayBox.setFlat(False)
        self.displayBox.setObjectName("displayBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.displayBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.themeButton = QtWidgets.QToolButton(self.displayBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pics/48x48/format-fill-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.themeButton.setIcon(icon1)
        self.themeButton.setIconSize(QtCore.QSize(48, 48))
        self.themeButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.themeButton.setObjectName("themeButton")
        self.horizontalLayout.addWidget(self.themeButton)
        self.verticalLayout_2.addWidget(self.displayBox)
        self.pluginsBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.pluginsBox.setObjectName("pluginsBox")
        self.verticalLayout_2.addWidget(self.pluginsBox)
        self.editorBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.editorBox.setObjectName("editorBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.editorBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pluginButton = QtWidgets.QToolButton(self.editorBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pics/48x48/preferences-plugin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pluginButton.setIcon(icon2)
        self.pluginButton.setIconSize(QtCore.QSize(48, 48))
        self.pluginButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.pluginButton.setObjectName("pluginButton")
        self.horizontalLayout_3.addWidget(self.pluginButton)
        self.verticalLayout_2.addWidget(self.editorBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.buttonBox.accepted.connect(Preferences.accept)
        self.buttonBox.rejected.connect(Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):

        Preferences.setWindowTitle(_("Dialog"))
        self.previousButton.setText(_("PushButton"))
        self.titleLabel.setText(_("TitleLabel"))
        self.displayBox.setTitle(_("Display"))
        self.themeButton.setText(_("Theme"))
        self.pluginsBox.setTitle(_("Editor"))
        self.editorBox.setTitle(_("Plugins"))
        self.pluginButton.setText(_("Plugins"))

