// Generated by Qleany v1.8.0 from common_entity_table.tera

// ═══════════════════════════════════════════════════════════════════════
// Entity WITH forward relationships — explicit struct implementation
// ═══════════════════════════════════════════════════════════════════════

use crate::database::hashmap_store::{
    HashMapStore, delete_from_backward_junction, junction_get, junction_remove, junction_set,
};
use crate::entities::Search;
use crate::error::RepositoryError;
use crate::types::EntityId;
use crate::{impl_relationship_methods, impl_write_relationship_methods};
use im::HashMap;
use std::sync::RwLock;

use super::search_repository::SearchRelationshipField;
use super::search_repository::SearchTable;
use super::search_repository::SearchTableRO;

pub struct SearchHashMapTable<'a> {
    store: &'a HashMapStore,
}

impl<'a> SearchHashMapTable<'a> {
    pub fn new(store: &'a HashMapStore) -> Self {
        Self { store }
    }

    fn resolve_junction(
        &self,
        field: &SearchRelationshipField,
    ) -> &RwLock<HashMap<EntityId, Vec<EntityId>>> {
        match field {
            SearchRelationshipField::Results => &self.store.jn_search_result_from_search_results,
        }
    }

    fn hydrate(&self, entity: &mut Search) {
        entity.results = junction_get(&self.store.jn_search_result_from_search_results, &entity.id);
    }
}

impl<'a> SearchTable for SearchHashMapTable<'a> {
    fn create(&mut self, entity: &Search) -> Result<Search, RepositoryError> {
        self.create_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn create_multi(&mut self, entities: &[Search]) -> Result<Vec<Search>, RepositoryError> {
        let mut created = Vec::with_capacity(entities.len());
        let mut search_map = self.store.searchs.write().unwrap();

        for entity in entities {
            let new_entity = if entity.id == EntityId::default() {
                let id = self.store.next_id("search");
                Search {
                    id,
                    ..entity.clone()
                }
            } else {
                if search_map.contains_key(&entity.id) {
                    return Err(RepositoryError::DuplicateId {
                        entity: "Search",
                        id: entity.id,
                    });
                }
                entity.clone()
            };

            search_map.insert(new_entity.id, new_entity.clone());

            junction_set(
                &self.store.jn_search_result_from_search_results,
                new_entity.id,
                new_entity.results.clone(),
            );

            created.push(new_entity);
        }
        Ok(created)
    }

    fn get(&self, id: &EntityId) -> Result<Option<Search>, RepositoryError> {
        let search_map = self.store.searchs.read().unwrap();
        match search_map.get(id) {
            Some(entity) => {
                let mut e = entity.clone();
                drop(search_map);
                self.hydrate(&mut e);
                Ok(Some(e))
            }
            None => Ok(None),
        }
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Search>>, RepositoryError> {
        let mut result = Vec::with_capacity(ids.len());
        for id in ids {
            result.push(self.get(id)?);
        }
        Ok(result)
    }

    fn get_all(&self) -> Result<Vec<Search>, RepositoryError> {
        let search_map = self.store.searchs.read().unwrap();
        let entries: Vec<Search> = search_map.values().cloned().collect();
        drop(search_map);
        let mut result = Vec::with_capacity(entries.len());
        for mut entity in entries {
            self.hydrate(&mut entity);
            result.push(entity);
        }
        Ok(result)
    }

    fn update(&mut self, entity: &Search) -> Result<Search, RepositoryError> {
        self.update_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    // Scalar-only update: writes entity data but does NOT touch junction tables.
    fn update_multi(&mut self, entities: &[Search]) -> Result<Vec<Search>, RepositoryError> {
        let mut search_map = self.store.searchs.write().unwrap();
        for entity in entities {
            search_map.insert(entity.id, entity.clone());
        }
        drop(search_map);
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn update_with_relationships(&mut self, entity: &Search) -> Result<Search, RepositoryError> {
        self.update_with_relationships_multi(std::slice::from_ref(entity))
            .map(|v| v.into_iter().next().unwrap())
    }

    fn update_with_relationships_multi(
        &mut self,
        entities: &[Search],
    ) -> Result<Vec<Search>, RepositoryError> {
        let mut search_map = self.store.searchs.write().unwrap();
        for entity in entities {
            search_map.insert(entity.id, entity.clone());

            junction_set(
                &self.store.jn_search_result_from_search_results,
                entity.id,
                entity.results.clone(),
            );
        }
        drop(search_map);
        let ids: Vec<EntityId> = entities.iter().map(|e| e.id).collect();
        let result = self.get_multi(&ids)?;
        Ok(result.into_iter().flatten().collect())
    }

    fn remove(&mut self, id: &EntityId) -> Result<(), RepositoryError> {
        self.remove_multi(std::slice::from_ref(id))
    }

    fn remove_multi(&mut self, ids: &[EntityId]) -> Result<(), RepositoryError> {
        let mut search_map = self.store.searchs.write().unwrap();
        for id in ids {
            search_map.remove(id);

            // Remove forward junction entries

            junction_remove(&self.store.jn_search_result_from_search_results, id);

            // Clean up backward references (uses the owning entity's forward junction)

            delete_from_backward_junction(&self.store.jn_search_from_work_info_search, id);
        }
        Ok(())
    }

    impl_write_relationship_methods!(SearchHashMapTable<'a>, SearchRelationshipField);
}

pub struct SearchHashMapTableRO<'a> {
    store: &'a HashMapStore,
}

impl<'a> SearchHashMapTableRO<'a> {
    pub fn new(store: &'a HashMapStore) -> Self {
        Self { store }
    }

    fn resolve_junction(
        &self,
        field: &SearchRelationshipField,
    ) -> &RwLock<HashMap<EntityId, Vec<EntityId>>> {
        match field {
            SearchRelationshipField::Results => &self.store.jn_search_result_from_search_results,
        }
    }

    fn hydrate(&self, entity: &mut Search) {
        entity.results = junction_get(&self.store.jn_search_result_from_search_results, &entity.id);
    }
}

impl<'a> SearchTableRO for SearchHashMapTableRO<'a> {
    fn get(&self, id: &EntityId) -> Result<Option<Search>, RepositoryError> {
        let search_map = self.store.searchs.read().unwrap();
        match search_map.get(id) {
            Some(entity) => {
                let mut e = entity.clone();
                drop(search_map);
                self.hydrate(&mut e);
                Ok(Some(e))
            }
            None => Ok(None),
        }
    }

    fn get_multi(&self, ids: &[EntityId]) -> Result<Vec<Option<Search>>, RepositoryError> {
        let mut result = Vec::with_capacity(ids.len());
        for id in ids {
            result.push(self.get(id)?);
        }
        Ok(result)
    }

    fn get_all(&self) -> Result<Vec<Search>, RepositoryError> {
        let search_map = self.store.searchs.read().unwrap();
        let entries: Vec<Search> = search_map.values().cloned().collect();
        drop(search_map);
        let mut result = Vec::with_capacity(entries.len());
        for mut entity in entries {
            self.hydrate(&mut entity);
            result.push(entity);
        }
        Ok(result)
    }

    impl_relationship_methods!(SearchHashMapTableRO<'a>, SearchRelationshipField);
}
