/******************************************************************************
 Copyright (C) 2025 by Cyril Jacquet                                          *
 cyril.jacquet@skribisto.eu                                                   *
                                                                              *
 This file is part of Skribisto.                                              *
                                                                              *
 Skribisto is free software: you can redistribute it and/or modify            *
 it under the terms of the GNU General Public License as published by         *
 the Free Software Foundation, either version 3 of the License, or            *
 (at your option) any later version.                                          *
                                                                              *
 Skribisto is distributed in the hope that it will be useful,                 *
 but WITHOUT ANY WARRANTY; without even the implied warranty of               *
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                *
 GNU General Public License for more details.                                 *
                                                                              *
 You should have received a copy of the GNU General Public License            *
 along with Skribisto.  If not, see <http://www.gnu.org/licenses/>.           *
 ******************************************************************************/

// This file was generated automatically by Qleany's generator, edit at your own risk!// If you do, be careful to not
// overwrite it when you run the generator again.

#include "database/db_context.h"
#include "direct_access/event_registry.h"
#include "service_locator.h"

#include <QCoroQml>
#include <QCoroQmlTask>
#include <QGuiApplication>
#include <QLoggingCategory>
#include <QQmlApplicationEngine>

using namespace Qt::StringLiterals;
int main(int argc, char *argv[])
{
    qputenv("QT_AUTO_SCREEN_SCALE_FACTOR", "1");
    qputenv("QT_LOGGING_RULES", "qt.qml.connections=false");
    qputenv("QT_QUICK_CONTROLS_CONF", ":/qtquickcontrols2.conf");
    qputenv("QML_COMPAT_RESOLVE_URLS_ON_ASSIGNMENT", "1");
    qputenv("QT_ENABLE_HIGHDPI_SCALING", "0");

    QLoggingCategory::setFilterRules("default.debug=true\n"
                                     "qt.qml.debug=true\n"
                                     "qml.debug=true\n"
                                     "js.debug=true\n"
                                     "qt.qml.console.debug=true\n"
                                     "qml.console.debug=true"_L1);

    QGuiApplication app(argc, argv);
    app.setApplicationName("FrontEndsExample"_L1);
    app.setOrganizationName("frontendsexample"_L1);
    app.setOrganizationDomain("qleany.eu"_L1);

#ifndef BUILD_WITH_MOCKS
    // These registrations are necessary to make the app work with the backend generated by the code generator of Qleany

    auto *db = new Skribisto::Common::Database::DbContext(&app);
    auto *ev = new Skribisto::Common::DirectAccess::EventRegistry(&app);
    // Undo Redo System
    // Skribisto::Common::UndoRedo::Scopes scopes(QStringList() << "root"_L1
    //                                                          << "project"_L1
    //                                                          << "binder"_L1
    //                                                          << "binder_items"_L1
    //                                                          << "tags"_L1);
    auto *urs = new Skribisto::Common::UndoRedo::UndoRedoSystem(&app);

    auto *locator = new Skribisto::Common::ServiceLocator(&app);
    locator->setDbContext(db);
    locator->setEventRegistry(ev);
    locator->setUndoRedoSystem(urs);
    Skribisto::Common::ServiceLocator::setInstance(locator);

#endif

    QCoro::Qml::registerTypes();

    QQmlApplicationEngine engine;
    const QUrl url(u"qrc:/qt/qml/Main/main.qml"_s);
    QObject::connect(
        &engine, &QQmlApplicationEngine::objectCreated, &app,
        [url](QObject *obj, const QUrl &objUrl) {
            if (!obj && (url == objUrl))
                QCoreApplication::exit(-1);
        },
        Qt::QueuedConnection);

    engine.addImportPath(QCoreApplication::applicationDirPath() + "/qml"_L1);
    engine.addImportPath(":/"_L1);
#if defined(BUILD_WITH_MOCKS)
    engine.addImportPath(QCoreApplication::applicationDirPath() + "/mock_imports"_L1);
#endif

    engine.load(url);

    if (engine.rootObjects().isEmpty())
    {
        return -1;
    }

    // Ensure proper shutdown of async operations before app termination
    auto cleanup = [&]() {
        auto *locator = Skribisto::Common::ServiceLocator::instance();
        if (locator && locator->undoRedoSystem())
        {
            locator->undoRedoSystem()->shutdown();

            // Give Qt's background threads time to complete cleanup
            // This prevents database operations from happening after QCoreApplication destruction
            QThread::msleep(100);

            qDebug() << "Cleanup complete, application will now exit";
        }
    };

    // Connect to aboutToQuit to ensure cleanup happens before QCoreApplication destruction
    QObject::connect(&app, &QGuiApplication::aboutToQuit, cleanup);

    return app.exec();
}