// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from entity_dtos.tera

pub use common::entities::ChapterMode;
use common::entities::Work;
use common::types::EntityId;
use serde::{Deserialize, Serialize};
use std::convert::From;

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct WorkDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub author_name: String,
    pub dict_language: Vec<String>,
    pub unique_id: String,
    pub chapter_mode: ChapterMode,
    pub custom_replacement_rules_enabled: bool,
    pub binders: Vec<EntityId>,
    pub tags: Vec<EntityId>,
    pub dict_words: Vec<EntityId>,
    pub text_replacement_rules: Vec<EntityId>,
    pub trash_infos: Vec<EntityId>,
    pub paces: Vec<EntityId>,
}

impl From<WorkDto> for Work {
    fn from(dto: WorkDto) -> Self {
        Work {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            author_name: dto.author_name,
            dict_language: dto.dict_language,
            unique_id: dto.unique_id,
            chapter_mode: dto.chapter_mode,
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled,
            binders: dto.binders,
            tags: dto.tags,
            dict_words: dto.dict_words,
            text_replacement_rules: dto.text_replacement_rules,
            trash_infos: dto.trash_infos,
            paces: dto.paces,
        }
    }
}

impl From<&WorkDto> for Work {
    fn from(dto: &WorkDto) -> Self {
        Work {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            title: dto.title.clone(),
            author_name: dto.author_name.clone(),
            dict_language: dto.dict_language.clone(),
            unique_id: dto.unique_id.clone(),
            chapter_mode: dto.chapter_mode.clone(),
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled.clone(),
            binders: dto.binders.clone(),
            tags: dto.tags.clone(),
            dict_words: dto.dict_words.clone(),
            text_replacement_rules: dto.text_replacement_rules.clone(),
            trash_infos: dto.trash_infos.clone(),
            paces: dto.paces.clone(),
        }
    }
}

impl From<Work> for WorkDto {
    fn from(entity: Work) -> Self {
        WorkDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            title: entity.title,
            author_name: entity.author_name,
            dict_language: entity.dict_language,
            unique_id: entity.unique_id,
            chapter_mode: entity.chapter_mode,
            custom_replacement_rules_enabled: entity.custom_replacement_rules_enabled,
            binders: entity.binders,
            tags: entity.tags,
            dict_words: entity.dict_words,
            text_replacement_rules: entity.text_replacement_rules,
            trash_infos: entity.trash_infos,
            paces: entity.paces,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CreateWorkDto {
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub author_name: String,
    pub dict_language: Vec<String>,
    pub unique_id: String,
    pub chapter_mode: ChapterMode,
    pub custom_replacement_rules_enabled: bool,
    pub binders: Vec<EntityId>,
    pub tags: Vec<EntityId>,
    pub dict_words: Vec<EntityId>,
    pub text_replacement_rules: Vec<EntityId>,
    pub trash_infos: Vec<EntityId>,
    pub paces: Vec<EntityId>,
}

impl From<CreateWorkDto> for Work {
    fn from(dto: CreateWorkDto) -> Self {
        Work {
            id: 0,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            author_name: dto.author_name,
            dict_language: dto.dict_language,
            unique_id: dto.unique_id,
            chapter_mode: dto.chapter_mode,
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled,
            binders: dto.binders,
            tags: dto.tags,
            dict_words: dto.dict_words,
            text_replacement_rules: dto.text_replacement_rules,
            trash_infos: dto.trash_infos,
            paces: dto.paces,
        }
    }
}

impl From<&CreateWorkDto> for Work {
    fn from(dto: &CreateWorkDto) -> Self {
        Work {
            id: 0,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            title: dto.title.clone(),
            author_name: dto.author_name.clone(),
            dict_language: dto.dict_language.clone(),
            unique_id: dto.unique_id.clone(),
            chapter_mode: dto.chapter_mode.clone(),
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled.clone(),
            binders: dto.binders.clone(),
            tags: dto.tags.clone(),
            dict_words: dto.dict_words.clone(),
            text_replacement_rules: dto.text_replacement_rules.clone(),
            trash_infos: dto.trash_infos.clone(),
            paces: dto.paces.clone(),
        }
    }
}

impl From<Work> for CreateWorkDto {
    fn from(entity: Work) -> Self {
        CreateWorkDto {
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            title: entity.title,
            author_name: entity.author_name,
            dict_language: entity.dict_language,
            unique_id: entity.unique_id,
            chapter_mode: entity.chapter_mode,
            custom_replacement_rules_enabled: entity.custom_replacement_rules_enabled,
            binders: entity.binders,
            tags: entity.tags,
            dict_words: entity.dict_words,
            text_replacement_rules: entity.text_replacement_rules,
            trash_infos: entity.trash_infos,
            paces: entity.paces,
        }
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct UpdateWorkDto {
    pub id: EntityId,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
    pub title: String,
    pub author_name: String,
    pub dict_language: Vec<String>,
    pub unique_id: String,
    pub chapter_mode: ChapterMode,
    pub custom_replacement_rules_enabled: bool,
}

impl From<UpdateWorkDto> for Work {
    fn from(dto: UpdateWorkDto) -> Self {
        Work {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            author_name: dto.author_name,
            dict_language: dto.dict_language,
            unique_id: dto.unique_id,
            chapter_mode: dto.chapter_mode,
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled,
            binders: Default::default(),
            tags: Default::default(),
            dict_words: Default::default(),
            text_replacement_rules: Default::default(),
            trash_infos: Default::default(),
            paces: Default::default(),
        }
    }
}

impl From<&UpdateWorkDto> for Work {
    fn from(dto: &UpdateWorkDto) -> Self {
        Work {
            id: dto.id,
            created_at: dto.created_at.clone(),
            updated_at: dto.updated_at.clone(),
            title: dto.title.clone(),
            author_name: dto.author_name.clone(),
            dict_language: dto.dict_language.clone(),
            unique_id: dto.unique_id.clone(),
            chapter_mode: dto.chapter_mode.clone(),
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled.clone(),
            binders: Default::default(),
            tags: Default::default(),
            dict_words: Default::default(),
            text_replacement_rules: Default::default(),
            trash_infos: Default::default(),
            paces: Default::default(),
        }
    }
}

impl From<Work> for UpdateWorkDto {
    fn from(entity: Work) -> Self {
        UpdateWorkDto {
            id: entity.id,
            created_at: entity.created_at,
            updated_at: entity.updated_at,
            title: entity.title,
            author_name: entity.author_name,
            dict_language: entity.dict_language,
            unique_id: entity.unique_id,
            chapter_mode: entity.chapter_mode,
            custom_replacement_rules_enabled: entity.custom_replacement_rules_enabled,
        }
    }
}

impl From<WorkDto> for UpdateWorkDto {
    fn from(dto: WorkDto) -> Self {
        UpdateWorkDto {
            id: dto.id,
            created_at: dto.created_at,
            updated_at: dto.updated_at,
            title: dto.title,
            author_name: dto.author_name,
            dict_language: dto.dict_language,
            unique_id: dto.unique_id,
            chapter_mode: dto.chapter_mode,
            custom_replacement_rules_enabled: dto.custom_replacement_rules_enabled,
        }
    }
}
pub use common::direct_access::work::WorkRelationshipField;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WorkRelationshipDto {
    pub id: EntityId,
    pub field: WorkRelationshipField,
    pub right_ids: Vec<EntityId>,
}
