#pragma once

#include <QtCore/QtGlobal>

#if defined(SKRIBISTO_APPLICATION_WRITING_LIBRARY)
#define SKRIBISTO_APPLICATION_WRITING_EXPORT Q_DECL_EXPORT
#else // if defined(SKRIBISTO_APPLICATION_WRITING_LIBRARY)
#define SKRIBISTO_APPLICATION_WRITING_EXPORT Q_DECL_IMPORT
#endif // if defined(SKRIBISTO_APPLICATION_WRITING_LIBRARY)