// Generated by Qleany v1.4.5 from feature_controller_qml.tera

import QtQuick

QtObject {
    id: controller

    property int undoRedoStackId: 0

    function getDuplicateDto() {
        return {
            "itemIds": []
        };
    }

    function duplicate(duplicateDto) {
        let return_dto = {};

        // mocking QCoro::Task
        let task;
        var component = Qt.createComponent("QCoroQmlTask.qml");
        if (component.status === Component.Ready) {
            task = component.createObject(controller);
            task.setValue(return_dto);
            task.setDelay(50);
        }

        return task;
    }

    function getMoveDto() {
        return {
            "itemIds": [],
            "targetId": null,
            "movePlace": ""
        };
    }

    function moveItems(moveDto) {
        let return_dto = true;

        // mocking QCoro::Task
        let task;
        var component = Qt.createComponent("QCoroQmlTask.qml");
        if (component.status === Component.Ready) {
            task = component.createObject(controller);
            task.setValue(return_dto);
            task.setDelay(50);
        }

        return task;
    }
}
