// Generated by Qleany v1.4.5 from feature_event_registry_qml.tera
pragma Singleton

import QtQuick

QtObject {
    function workManagementEvents() {
        return WorkManagementEvents;
    }
    function exportManagementEvents() {
        return ExportManagementEvents;
    }
    function trashManagementEvents() {
        return TrashManagementEvents;
    }
    function binderItemManagementEvents() {
        return BinderItemManagementEvents;
    }
    function handlingAppLifecycleEvents() {
        return HandlingAppLifecycleEvents;
    }
}
