// Generated by Qleany v1.4.2 from foreign_list_model_h.tera
#pragma once
#include "system/models/system_trash_infos_list_model.h"
#include <QQmlEngine>

struct ForeignSystemTrashInfosListModel
{
    Q_GADGET
    QML_FOREIGN(Skribisto::DirectAccess::System::SystemTrashInfosListModel)
    QML_NAMED_ELEMENT(SystemTrashInfosListModel)
};
