// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.10.0 from common_direct_access_mod.tera

pub mod asset;
pub mod binder;
pub mod binder_item;
pub mod binder_status;
pub mod binder_tag;
pub mod comment;
pub mod comment_reply;
pub mod content;
pub mod dict_word;
pub mod footnote;
pub mod holiday;
pub mod milestone;
pub mod note_template;
pub mod pace;
pub mod progress_snapshot;
pub mod recent_work;
pub mod repository_factory;
pub mod root;
pub mod search;
pub mod search_result;
pub(crate) mod setup;
pub mod smart_punctuation;
pub mod system;
pub mod text_replacement_rule;
pub mod trash_info;
pub mod use_cases;
pub mod work;
pub mod work_info;
