// Generated by Qleany v1.4.2 from controller_command_helpers_h.tera
/******************************************************************************
 * Controller Command Helpers
 *
 * Template helpers that encapsulate the repetitive command/query wiring
 * found in every entity and feature controller.
 *
 * Helpers for entity controllers (single-command operations):
 * - executeUndoableCommand       — execute + push to undo stack (with result)
 * - executeUndoableCommandVoid   — execute + push to undo stack (void)
 * - executeNotUndoableCommand    — execute on throwaway stack (with result)
 * - executeNotUndoableCommandVoid— execute on throwaway stack (void)
 * - executeReadQuery             — read-only query through the system
 *
 * Helpers for command composition (GroupCommand in feature controllers):
 * - executeDeferredCommand       — execute + return command (with result)
 * - executeDeferredCommandVoid   — execute + return command (void)
 * - rollbackDeferredCommands     — undo a list of deferred commands in reverse
 *
 * Features:
 * - Configurable timeout per call
 * - UseCase lifetime managed by direct shared_ptr capture
 * - Error callback for signal-based error reporting
 * - Type-safe, debuggable, IDE-navigable
 *
 * Usage — single-command (in a generated entity controller):
 *
 *   QCoro::Task<QList<PersonDto>> PersonController::create(
 *       const QList<CreatePersonDto> &persons)
 *   {
 *       auto uow = std::make_unique<PersonUnitOfWork>(*m_dbContext, m_eventRegistry);
 *       auto useCase = std::make_shared<CreatePersonUseCase>(std::move(uow));
 *
 *       co_return co_await executeUndoableCommand<QList<PersonDto>>(
 *           m_undoRedoSystem,
 *           m_undoRedoStackId,
 *           u"Create persons Command"_s,
 *           std::move(useCase),
 *           500,
 *           [this](const QString &cmd, const QString &msg) {
 *               if (m_eventRegistry) m_eventRegistry->publishError(cmd, msg);
 *           },
 *           persons);
 *   }
 *
 * Usage — grouped commands (in a custom feature controller):
 *
 *   QCoro::Task<bool> MyFeatureController::importData(const ImportDto &dto)
 *   {
 *       QList<std::shared_ptr<UndoRedoCommand>> executed;
 *
 *       // Step 1
 *       auto [result1, cmd1] = co_await executeDeferredCommand<QList<CarDto>>(
 *           u"Create cars"_s, useCase1, 500, onError, dto.cars, ownerId, -1);
 *       if (!cmd1) co_return false;
 *       executed.append(cmd1);
 *
 *       // Step 2 (depends on step 1)
 *       auto [ok, cmd2] = co_await executeDeferredCommandVoid(
 *           u"Link tags"_s, useCase2, 500, onError, result1[0].id(), dto.tagIds);
 *       if (!cmd2) {
 *           co_await rollbackDeferredCommands(executed);
 *           co_return false;
 *       }
 *       executed.append(cmd2);
 *
 *       // Register all steps as a single undo unit
 *       auto group = std::make_shared<GroupCommand>(u"Import data"_s);
 *       for (auto &cmd : executed) group->addCommand(cmd);
 *       m_undoRedoSystem->manager()->pushCommand(group, m_undoRedoStackId);
 *       co_return true;
 *   }
 ******************************************************************************/

#pragma once

#include "undo_redo/undo_redo_command.h"

#include <QCoro/QCoroSignal>
#include <QCoro/QCoroTask>
#include <QDebug>
#include <QList>
#include <QString>
#include <functional>
#include <memory>
#include <optional>
#include <type_traits>
#include <utility>

using namespace Qt::StringLiterals;

namespace Skribisto::Common::ControllerHelpers
{

namespace SCUndoRedo = Skribisto::Common::UndoRedo;

// =============================================================================
// Undoable Command — returns a result from execute()
// =============================================================================

/**
 * @brief Execute an undoable command, returning the use-case result.
 *
 * Constructs the UndoRedoCommand, wires execute/undo/redo, and co_awaits
 * the undo-redo system. The UseCase is kept alive by shared_ptr capture
 * inside the lambdas.
 *
 * @tparam ResultT       Return type of the use-case execute method
 * @tparam UseCaseT      UseCase type (must have execute(...), undo(), redo())
 * @tparam ExecArgs      Argument types forwarded to useCase->execute(...)
 *
 * @param undoRedoSystem The undo-redo system to execute on
 * @param undoRedoStackId The undo redo stack to use
 * @param commandName    Human-readable name for the command
 * @param useCase        Shared ownership of the use case
 * @param timeoutMs      Timeout in milliseconds for async execution
 * @param onError        Callback invoked on timeout or failure (commandName, message)
 * @param execArgs       Arguments forwarded to useCase->execute(...)
 *
 * @return The result of useCase->execute(), or a default-constructed ResultT on failure.
 */
template <typename ResultT, typename UseCaseT, typename... ExecArgs>
[[nodiscard]] QCoro::Task<ResultT> executeUndoableCommand(SCUndoRedo::UndoRedoSystem *undoRedoSystem,
                                                          int undoRedoStackId, const QString &commandName,
                                                          std::shared_ptr<UseCaseT> useCase, int timeoutMs,
                                                          std::function<void(const QString &, const QString &)> onError,
                                                          ExecArgs... execArgs)
{
    if (!undoRedoSystem) [[unlikely]]
    {
        qCritical() << "UndoRedo system not available";
        co_return ResultT{};
    }

    auto command = std::make_shared<SCUndoRedo::UndoRedoCommand>(commandName);
    auto result = std::make_shared<ResultT>();

    // Capture useCase and result by shared_ptr value — both stay alive as long
    // as the command's lambdas exist, even if the coroutine frame is destroyed
    // on timeout.
    command->setExecuteFunction(
        [useCase, ... args = std::move(execArgs), result](auto & /*promise*/) { *result = useCase->execute(args...); });

    command->setRedoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->redo(); });

    command->setUndoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->undo(); });

    std::optional<bool> success = co_await undoRedoSystem->executeCommandAsync(command, timeoutMs, undoRedoStackId);

    if (!success.has_value()) [[unlikely]]
    {
        QString msg = commandName + " timed out"_L1;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ResultT{};
    }

    if (!success.value()) [[unlikely]]
    {
        QString msg = "Failed to execute "_L1 + commandName;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ResultT{};
    }

    co_return std::move(*result);
}

// =============================================================================
// Undoable Command — void execute (no return value)
// =============================================================================

/**
 * @brief Execute an undoable command whose execute() returns void.
 *
 * Same pattern as the result-returning variant but returns a boolean
 * indicating success/failure.
 */
template <typename UseCaseT, typename... ExecArgs>
[[nodiscard]] QCoro::Task<bool> executeUndoableCommandVoid(
    SCUndoRedo::UndoRedoSystem *undoRedoSystem, int undoRedoStackId, const QString &commandName,
    std::shared_ptr<UseCaseT> useCase, int timeoutMs, std::function<void(const QString &, const QString &)> onError,
    ExecArgs... execArgs)
{
    if (!undoRedoSystem) [[unlikely]]
    {
        qCritical() << "UndoRedo system not available";
        co_return false;
    }

    auto command = std::make_shared<SCUndoRedo::UndoRedoCommand>(commandName);

    command->setExecuteFunction(
        [useCase, ... args = std::move(execArgs)](auto & /*promise*/) { useCase->execute(args...); });

    command->setRedoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->redo(); });

    command->setUndoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->undo(); });

    std::optional<bool> success = co_await undoRedoSystem->executeCommandAsync(command, timeoutMs, undoRedoStackId);

    if (!success.has_value()) [[unlikely]]
    {
        QString msg = commandName + " timed out"_L1;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return false;
    }

    if (!success.value()) [[unlikely]]
    {
        QString msg = "Failed to execute "_L1 + commandName;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return false;
    }

    co_return true;
}

// =============================================================================
// Not Undoable Command — returns a result from execute()
// =============================================================================

/**
 * @brief Execute a not-undoable command, returning the use-case result.
 *
 * Constructs the UndoRedoCommand, wires only execute (no undo/redo), and
 * co_awaits the undo-redo system on a throwaway stack. After execution the
 * stack is cleared. The UseCase is kept alive by shared_ptr capture inside
 * the lambda.
 *
 * @tparam ResultT       Return type of the use-case execute method
 * @tparam UseCaseT      UseCase type (must have execute(...))
 * @tparam ExecArgs      Argument types forwarded to useCase->execute(...)
 *
 * @param undoRedoSystem The undo-redo system to execute on
 * @param commandName    Human-readable name for the command
 * @param useCase        Shared ownership of the use case
 * @param timeoutMs      Timeout in milliseconds for async execution
 * @param onError        Callback invoked on timeout or failure (commandName, message)
 * @param execArgs       Arguments forwarded to useCase->execute(...)
 *
 * @return The result of useCase->execute(), or a default-constructed ResultT on failure.
 */
template <typename ResultT, typename UseCaseT, typename... ExecArgs>
[[nodiscard]] QCoro::Task<ResultT> executeNotUndoableCommand(
    SCUndoRedo::UndoRedoSystem *undoRedoSystem, const QString &commandName, std::shared_ptr<UseCaseT> useCase,
    int timeoutMs, std::function<void(const QString &, const QString &)> onError, ExecArgs... execArgs)
{
    if (!undoRedoSystem) [[unlikely]]
    {
        qCritical() << "UndoRedo system not available";
        co_return ResultT{};
    }

    auto command = std::make_shared<SCUndoRedo::UndoRedoCommand>(commandName);
    auto result = std::make_shared<ResultT>();

    // Capture useCase and result by shared_ptr value — both stay alive as long
    // as the command's lambdas exist, even if the coroutine frame is destroyed
    // on timeout.
    command->setExecuteFunction(
        [useCase, ... args = std::move(execArgs), result](auto & /*promise*/) { *result = useCase->execute(args...); });

    std::optional<bool> success = co_await undoRedoSystem->executeCommandAsync(command, timeoutMs, -1);

    if (!success.has_value()) [[unlikely]]
    {
        QString msg = commandName + " timed out"_L1;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ResultT{};
    }

    if (!success.value()) [[unlikely]]
    {
        QString msg = "Failed to execute "_L1 + commandName;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ResultT{};
    }

    // clear undo redo
    undoRedoSystem->manager()->clearStack(-1);

    co_return std::move(*result);
}

// =============================================================================
// Not Undoable Command — void execute (no return value)
// =============================================================================

/**
 * @brief Execute a not-undoable command whose execute() returns void.
 *
 * Same pattern as the result-returning not-undoable variant but returns
 * a boolean indicating success/failure.
 */
template <typename UseCaseT, typename... ExecArgs>
[[nodiscard]] QCoro::Task<bool> executeNotUndoableCommandVoid(
    SCUndoRedo::UndoRedoSystem *undoRedoSystem, const QString &commandName, std::shared_ptr<UseCaseT> useCase,
    int timeoutMs, std::function<void(const QString &, const QString &)> onError, ExecArgs... execArgs)
{
    if (!undoRedoSystem) [[unlikely]]
    {
        qCritical() << "UndoRedo system not available";
        co_return false;
    }

    auto command = std::make_shared<SCUndoRedo::UndoRedoCommand>(commandName);

    command->setExecuteFunction(
        [useCase, ... args = std::move(execArgs)](auto & /*promise*/) { useCase->execute(args...); });

    std::optional<bool> success = co_await undoRedoSystem->executeCommandAsync(command, timeoutMs, -1);

    if (!success.has_value()) [[unlikely]]
    {
        QString msg = commandName + " timed out"_L1;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return false;
    }

    if (!success.value()) [[unlikely]]
    {
        QString msg = "Failed to execute "_L1 + commandName;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return false;
    }

    // clear undo redo
    undoRedoSystem->manager()->clearStack(-1);

    co_return true;
}

// =============================================================================
// Read-only Query
// =============================================================================

/**
 * @brief Execute a read-only query through the undo-redo system.
 *
 * @tparam ResultT  Return type of the query
 * @tparam QueryFn  Callable returning ResultT (typically a lambda that
 *                  constructs UoW + UseCase and calls execute)
 *
 * @param undoRedoSystem The undo-redo system to execute on
 * @param queryName      Human-readable name for the query
 * @param queryFn        Callable invoked to produce the result
 *
 * @return The query result, or a default-constructed ResultT on failure.
 */
template <typename ResultT, typename QueryFn>
[[nodiscard]] QCoro::Task<ResultT> executeReadQuery(SCUndoRedo::UndoRedoSystem *undoRedoSystem,
                                                    const QString &queryName, QueryFn &&queryFn)
{
    if (!undoRedoSystem) [[unlikely]]
    {
        qCritical() << "UndoRedo system not available";
        co_return ResultT{};
    }

    auto query = undoRedoSystem->template createQuery<ResultT>(queryName);
    query->setQueryFunction(std::forward<QueryFn>(queryFn));

    co_return co_await undoRedoSystem->executeQueryAsync(query);
}

// =============================================================================
// Deferred Command — execute without registering on any stack
// =============================================================================

/**
 * @brief Execute a use case on a background thread and return both the result
 *        and the command object, without pushing to any undo/redo stack.
 *
 * The command runs via asyncExecute() / QtConcurrent::run, identical to the
 * normal path. The difference is that the resulting command is returned to
 * the caller instead of being registered on a stack.
 *
 * Intended for feature controllers that compose multiple entity operations
 * into a single GroupCommand (one undo unit). Collect the returned commands,
 * add them to a GroupCommand, and push the group with:
 *
 *     m_undoRedoSystem->manager()->pushCommand(group, m_undoRedoStackId);
 *
 * @tparam ResultT       Return type of the use-case execute method
 * @tparam UseCaseT      UseCase type (must have execute(...), undo(), redo())
 * @tparam ExecArgs      Argument types forwarded to useCase->execute(...)
 *
 * @param commandName    Human-readable name for the command
 * @param useCase        Shared ownership of the use case
 * @param timeoutMs      Timeout in milliseconds for async execution
 * @param onError        Callback invoked on timeout or failure (commandName, message)
 * @param execArgs       Arguments forwarded to useCase->execute(...)
 *
 * @return A pair of {result, command}. On failure, command is nullptr.
 */
template <typename ResultT, typename UseCaseT, typename... ExecArgs>
[[nodiscard]] QCoro::Task<std::pair<ResultT, std::shared_ptr<SCUndoRedo::UndoRedoCommand>>> executeDeferredCommand(
    const QString &commandName, std::shared_ptr<UseCaseT> useCase, int timeoutMs,
    std::function<void(const QString &, const QString &)> onError, ExecArgs... execArgs)
{
    using ReturnT = std::pair<ResultT, std::shared_ptr<SCUndoRedo::UndoRedoCommand>>;

    auto command = std::make_shared<SCUndoRedo::UndoRedoCommand>(commandName);
    auto result = std::make_shared<ResultT>();

    // Capture useCase and result by shared_ptr value — both stay alive as long
    // as the command's lambdas exist, even if the coroutine frame is destroyed
    // on timeout.
    command->setExecuteFunction(
        [useCase, ... args = std::move(execArgs), result](auto & /*promise*/) { *result = useCase->execute(args...); });

    command->setRedoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->redo(); });

    command->setUndoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->undo(); });

    // Execute directly — not through any stack
    command->asyncExecute();
    auto success =
        co_await qCoro(command.get(), &SCUndoRedo::UndoRedoCommand::finished, std::chrono::milliseconds(timeoutMs));

    if (!success.has_value()) [[unlikely]]
    {
        QString msg = commandName + " timed out"_L1;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ReturnT{ResultT{}, nullptr};
    }

    if (!success.value()) [[unlikely]]
    {
        QString msg = "Failed to execute "_L1 + commandName;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ReturnT{ResultT{}, nullptr};
    }

    co_return ReturnT{std::move(*result), command};
}

// =============================================================================
// Deferred Command — void execute (no return value)
// =============================================================================

/**
 * @brief Execute a use case on a background thread and return the command
 *        object, without pushing to any undo/redo stack.
 *
 * Same as executeDeferredCommand but for use cases whose execute() returns void.
 *
 * @return A pair of {success, command}. On failure, command is nullptr.
 */
template <typename UseCaseT, typename... ExecArgs>
[[nodiscard]] QCoro::Task<std::pair<bool, std::shared_ptr<SCUndoRedo::UndoRedoCommand>>> executeDeferredCommandVoid(
    const QString &commandName, std::shared_ptr<UseCaseT> useCase, int timeoutMs,
    std::function<void(const QString &, const QString &)> onError, ExecArgs... execArgs)
{
    using ReturnT = std::pair<bool, std::shared_ptr<SCUndoRedo::UndoRedoCommand>>;

    auto command = std::make_shared<SCUndoRedo::UndoRedoCommand>(commandName);

    command->setExecuteFunction(
        [useCase, ... args = std::move(execArgs)](auto & /*promise*/) { useCase->execute(args...); });

    command->setRedoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->redo(); });

    command->setUndoFunction([useCase]() -> SCUndoRedo::Result<void> { return useCase->undo(); });

    // Execute directly — not through any stack
    command->asyncExecute();
    auto success =
        co_await qCoro(command.get(), &SCUndoRedo::UndoRedoCommand::finished, std::chrono::milliseconds(timeoutMs));

    if (!success.has_value()) [[unlikely]]
    {
        QString msg = commandName + " timed out"_L1;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ReturnT{false, nullptr};
    }

    if (!success.value()) [[unlikely]]
    {
        QString msg = "Failed to execute "_L1 + commandName;
        qWarning() << msg;
        if (onError)
            onError(commandName, msg);
        co_return ReturnT{false, nullptr};
    }

    co_return ReturnT{true, command};
}

// =============================================================================
// Rollback Deferred Commands
// =============================================================================

/**
 * @brief Undo a list of already-executed deferred commands in reverse order.
 *
 * Use this to roll back partial progress when a grouped operation fails
 * mid-way. Each command's asyncUndo() runs on a background thread via
 * QtConcurrent::run, same as normal undo operations.
 *
 * @param commands   The commands to undo, in the order they were executed.
 *                   They will be undone in reverse order.
 * @param timeoutMs  Timeout per individual undo operation (default 500ms).
 *
 * @return true if all rollbacks succeeded, false if any failed.
 */
[[nodiscard]] inline QCoro::Task<bool> rollbackDeferredCommands(
    const QList<std::shared_ptr<SCUndoRedo::UndoRedoCommand>> &commands, int timeoutMs = 500)
{
    for (auto it = commands.rbegin(); it != commands.rend(); ++it)
    {
        (*it)->asyncUndo();
        auto success =
            co_await qCoro(it->get(), &SCUndoRedo::UndoRedoCommand::finished, std::chrono::milliseconds(timeoutMs));

        if (!success.has_value() || !success.value())
        {
            qWarning() << "Rollback failed for command:" << (*it)->text();
            co_return false;
        }
    }
    co_return true;
}

} // namespace Skribisto::Common::ControllerHelpers
