// Generated by Qleany v1.4.2 from service_locator_h.tera
#pragma once
#include "database/db_context.h"
#include "direct_access/event_registry.h"
#include "features/feature_event_registry.h"
#include "long_operation/long_operation_manager.h"
#include "undo_redo/undo_redo_system.h"

#include <QObject>
#include <QPointer>

namespace Skribisto::Common
{

class ServiceLocator : public QObject
{
    Q_OBJECT
  public:
    explicit ServiceLocator(QObject *parent = nullptr);
    ~ServiceLocator();

    void setDbContext(Database::DbContext *db);
    void setEventRegistry(DirectAccess::EventRegistry *ev);
    void setFeatureEventRegistry(Features::FeatureEventRegistry *fev);
    void setUndoRedoSystem(UndoRedo::UndoRedoSystem *urs);
    void setLongOperationManager(LongOperation::LongOperationManager *lom);

    QPointer<Database::DbContext> dbContext() const;
    QPointer<DirectAccess::EventRegistry> eventRegistry() const;
    QPointer<Features::FeatureEventRegistry> featureEventRegistry() const;
    QPointer<UndoRedo::UndoRedoSystem> undoRedoSystem() const;
    QPointer<LongOperation::LongOperationManager> longOperationManager() const;

    static void setInstance(ServiceLocator *locator);
    static ServiceLocator *instance();

  Q_SIGNALS:
    /// Forwarded from EventRegistry and FeatureEventRegistry when a command
    /// times out or fails. Single subscription point for all command errors.
    void errorOccurred(const QString &commandName, const QString &errorMessage);

  private:
    inline static ServiceLocator *s_instance = nullptr;
    QPointer<Database::DbContext> m_dbContext;
    QPointer<DirectAccess::EventRegistry> m_eventRegistry;
    QPointer<Features::FeatureEventRegistry> m_featureEventRegistry;
    QPointer<UndoRedo::UndoRedoSystem> m_undoRedoSystem;
    QPointer<LongOperation::LongOperationManager> m_longOperationManager;
};

} // namespace Skribisto::Common