// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 Cyril Jacquet

// Generated by Qleany v1.8.0 from feature_lib.tera
// Hand-edited: `kind_mapping` and `events` are hand-written modules (see their
// own doc comments), not part of Qleany's generated shape, and
// `diagnostic_to_dto` is re-exported for the UI's translation-coverage test.
// Do NOT blanket-regenerate this file without re-adding those lines.
pub mod dtos;
/// What an import did, and where each row's words came from — the payload on
/// the completion event. Hand-written: `Event.data` is a plain `String` the
/// generator knows nothing about.
pub mod events;
pub mod import_management_controller;
pub(crate) mod kind_mapping;
mod units_of_work;
pub mod use_cases;

pub use dtos::*;
/// The canonical diagnostic → DTO mapping, exposed so `teksilo_ui`'s
/// "every diagnostic reaches a translated sentence" test can drive the real one.
pub use use_cases::analyze_document_import_uc::diagnostic_to_dto;
