# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/cyril/Devel/workspace_eric/plume-creator/src/plume/gui/writingzone/writing_zone.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WritingZone(object):
    def setupUi(self, WritingZone):
        WritingZone.setObjectName("WritingZone")
        WritingZone.setEnabled(True)
        WritingZone.resize(816, 522)
        self.verticalLayout = QtWidgets.QVBoxLayout(WritingZone)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(WritingZone)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.historyPreviousToolButton = QtWidgets.QToolButton(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pics/32x32/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyPreviousToolButton.setIcon(icon)
        self.historyPreviousToolButton.setObjectName("historyPreviousToolButton")
        self.horizontalLayout_2.addWidget(self.historyPreviousToolButton)
        self.historyNextToolButton = QtWidgets.QToolButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pics/32x32/arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyNextToolButton.setIcon(icon1)
        self.historyNextToolButton.setObjectName("historyNextToolButton")
        self.horizontalLayout_2.addWidget(self.historyNextToolButton)
        self.browserComboBox = QtWidgets.QComboBox(self.widget)
        self.browserComboBox.setObjectName("browserComboBox")
        self.horizontalLayout_2.addWidget(self.browserComboBox)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.findComboBox = QtWidgets.QComboBox(self.widget)
        self.findComboBox.setEditable(True)
        self.findComboBox.setObjectName("findComboBox")
        self.horizontalLayout_3.addWidget(self.findComboBox)
        self.findPreviousToolButton = QtWidgets.QToolButton(self.widget)
        self.findPreviousToolButton.setIcon(icon)
        self.findPreviousToolButton.setObjectName("findPreviousToolButton")
        self.horizontalLayout_3.addWidget(self.findPreviousToolButton)
        self.findNextToolButton = QtWidgets.QToolButton(self.widget)
        self.findNextToolButton.setIcon(icon1)
        self.findNextToolButton.setObjectName("findNextToolButton")
        self.horizontalLayout_3.addWidget(self.findNextToolButton)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.toolBar = ToolBar(WritingZone)
        self.toolBar.setMinimumSize(QtCore.QSize(20, 0))
        self.toolBar.setObjectName("toolBar")
        self.verticalLayout_2.addWidget(self.toolBar)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.richTextEdit = RichTextEdit(WritingZone)
        self.richTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.richTextEdit.setObjectName("richTextEdit")
        self.horizontalLayout.addWidget(self.richTextEdit)
        self.sizehandle = QtWidgets.QWidget(WritingZone)
        self.sizehandle.setMinimumSize(QtCore.QSize(4, 0))
        self.sizehandle.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.sizehandle.setMouseTracking(True)
        self.sizehandle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sizehandle.setObjectName("sizehandle")
        self.horizontalLayout.addWidget(self.sizehandle)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.minimap = Minimap2(WritingZone)
        self.minimap.setObjectName("minimap")
        self.horizontalLayout.addWidget(self.minimap)
        self.minimap_old = Minimap(WritingZone)
        self.minimap_old.setObjectName("minimap_old")
        self.horizontalLayout.addWidget(self.minimap_old)
        self.verticalScrollBar = QtWidgets.QScrollBar(WritingZone)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout.addWidget(self.verticalScrollBar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.actionCopy = QtWidgets.QAction(WritingZone)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pics/32x32/edit-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon2)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(WritingZone)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pics/32x32/edit-paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon3)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtWidgets.QAction(WritingZone)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pics/32x32/edit-cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon4)
        self.actionCut.setObjectName("actionCut")
        self.actionBold = QtWidgets.QAction(WritingZone)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pics/32x32/format-text-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon5)
        self.actionBold.setObjectName("actionBold")
        self.actionStrikethrough = QtWidgets.QAction(WritingZone)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pics/32x32/format-text-strikethrough.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStrikethrough.setIcon(icon6)
        self.actionStrikethrough.setObjectName("actionStrikethrough")
        self.actionItalic = QtWidgets.QAction(WritingZone)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pics/32x32/format-text-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon7)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtWidgets.QAction(WritingZone)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/pics/32x32/format-text-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon8)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionPrint_directly = QtWidgets.QAction(WritingZone)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/pics/32x32/document-print-direct.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint_directly.setIcon(icon9)
        self.actionPrint_directly.setObjectName("actionPrint_directly")

        self.retranslateUi(WritingZone)
        QtCore.QMetaObject.connectSlotsByName(WritingZone)

    def retranslateUi(self, WritingZone):

        WritingZone.setWindowTitle(_("Form"))
        self.historyPreviousToolButton.setText(_("<-"))
        self.historyNextToolButton.setText(_("->"))
        self.findPreviousToolButton.setText(_("<-"))
        self.findNextToolButton.setText(_("->"))
        self.actionCopy.setText(_("Copy"))
        self.actionCopy.setShortcut(_("Ctrl+C"))
        self.actionPaste.setText(_("Paste"))
        self.actionPaste.setShortcut(_("Ctrl+V"))
        self.actionCut.setText(_("Cut"))
        self.actionCut.setShortcut(_("Ctrl+X"))
        self.actionBold.setText(_("Bold"))
        self.actionBold.setShortcut(_("Ctrl+B"))
        self.actionStrikethrough.setText(_("Strikethrough"))
        self.actionItalic.setText(_("Italic"))
        self.actionItalic.setShortcut(_("Ctrl+I"))
        self.actionUnderline.setText(_("Underline"))
        self.actionUnderline.setShortcut(_("Ctrl+U"))
        self.actionPrint_directly.setText(_("Print directly"))
        self.actionPrint_directly.setShortcut(_("Ctrl+Shift+P"))

from .minimap import Minimap
from .minimap_text_browser import Minimap2
from .rich_text_edit import RichTextEdit
from .tool_bar import ToolBar
