// Generated by Qleany v1.4.2 from i_entity_unit_of_work_h.tera
#pragma once

#include "direct_access/system/i_system_repository.h"
#include "entities/system.h"
#include "unit_of_work/unit_of_work.h"

namespace Skribisto::DirectAccess::System
{
namespace SCE = Common::Entities;
namespace SCUoW = Common::UnitOfWork;
namespace SCDSystem = Common::DirectAccess::System;

// a bit of magic to share interface definitions between all the units of work interfaces
using ISystemUnitOfWork = SCUoW::IEntityWithRelationships<SCE::System, SCDSystem::SystemRelationshipField>;

} // namespace Skribisto::DirectAccess::System
